// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_pwc_peri package generated by `tlgen.py` tool

package tl_pwc_peri_pkg;

  localparam logic [31:0] ADDR_SPACE_GPIO                    = 32'h 30000000;
  localparam logic [31:0] ADDR_SPACE_RV_TIMER                = 32'h 30100000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_RET_AON__REGS = 32'h 30500000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_RET_AON__RAM  = 32'h 30600000;
  localparam logic [31:0] ADDR_SPACE_AON_TIMER_AON           = 32'h 30470000;

  localparam logic [31:0] ADDR_MASK_GPIO                    = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_RV_TIMER                = 32'h 000001ff;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_RET_AON__REGS = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_RET_AON__RAM  = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_AON_TIMER_AON           = 32'h 0000003f;

  localparam int N_HOST   = 1;
  localparam int N_DEVICE = 5;

  typedef enum int {
    TlGpio = 0,
    TlRvTimer = 1,
    TlSramCtrlRetAonRegs = 2,
    TlSramCtrlRetAonRam = 3,
    TlAonTimerAon = 4
  } tl_device_e;

  typedef enum int {
    TlPwcMain = 0
  } tl_host_e;

endpackage
