# SPDX-FileCopyrightText: 2023 - 2025 Rivos Inc.
#
# SPDX-License-Identifier: LicenseRef-Rivos-Internal-Only

include:
  # https://gitlab.ba.rivosinc.com/rv/group_gitlab_config/raw/rivos/main/ci_includes/pre-commit-lint.yml
  - project: "rv/group_gitlab_config"
    ref: rivos/main
    file: "/ci_includes/pre-commit-lint.yml"

stages:
  - prebuild
  - check
  - build
  - build_docs

# Only run CI on merge requests events happening on a protected branch
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_PROTECTED == "true"

variables:
  DOCKER_TLS_CERTDIR: ""
  GIT_CLEAN_FLAGS: -ffdx -e .cache/ -e 11e283c7cfdf742e8a30d55ba62ebe28/
  OT_DESTRUCTIVE: 1

#
# Authentication helper for git accesses.
#
# It transforms the SSH repository URLs (working in the developers environment)
# into HTTPS ones authenticated by the CI Job token.
#
# Use environment variables to store the Git config to avoid storing the
# config in the CI runner's home (where it might leak to other runs), or in
# the repository itself (where the OpenTitan scripts would detect it as a
# dirty file and remove it).
#
.git-auth-fixup: &git-auth-fixup
  before_script:
    - export GIT_CONFIG_COUNT=2
    - export GIT_CONFIG_KEY_0=url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ba.rivosinc.com/".insteadOf
    - export GIT_CONFIG_VALUE_0='git@gitlab.ba.rivosinc.com:'
    - export GIT_CONFIG_KEY_1=url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ba.rivosinc.com/".insteadOf
    - export GIT_CONFIG_VALUE_1="ssh://git@gitlab.ba.rivosinc.com"

.clone-rvsys: &clone-rvsys
  - mkdir hw/foundry
  - git clone --depth 1 --branch rivos/main https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ba.rivosinc.com/rv/si/int/rvsys.git hw/foundry/rvsys

.setup-ot-env: &setup-ot-env
  - module purge
  - module load rivos/init rust
  - uv venv
  - source .venv/bin/activate
  - uv pip sync python-requirements.txt

check_freeze:
  tags: [shell]
  stage: check
  extends: .git-auth-fixup
  script:
    - module load rivos/init rust
    - python3 ci/scripts/freeze/freeze.py --freeze-file BLOCKFILE
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "rivos/main" && $CI_PIPELINE_SOURCE == "merge_request_event"'
  variables:
    FREEZE_API_SERVER_URL: https://script.google.com/macros/s/AKfycbzBJYJCfh6R8nmNs1SZTr1RxN6s7EwR8Np_rnOohm4QkTQjCCxixePIRiwaTnIo9cjZsA/exec

check_change_id:
  tags: [shell]
  stage: check
  script:
    - ./ci/scripts/check-change-id.sh

quick_lint:
  stage: check
  image: gitlab.ba.rivosinc.com:5050/rv/si/ext/opentitan-integrated
  extends: .git-auth-fixup
  before_script:
    - git config --global --add safe.directory /builds/rv/si/ext/opentitan-integrated
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  script:
    - ./ci/scripts/exec-check.sh
    - ./ci/scripts/check-ascii.sh
    - ./ci/scripts/python-lint.sh $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    # - ./ci/scripts/mypy.sh
    - ruff check
    - ./ci/scripts/validate_testplans.sh
    - ./bazelisk.sh test //quality:clang_format_check
    - ./bazelisk.sh test //quality:rustfmt_check
    # - ./bazelisk.sh test //quality:shellcheck_check
    - ./ci/scripts/include-guard.sh $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - ./ci/scripts/whitespace.sh $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    # - ./ci/scripts/check-links.sh
    - ./ci/scripts/check-cmdgen.sh
    #- ./ci/scripts/check-lock-files.sh

check_generated:
  tags: [shell]
  stage: check
  extends: .git-auth-fixup
  script:
    - *setup-ot-env
    - *clone-rvsys
    - ./ci/scripts/check-generated.sh
  rules:
    - if: $CI_COMMIT_BRANCH != "rivos/ga0"
      changes:
      - hw/**/*
      - generated_ips/*
      when: always

.lint-rtl:
  tags: [centos7-hw-shell]
  stage: check
  extends: .git-auth-fixup
  script:
    - *setup-ot-env
    - *clone-rvsys
    - module load ascentlint
    - fusesoc --cores-root . run --flag fileset_top --flag fileset_opentitan_lint --target lint --tool ascentlint --flag local_exe  lowrisc:systems:${TEST_TARGET} || true
    - grep "^E " "build/lowrisc_systems_${TEST_TARGET}_0.1/lint-ascentlint/ascentlint.log" | grep -v "ToolWaived" || true
    - egrep -iq -e "^No (New lint|lint) violations found" -e "^Found [0-9]+ Info (New lint|lint) violation" build/lowrisc_systems_${TEST_TARGET}_0.1/lint-ascentlint/ascentlint.log && echo "***PASSED***" || (echo "***ERROR*** Lint run found new errors or warnings." "Please check ascentlint.rpt" && exit 1)
  rules:
    - if: $CI_COMMIT_BRANCH != "rivos/ga0"
      changes:
      - hw/**/*
      when: always
  artifacts:
    when: on_failure
    paths:
      - build/lowrisc_systems_${TEST_TARGET}_0.1/lint-ascentlint/*.log
      - build/lowrisc_systems_${TEST_TARGET}_0.1/lint-ascentlint/*.rpt
    expire_in: 1 week

# TODO: re-enable these once we fix the fusesoc version in CI
lint_rot:
  extends: .lint-rtl
  variables:
   TEST_TARGET: top_darjeeling

lint_mio:
 extends: .lint-rtl
 variables:
   TEST_TARGET: top_mio

lint_pwc:
 extends: .lint-rtl
 variables:
   TEST_TARGET: top_pwc

# Common initialization step for Docker-in-Docker jobs
.prepare-docker: &prepare-docker
  extends: .git-auth-fixup
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:20.10
  services:
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:20.10-dind
      alias: docker
  before_script:
    # login to the gitlab container registry
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    # login to the gitlab dependency proxy
    - docker login -u "$CI_DEPENDENCY_PROXY_USER" -p "$CI_DEPENDENCY_PROXY_PASSWORD" $CI_DEPENDENCY_PROXY_SERVER

build_ot_container:
  stage: build
  extends: .prepare-docker
  variables:
    # Enable Docker BuildKit, which is required for secrets
    DOCKER_BUILDKIT: "1"
  script:
    - ./ci/scripts/build-push-container-image.sh
  rules:
    - changes:
      - "*-requirements.txt"
      - util/**/*
      - ci/scripts/build-push-container-image.sh
      when: always

create-pages:
  stage: build_docs
  image: gitlab.ba.rivosinc.com:5050/rv/si/ext/opentitan-integrated
  pages:
    # The folder that contains the files to be exposed at the Page URL
    publish: build-site/book
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - git config --global --add safe.directory /builds/rv/si/ext/opentitan-integrated
  script:
    - util/site/build-docs.sh build
