# sops file defining which secrets are encrypted for the tapeout
keys: &kms_arn 'arn:aws:kms:us-east-2:332666482539:key/908f3d89-7bd8-4e5d-aee5-5efa938202b2'
creation_rules:
  - path_regex: hw/top_darjeeling/data/top_darjeeling_seed.tapeout.hjson
    kms: *kms_arn
  - path_regex: hw/top_darjeeling/data/autogen/top_darjeeling.secrets.tapeout.gen.hjson
    kms: *kms_arn
  - path_regex: hw/top_darjeeling/rtl/autogen/tapeout/top_darjeeling_rnd_cnst_pkg.sv
    kms: *kms_arn
  - path_regex: hw/top_darjeeling/rtl/autogen/tapeout/lc_ctrl_state_pkg.sv
    kms: *kms_arn
  - path_regex: hw/top_mio/data/top_mio_seed.tapeout.hjson
    kms: *kms_arn
  - path_regex: hw/top_mio/data/autogen/top_mio.secrets.tapeout.gen.hjson
    kms: *kms_arn
  - path_regex: hw/top_mio/rtl/autogen/tapeout/top_mio_rnd_cnst_pkg.sv
    kms: *kms_arn
  - path_regex: hw/top_pwc/data/top_pwc_seed.tapeout.hjson
    kms: *kms_arn
  - path_regex: hw/top_pwc/data/autogen/top_pwc.secrets.tapeout.gen.hjson
    kms: *kms_arn
  - path_regex: hw/top_pwc/rtl/autogen/tapeout/top_pwc_rnd_cnst_pkg.sv
    kms: *kms_arn
