// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_pwc_main_bind module generated by `tlgen.py` tool for assertions
module xbar_pwc_main_bind;
`ifndef GATE_LEVEL
  // Host interfaces
  bind xbar_pwc_main tlul_assert #(.EndpointType("Device")) tlul_assert_host_rv_core_ibex__corei (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_rv_core_ibex__corei_i),
    .d2h    (tl_rv_core_ibex__corei_o)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Device")) tlul_assert_host_rv_core_ibex__cored (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_rv_core_ibex__cored_i),
    .d2h    (tl_rv_core_ibex__cored_o)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Device")) tlul_assert_host_rv_dm__sba (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_rv_dm__sba_i),
    .d2h    (tl_rv_dm__sba_o)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Device")) tlul_assert_host_dma__host (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_dma__host_i),
    .d2h    (tl_dma__host_o)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Device")) tlul_assert_host_mbx0__sram (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_mbx0__sram_i),
    .d2h    (tl_mbx0__sram_o)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Device")) tlul_assert_host_mbx1__sram (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_mbx1__sram_i),
    .d2h    (tl_mbx1__sram_o)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Device")) tlul_assert_host_mbx2__sram (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_mbx2__sram_i),
    .d2h    (tl_mbx2__sram_o)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Device")) tlul_assert_host_mbx3__sram (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_mbx3__sram_i),
    .d2h    (tl_mbx3__sram_o)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Device")) tlul_assert_host_mbx4__sram (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_mbx4__sram_i),
    .d2h    (tl_mbx4__sram_o)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Device")) tlul_assert_host_mbx5__sram (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_mbx5__sram_i),
    .d2h    (tl_mbx5__sram_o)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Device")) tlul_assert_host_mbx_pcie0__sram (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_mbx_pcie0__sram_i),
    .d2h    (tl_mbx_pcie0__sram_o)
  );

  // Device interfaces
  bind xbar_pwc_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_rv_dm__regs (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_rv_dm__regs_o),
    .d2h    (tl_rv_dm__regs_i)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_rv_dm__mem (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_rv_dm__mem_o),
    .d2h    (tl_rv_dm__mem_i)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_pwc_peri (
    .clk_i  (clk_fixed_i),
    .rst_ni (rst_fixed_ni),
    .h2d    (tl_pwc_peri_o),
    .d2h    (tl_pwc_peri_i)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_pwc_soc_proxy__core (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_pwc_soc_proxy__core_o),
    .d2h    (tl_pwc_soc_proxy__core_i)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_pwc_soc_proxy__ctn (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_pwc_soc_proxy__ctn_o),
    .d2h    (tl_pwc_soc_proxy__ctn_i)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_rv_plic_pwc (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_rv_plic_pwc_o),
    .d2h    (tl_rv_plic_pwc_i)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_rv_core_ibex__cfg (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_rv_core_ibex__cfg_o),
    .d2h    (tl_rv_core_ibex__cfg_i)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_sram_ctrl_main__regs (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_sram_ctrl_main__regs_o),
    .d2h    (tl_sram_ctrl_main__regs_i)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_sram_ctrl_main__ram (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_sram_ctrl_main__ram_o),
    .d2h    (tl_sram_ctrl_main__ram_i)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_sram_ctrl_mbox__regs (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_sram_ctrl_mbox__regs_o),
    .d2h    (tl_sram_ctrl_mbox__regs_i)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_sram_ctrl_mbox__ram (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_sram_ctrl_mbox__ram_o),
    .d2h    (tl_sram_ctrl_mbox__ram_i)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_dma (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_dma_o),
    .d2h    (tl_dma_i)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_mbx0__core (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_mbx0__core_o),
    .d2h    (tl_mbx0__core_i)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_mbx1__core (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_mbx1__core_o),
    .d2h    (tl_mbx1__core_i)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_mbx2__core (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_mbx2__core_o),
    .d2h    (tl_mbx2__core_i)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_mbx3__core (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_mbx3__core_o),
    .d2h    (tl_mbx3__core_i)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_mbx4__core (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_mbx4__core_o),
    .d2h    (tl_mbx4__core_i)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_mbx5__core (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_mbx5__core_o),
    .d2h    (tl_mbx5__core_i)
  );
  bind xbar_pwc_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_mbx_pcie0__core (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_mbx_pcie0__core_o),
    .d2h    (tl_mbx_pcie0__core_i)
  );
`endif
endmodule
