// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

#include "hw/top_pwc/sw/autogen/top_pwc.h"

/**
 * PLIC Interrupt Source to Peripheral Map
 *
 * This array is a mapping from `top_pwc_plic_irq_id_t` to
 * `top_pwc_plic_peripheral_t`.
 */
const top_pwc_plic_peripheral_t
    top_pwc_plic_interrupt_for_peripheral[89] = {
  [kTopPwcPlicIrqIdNone] = kTopPwcPlicPeripheralUnknown,
  [kTopPwcPlicIrqIdGpioGpio0] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio1] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio2] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio3] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio4] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio5] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio6] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio7] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio8] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio9] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio10] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio11] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio12] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio13] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio14] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio15] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio16] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio17] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio18] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio19] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio20] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio21] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio22] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio23] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio24] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio25] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio26] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio27] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio28] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio29] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio30] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdGpioGpio31] = kTopPwcPlicPeripheralGpio,
  [kTopPwcPlicIrqIdRvTimerTimerExpiredHart0Timer0] = kTopPwcPlicPeripheralRvTimer,
  [kTopPwcPlicIrqIdAonTimerAonWkupTimerExpired] = kTopPwcPlicPeripheralAonTimerAon,
  [kTopPwcPlicIrqIdAonTimerAonWdogTimerBark] = kTopPwcPlicPeripheralAonTimerAon,
  [kTopPwcPlicIrqIdSocProxyExternal0] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal1] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal2] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal3] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal4] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal5] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal6] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal7] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal8] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal9] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal10] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal11] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal12] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal13] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal14] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal15] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal16] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal17] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal18] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal19] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal20] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal21] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal22] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal23] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal24] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal25] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal26] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal27] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal28] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal29] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal30] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdSocProxyExternal31] = kTopPwcPlicPeripheralSocProxy,
  [kTopPwcPlicIrqIdDmaDmaDone] = kTopPwcPlicPeripheralDma,
  [kTopPwcPlicIrqIdDmaDmaChunkDone] = kTopPwcPlicPeripheralDma,
  [kTopPwcPlicIrqIdDmaDmaError] = kTopPwcPlicPeripheralDma,
  [kTopPwcPlicIrqIdMbx0MbxReady] = kTopPwcPlicPeripheralMbx0,
  [kTopPwcPlicIrqIdMbx0MbxAbort] = kTopPwcPlicPeripheralMbx0,
  [kTopPwcPlicIrqIdMbx0MbxError] = kTopPwcPlicPeripheralMbx0,
  [kTopPwcPlicIrqIdMbx1MbxReady] = kTopPwcPlicPeripheralMbx1,
  [kTopPwcPlicIrqIdMbx1MbxAbort] = kTopPwcPlicPeripheralMbx1,
  [kTopPwcPlicIrqIdMbx1MbxError] = kTopPwcPlicPeripheralMbx1,
  [kTopPwcPlicIrqIdMbx2MbxReady] = kTopPwcPlicPeripheralMbx2,
  [kTopPwcPlicIrqIdMbx2MbxAbort] = kTopPwcPlicPeripheralMbx2,
  [kTopPwcPlicIrqIdMbx2MbxError] = kTopPwcPlicPeripheralMbx2,
  [kTopPwcPlicIrqIdMbx3MbxReady] = kTopPwcPlicPeripheralMbx3,
  [kTopPwcPlicIrqIdMbx3MbxAbort] = kTopPwcPlicPeripheralMbx3,
  [kTopPwcPlicIrqIdMbx3MbxError] = kTopPwcPlicPeripheralMbx3,
  [kTopPwcPlicIrqIdMbx4MbxReady] = kTopPwcPlicPeripheralMbx4,
  [kTopPwcPlicIrqIdMbx4MbxAbort] = kTopPwcPlicPeripheralMbx4,
  [kTopPwcPlicIrqIdMbx4MbxError] = kTopPwcPlicPeripheralMbx4,
  [kTopPwcPlicIrqIdMbx5MbxReady] = kTopPwcPlicPeripheralMbx5,
  [kTopPwcPlicIrqIdMbx5MbxAbort] = kTopPwcPlicPeripheralMbx5,
  [kTopPwcPlicIrqIdMbx5MbxError] = kTopPwcPlicPeripheralMbx5,
};
