// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package mio_soc_proxy_reg_pkg;

  // Address widths within the block
  parameter int CoreAw = 1;
  parameter int CtnAw = 1;

  // Number of registers for every interface
  parameter int NumRegsCore = 0;
  parameter int NumRegsCtn = 0;

endpackage
