// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tb__xbar_connect generated by `topgen.py` tool

// This file must be `included in `hw/top_<toplevel>/dv/tb/tb.sv.

`define DRIVE_CHIP_TL_HOST_IF(tl_name, inst_name, sig_name) \
     force ``tl_name``_tl_if.d2h = dut.top_mio.u_``inst_name``.``sig_name``_i; \
     force dut.top_mio.u_``inst_name``.``sig_name``_o = ``tl_name``_tl_if.h2d; \
     force dut.top_mio.u_``inst_name``.clk_i = 0; \
     uvm_config_db#(virtual tl_if)::set(null, $sformatf("*env.%0s_agent", `"tl_name`"), "vif", \
                                        ``tl_name``_tl_if);

`define DRIVE_CHIP_TL_DEVICE_IF(tl_name, inst_name, sig_name) \
     force ``tl_name``_tl_if.h2d = dut.top_mio.u_``inst_name``.``sig_name``_i; \
     force dut.top_mio.u_``inst_name``.``sig_name``_o = ``tl_name``_tl_if.d2h; \
     force dut.top_mio.u_``inst_name``.clk_i = 0; \
     uvm_config_db#(virtual tl_if)::set(null, $sformatf("*env.%0s_agent", `"tl_name`"), "vif", \
                                        ``tl_name``_tl_if);

`define DRIVE_CHIP_TL_EXT_DEVICE_IF(tl_name, inst_name, port_name) \
     force ``tl_name``_tl_if.h2d = dut.u_``inst_name``.``port_name``_i; \
     force dut.u_``inst_name``.``port_name``_o = ``tl_name``_tl_if.d2h; \
     uvm_config_db#(virtual tl_if)::set(null, $sformatf("*env.%0s_agent", `"tl_name`"), "vif", \
                                        ``tl_name``_tl_if);


tl_if rv_core_ibex__corei_tl_if(clk_ext_main, rst_n);
tl_if rv_core_ibex__cored_tl_if(clk_ext_main, rst_n);
tl_if rv_dm__sba_tl_if(clk_ext_main, rst_n);
tl_if dma__host_tl_if(clk_ext_main, rst_n);
tl_if mbx0__sram_tl_if(clk_ext_main, rst_n);
tl_if mbx1__sram_tl_if(clk_ext_main, rst_n);
tl_if mbx2__sram_tl_if(clk_ext_main, rst_n);
tl_if mbx3__sram_tl_if(clk_ext_main, rst_n);
tl_if mbx4__sram_tl_if(clk_ext_main, rst_n);
tl_if mbx5__sram_tl_if(clk_ext_main, rst_n);
tl_if mbx_pcie0__sram_tl_if(clk_ext_main, rst_n);

tl_if rv_dm__regs_tl_if(clk_ext_main, rst_n);
tl_if rv_dm__mem_tl_if(clk_ext_main, rst_n);
tl_if soc_proxy__core_tl_if(clk_ext_main, rst_n);
tl_if soc_proxy__ctn_tl_if(clk_ext_main, rst_n);
tl_if rv_plic_tl_if(clk_ext_main, rst_n);
tl_if rv_core_ibex__cfg_tl_if(clk_ext_main, rst_n);
tl_if sram_ctrl_main__regs_tl_if(clk_ext_main, rst_n);
tl_if sram_ctrl_main__ram_tl_if(clk_ext_main, rst_n);
tl_if sram_ctrl_mbox__regs_tl_if(clk_ext_main, rst_n);
tl_if sram_ctrl_mbox__ram_tl_if(clk_ext_main, rst_n);
tl_if dma_tl_if(clk_ext_main, rst_n);
tl_if mbx0__core_tl_if(clk_ext_main, rst_n);
tl_if mbx1__core_tl_if(clk_ext_main, rst_n);
tl_if mbx2__core_tl_if(clk_ext_main, rst_n);
tl_if mbx3__core_tl_if(clk_ext_main, rst_n);
tl_if mbx4__core_tl_if(clk_ext_main, rst_n);
tl_if mbx5__core_tl_if(clk_ext_main, rst_n);
tl_if mbx_pcie0__core_tl_if(clk_ext_main, rst_n);
tl_if rv_timer_tl_if(clk_ext_io_div4, rst_n);
tl_if sram_ctrl_ret_aon__regs_tl_if(clk_ext_io_div4, rst_n);
tl_if sram_ctrl_ret_aon__ram_tl_if(clk_ext_io_div4, rst_n);
tl_if aon_timer_aon_tl_if(clk_ext_io_div4, rst_n);
tl_if mbx0__soc_tl_if(clk_ext_main, rst_n);
tl_if mbx1__soc_tl_if(clk_ext_main, rst_n);
tl_if mbx2__soc_tl_if(clk_ext_main, rst_n);
tl_if mbx3__soc_tl_if(clk_ext_main, rst_n);
tl_if mbx4__soc_tl_if(clk_ext_main, rst_n);
tl_if mbx5__soc_tl_if(clk_ext_main, rst_n);
tl_if mbx_pcie0__soc_tl_if(clk_ext_main, rst_n);
tl_if racl_ctrl_tl_if(clk_ext_main, rst_n);

initial begin
  wait (xbar_mode !== 1'bx);
  if (xbar_mode) begin
    // only enable assertions in xbar as many pins are unconnected
    $assertoff(0, tb);
    $asserton(0, tb.dut.top_mio.u_xbar_mio_main);
    $asserton(0, tb.dut.top_mio.u_xbar_mio_peri);
    $asserton(0, tb.dut.top_mio.u_xbar_mio_mbx);


    // These are all zero-time: anything that consumes time go at the end.

    // bypass clkmgr, force clocks directly
    force tb.dut.top_mio.u_xbar_mio_main.clk_main_i = clk_ext_main;
    force tb.dut.top_mio.u_xbar_mio_main.clk_fixed_i = clk_ext_io_div4;
    force tb.dut.top_mio.u_xbar_mio_peri.clk_peri_i = clk_ext_io_div4;
    force tb.dut.top_mio.u_xbar_mio_mbx.clk_mbx_i = clk_ext_main;

    // bypass rstmgr, force resets directly
    force tb.dut.top_mio.u_xbar_mio_main.rst_main_ni = rst_n;
    force tb.dut.top_mio.u_xbar_mio_main.rst_fixed_ni = rst_n;
    force tb.dut.top_mio.u_xbar_mio_peri.rst_peri_ni = rst_n;
    force tb.dut.top_mio.u_xbar_mio_mbx.rst_mbx_ni = rst_n;

`ifndef GATE_LEVEL
    `DRIVE_CHIP_TL_HOST_IF(rv_core_ibex__corei, rv_core_ibex, corei_tl_h)
    `DRIVE_CHIP_TL_HOST_IF(rv_core_ibex__cored, rv_core_ibex, cored_tl_h)
    `DRIVE_CHIP_TL_HOST_IF(rv_dm__sba, rv_dm, sba_tl_h)
    `DRIVE_CHIP_TL_DEVICE_IF(rv_dm__regs, rv_dm, regs_tl_d)
    `DRIVE_CHIP_TL_DEVICE_IF(rv_dm__mem, rv_dm, mem_tl_d)
    `DRIVE_CHIP_TL_DEVICE_IF(soc_proxy__core, soc_proxy, core_tl)
    `DRIVE_CHIP_TL_DEVICE_IF(soc_proxy__ctn, soc_proxy, ctn_tl)
    `DRIVE_CHIP_TL_DEVICE_IF(rv_plic, rv_plic, tl)
    `DRIVE_CHIP_TL_DEVICE_IF(rv_core_ibex__cfg, rv_core_ibex, cfg_tl_d)
    `DRIVE_CHIP_TL_DEVICE_IF(sram_ctrl_main__regs, sram_ctrl_main, regs_tl)
    `DRIVE_CHIP_TL_DEVICE_IF(sram_ctrl_main__ram, sram_ctrl_main, ram_tl)
    `DRIVE_CHIP_TL_DEVICE_IF(sram_ctrl_mbox__regs, sram_ctrl_mbox, regs_tl)
    `DRIVE_CHIP_TL_DEVICE_IF(sram_ctrl_mbox__ram, sram_ctrl_mbox, ram_tl)
    `DRIVE_CHIP_TL_DEVICE_IF(dma, dma, tl_d)
    `DRIVE_CHIP_TL_HOST_IF(dma__host, dma, host_tl_h)
    `DRIVE_CHIP_TL_DEVICE_IF(mbx0__core, mbx0, core_tl_d)
    `DRIVE_CHIP_TL_HOST_IF(mbx0__sram, mbx0, sram_tl_h)
    `DRIVE_CHIP_TL_DEVICE_IF(mbx1__core, mbx1, core_tl_d)
    `DRIVE_CHIP_TL_HOST_IF(mbx1__sram, mbx1, sram_tl_h)
    `DRIVE_CHIP_TL_DEVICE_IF(mbx2__core, mbx2, core_tl_d)
    `DRIVE_CHIP_TL_HOST_IF(mbx2__sram, mbx2, sram_tl_h)
    `DRIVE_CHIP_TL_DEVICE_IF(mbx3__core, mbx3, core_tl_d)
    `DRIVE_CHIP_TL_HOST_IF(mbx3__sram, mbx3, sram_tl_h)
    `DRIVE_CHIP_TL_DEVICE_IF(mbx4__core, mbx4, core_tl_d)
    `DRIVE_CHIP_TL_HOST_IF(mbx4__sram, mbx4, sram_tl_h)
    `DRIVE_CHIP_TL_DEVICE_IF(mbx5__core, mbx5, core_tl_d)
    `DRIVE_CHIP_TL_HOST_IF(mbx5__sram, mbx5, sram_tl_h)
    `DRIVE_CHIP_TL_DEVICE_IF(mbx_pcie0__core, mbx_pcie0, core_tl_d)
    `DRIVE_CHIP_TL_HOST_IF(mbx_pcie0__sram, mbx_pcie0, sram_tl_h)
    `DRIVE_CHIP_TL_DEVICE_IF(rv_timer, rv_timer, tl)
    `DRIVE_CHIP_TL_DEVICE_IF(sram_ctrl_ret_aon__regs, sram_ctrl_ret_aon, regs_tl)
    `DRIVE_CHIP_TL_DEVICE_IF(sram_ctrl_ret_aon__ram, sram_ctrl_ret_aon, ram_tl)
    `DRIVE_CHIP_TL_DEVICE_IF(aon_timer_aon, aon_timer_aon, tl)
    `DRIVE_CHIP_TL_DEVICE_IF(mbx0__soc, mbx0, soc_tl_d)
    `DRIVE_CHIP_TL_DEVICE_IF(mbx1__soc, mbx1, soc_tl_d)
    `DRIVE_CHIP_TL_DEVICE_IF(mbx2__soc, mbx2, soc_tl_d)
    `DRIVE_CHIP_TL_DEVICE_IF(mbx3__soc, mbx3, soc_tl_d)
    `DRIVE_CHIP_TL_DEVICE_IF(mbx4__soc, mbx4, soc_tl_d)
    `DRIVE_CHIP_TL_DEVICE_IF(mbx5__soc, mbx5, soc_tl_d)
    `DRIVE_CHIP_TL_DEVICE_IF(mbx_pcie0__soc, mbx_pcie0, soc_tl_d)
    `DRIVE_CHIP_TL_DEVICE_IF(racl_ctrl, racl_ctrl, tl)
`endif

    // And this can consume time, so they go at the end of this block.

    // Wait for a negedge of rst_n, or else we will have clock edges before
    // reset, which could capture 'X values.
    xbar_clk_rst_if.wait_for_reset(.wait_posedge(1'b0));


  end
end

`undef DRIVE_CHIP_TL_HOST_IF
`undef DRIVE_CHIP_TL_DEVICE_IF
`undef DRIVE_CHIP_TL_EXT_DEVICE_IF
