// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `topgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"rv_dm__regs", '{
        '{32'h21200000, 32'h2120000f}
    }},
    '{"rv_dm__mem", '{
        '{32'h00040000, 32'h00040fff}
    }},
    '{"mio_soc_proxy__ctn", '{
        '{32'h40000000, 32'hbfffffff}
    }},
    '{"rv_plic_mio", '{
        '{32'h28000000, 32'h2fffffff}
    }},
    '{"rv_core_ibex_mio__cfg", '{
        '{32'h211f0000, 32'h211f07ff}
    }},
    '{"sram_ctrl_main__regs", '{
        '{32'h211c0000, 32'h211c003f}
    }},
    '{"sram_ctrl_main__ram", '{
        '{32'h10000000, 32'h1000ffff}
    }},
    '{"sram_ctrl_mbox__regs", '{
        '{32'h211d0000, 32'h211d003f}
    }},
    '{"sram_ctrl_mbox__ram", '{
        '{32'h11000000, 32'h11000fff}
    }},
    '{"dma", '{
        '{32'h22010000, 32'h220101ff}
    }},
    '{"mbx0__core", '{
        '{32'h22000000, 32'h2200007f}
    }},
    '{"mbx1__core", '{
        '{32'h22000100, 32'h2200017f}
    }},
    '{"mbx2__core", '{
        '{32'h22000200, 32'h2200027f}
    }},
    '{"mbx3__core", '{
        '{32'h22000300, 32'h2200037f}
    }},
    '{"mbx4__core", '{
        '{32'h22000400, 32'h2200047f}
    }},
    '{"mbx5__core", '{
        '{32'h22000500, 32'h2200057f}
    }},
    '{"mbx_pcie0__core", '{
        '{32'h22040000, 32'h2204007f}
    }},
    '{"rv_timer", '{
        '{32'h30000000, 32'h300001ff}
    }},
    '{"sram_ctrl_ret_aon__regs", '{
        '{32'h30500000, 32'h3050003f}
    }},
    '{"sram_ctrl_ret_aon__ram", '{
        '{32'h30600000, 32'h30600fff}
    }},
    '{"aon_timer_aon", '{
        '{32'h30470000, 32'h3047003f}
    }},
    '{"mbx0__soc", '{
        '{32'h01485000, 32'h0148501f}
    }},
    '{"mbx1__soc", '{
        '{32'h01485100, 32'h0148511f}
    }},
    '{"mbx2__soc", '{
        '{32'h01485200, 32'h0148521f}
    }},
    '{"mbx3__soc", '{
        '{32'h01485300, 32'h0148531f}
    }},
    '{"mbx4__soc", '{
        '{32'h01485400, 32'h0148541f}
    }},
    '{"mbx5__soc", '{
        '{32'h01485500, 32'h0148551f}
    }},
    '{"mbx_pcie0__soc", '{
        '{32'h01480100, 32'h0148011f}
    }},
    '{"racl_ctrl_mio", '{
        '{32'h01481f00, 32'h01481fff}
    }},
    '{"ac_range_check_mio", '{
        '{32'h01484000, 32'h014843ff}
    }}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"rv_core_ibex_mio__corei", 0, '{
        "rv_dm__mem",
        "sram_ctrl_main__ram",
        "mio_soc_proxy__ctn"}}
    ,
    '{"rv_core_ibex_mio__cored", 1, '{
        "rv_dm__mem",
        "rv_dm__regs",
        "sram_ctrl_main__ram",
        "rv_timer",
        "sram_ctrl_ret_aon__ram",
        "sram_ctrl_ret_aon__regs",
        "aon_timer_aon",
        "rv_plic_mio",
        "sram_ctrl_main__regs",
        "rv_core_ibex_mio__cfg",
        "sram_ctrl_mbox__ram",
        "sram_ctrl_mbox__regs",
        "mio_soc_proxy__ctn",
        "dma",
        "mbx0__core",
        "mbx1__core",
        "mbx2__core",
        "mbx3__core",
        "mbx4__core",
        "mbx5__core",
        "mbx_pcie0__core"}}
    ,
    '{"rv_dm__sba", 2, '{
        "rv_dm__mem",
        "rv_dm__regs",
        "sram_ctrl_main__ram",
        "rv_timer",
        "sram_ctrl_ret_aon__ram",
        "sram_ctrl_ret_aon__regs",
        "aon_timer_aon",
        "rv_plic_mio",
        "sram_ctrl_main__regs",
        "rv_core_ibex_mio__cfg",
        "sram_ctrl_mbox__ram",
        "sram_ctrl_mbox__regs",
        "mio_soc_proxy__ctn",
        "dma",
        "mbx0__core",
        "mbx1__core",
        "mbx2__core",
        "mbx3__core",
        "mbx4__core",
        "mbx5__core",
        "mbx_pcie0__core"}}
    ,
    '{"dma__host", 3, '{
        "sram_ctrl_main__ram",
        "sram_ctrl_mbox__ram",
        "mio_soc_proxy__ctn",
        "rv_timer",
        "sram_ctrl_ret_aon__ram",
        "sram_ctrl_ret_aon__regs",
        "aon_timer_aon"}}
    ,
    '{"mbx0__sram", 4, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx1__sram", 5, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx2__sram", 6, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx3__sram", 7, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx4__sram", 8, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx5__sram", 9, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx_pcie0__sram", 10, '{
        "sram_ctrl_mbox__ram"}}
};
