# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

exports_files(["top_pwc_racl_ctrl_pwc.ipconfig.hjson"])

filegroup(
    name = "doc_files",
    srcs = ["racl_ctrl_pwc.hjson"],
)
