// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package otp_ctrl_reg_pkg;

  // Param list
  parameter int NumSramKeyReqSlots = 4;
  parameter int OtpByteAddrWidth = 15;
  parameter int NumErrorEntries = 24;
  parameter int NumDaiWords = 2;
  parameter int NumDigestWords = 2;
  parameter int NumSwCfgWindowWords = 8192;
  parameter int NumPart = 22;
  parameter int NumPartUnbuf = 15;
  parameter int NumPartBuf = 7;
  parameter int VendorTestOffset = 0;
  parameter int VendorTestSize = 64;
  parameter int ScratchOffset = 0;
  parameter int ScratchSize = 56;
  parameter int VendorTestDigestOffset = 56;
  parameter int VendorTestDigestSize = 8;
  parameter int CreatorSwCfgOffset = 64;
  parameter int CreatorSwCfgSize = 320;
  parameter int CreatorSwCfgAstCfgOffset = 64;
  parameter int CreatorSwCfgAstCfgSize = 124;
  parameter int CreatorSwCfgAstInitEnOffset = 188;
  parameter int CreatorSwCfgAstInitEnSize = 4;
  parameter int CreatorSwCfgOverridesOffset = 192;
  parameter int CreatorSwCfgOverridesSize = 32;
  parameter int CreatorSwCfgRomExtSkuOffset = 224;
  parameter int CreatorSwCfgRomExtSkuSize = 4;
  parameter int CreatorSwCfgSigverifyRsaModExpIbexEnOffset = 228;
  parameter int CreatorSwCfgSigverifyRsaModExpIbexEnSize = 4;
  parameter int CreatorSwCfgSigverifyRsaKeyEnOffset = 232;
  parameter int CreatorSwCfgSigverifyRsaKeyEnSize = 8;
  parameter int CreatorSwCfgSigverifySpxEnOffset = 240;
  parameter int CreatorSwCfgSigverifySpxEnSize = 4;
  parameter int CreatorSwCfgSigverifySpxKeyEnOffset = 244;
  parameter int CreatorSwCfgSigverifySpxKeyEnSize = 8;
  parameter int CreatorSwCfgFlashDataDefaultCfgOffset = 252;
  parameter int CreatorSwCfgFlashDataDefaultCfgSize = 4;
  parameter int CreatorSwCfgFlashInfoBootDataCfgOffset = 256;
  parameter int CreatorSwCfgFlashInfoBootDataCfgSize = 4;
  parameter int CreatorSwCfgFlashHwInfoCfgOverrideOffset = 260;
  parameter int CreatorSwCfgFlashHwInfoCfgOverrideSize = 4;
  parameter int CreatorSwCfgRngEnOffset = 264;
  parameter int CreatorSwCfgRngEnSize = 4;
  parameter int CreatorSwCfgJitterEnOffset = 268;
  parameter int CreatorSwCfgJitterEnSize = 4;
  parameter int CreatorSwCfgRetRamResetMaskOffset = 272;
  parameter int CreatorSwCfgRetRamResetMaskSize = 4;
  parameter int CreatorSwCfgManufStateOffset = 276;
  parameter int CreatorSwCfgManufStateSize = 4;
  parameter int CreatorSwCfgRomExecEnOffset = 280;
  parameter int CreatorSwCfgRomExecEnSize = 4;
  parameter int CreatorSwCfgCpuctrlOffset = 284;
  parameter int CreatorSwCfgCpuctrlSize = 4;
  parameter int CreatorSwCfgMinSecVerRomExtOffset = 288;
  parameter int CreatorSwCfgMinSecVerRomExtSize = 4;
  parameter int CreatorSwCfgMinSecVerBl0Offset = 292;
  parameter int CreatorSwCfgMinSecVerBl0Size = 4;
  parameter int CreatorSwCfgDefaultBootDataInProdEnOffset = 296;
  parameter int CreatorSwCfgDefaultBootDataInProdEnSize = 4;
  parameter int CreatorSwCfgRmaSpinEnOffset = 300;
  parameter int CreatorSwCfgRmaSpinEnSize = 4;
  parameter int CreatorSwCfgRmaSpinCyclesOffset = 304;
  parameter int CreatorSwCfgRmaSpinCyclesSize = 4;
  parameter int CreatorSwCfgRngRepcntThresholdsOffset = 308;
  parameter int CreatorSwCfgRngRepcntThresholdsSize = 4;
  parameter int CreatorSwCfgRngRepcntsThresholdsOffset = 312;
  parameter int CreatorSwCfgRngRepcntsThresholdsSize = 4;
  parameter int CreatorSwCfgRngAdaptpHiThresholdsOffset = 316;
  parameter int CreatorSwCfgRngAdaptpHiThresholdsSize = 4;
  parameter int CreatorSwCfgRngAdaptpLoThresholdsOffset = 320;
  parameter int CreatorSwCfgRngAdaptpLoThresholdsSize = 4;
  parameter int CreatorSwCfgRngBucketThresholdsOffset = 324;
  parameter int CreatorSwCfgRngBucketThresholdsSize = 4;
  parameter int CreatorSwCfgRngMarkovHiThresholdsOffset = 328;
  parameter int CreatorSwCfgRngMarkovHiThresholdsSize = 4;
  parameter int CreatorSwCfgRngMarkovLoThresholdsOffset = 332;
  parameter int CreatorSwCfgRngMarkovLoThresholdsSize = 4;
  parameter int CreatorSwCfgRngExthtHiThresholdsOffset = 336;
  parameter int CreatorSwCfgRngExthtHiThresholdsSize = 4;
  parameter int CreatorSwCfgRngExthtLoThresholdsOffset = 340;
  parameter int CreatorSwCfgRngExthtLoThresholdsSize = 4;
  parameter int CreatorSwCfgRngAlertThresholdOffset = 344;
  parameter int CreatorSwCfgRngAlertThresholdSize = 4;
  parameter int CreatorSwCfgRngHealthConfigDigestOffset = 348;
  parameter int CreatorSwCfgRngHealthConfigDigestSize = 4;
  parameter int CreatorSwCfgSramKeyRenewEnOffset = 352;
  parameter int CreatorSwCfgSramKeyRenewEnSize = 4;
  parameter int CreatorSwCfgDigestOffset = 376;
  parameter int CreatorSwCfgDigestSize = 8;
  parameter int OwnerSwCfgOffset = 384;
  parameter int OwnerSwCfgSize = 632;
  parameter int OwnerSwCfgRomErrorReportingOffset = 384;
  parameter int OwnerSwCfgRomErrorReportingSize = 4;
  parameter int OwnerSwCfgRomBootstrapDisOffset = 388;
  parameter int OwnerSwCfgRomBootstrapDisSize = 4;
  parameter int OwnerSwCfgRomAlertClassEnOffset = 392;
  parameter int OwnerSwCfgRomAlertClassEnSize = 4;
  parameter int OwnerSwCfgRomAlertEscalationOffset = 396;
  parameter int OwnerSwCfgRomAlertEscalationSize = 4;
  parameter int OwnerSwCfgRomAlertClassificationOffset = 400;
  parameter int OwnerSwCfgRomAlertClassificationSize = 400;
  parameter int OwnerSwCfgRomLocalAlertClassificationOffset = 800;
  parameter int OwnerSwCfgRomLocalAlertClassificationSize = 64;
  parameter int OwnerSwCfgRomAlertAccumThreshOffset = 864;
  parameter int OwnerSwCfgRomAlertAccumThreshSize = 16;
  parameter int OwnerSwCfgRomAlertTimeoutCyclesOffset = 880;
  parameter int OwnerSwCfgRomAlertTimeoutCyclesSize = 16;
  parameter int OwnerSwCfgRomAlertPhaseCyclesOffset = 896;
  parameter int OwnerSwCfgRomAlertPhaseCyclesSize = 64;
  parameter int OwnerSwCfgRomAlertDigestProdOffset = 960;
  parameter int OwnerSwCfgRomAlertDigestProdSize = 4;
  parameter int OwnerSwCfgRomAlertDigestProdEndOffset = 964;
  parameter int OwnerSwCfgRomAlertDigestProdEndSize = 4;
  parameter int OwnerSwCfgRomAlertDigestDevOffset = 968;
  parameter int OwnerSwCfgRomAlertDigestDevSize = 4;
  parameter int OwnerSwCfgRomAlertDigestRmaOffset = 972;
  parameter int OwnerSwCfgRomAlertDigestRmaSize = 4;
  parameter int OwnerSwCfgRomWatchdogBiteThresholdCyclesOffset = 976;
  parameter int OwnerSwCfgRomWatchdogBiteThresholdCyclesSize = 4;
  parameter int OwnerSwCfgRomKeymgrRomExtMeasEnOffset = 980;
  parameter int OwnerSwCfgRomKeymgrRomExtMeasEnSize = 4;
  parameter int OwnerSwCfgManufStateOffset = 984;
  parameter int OwnerSwCfgManufStateSize = 4;
  parameter int OwnerSwCfgRomRstmgrInfoEnOffset = 988;
  parameter int OwnerSwCfgRomRstmgrInfoEnSize = 4;
  parameter int OwnerSwCfgDigestOffset = 1008;
  parameter int OwnerSwCfgDigestSize = 8;
  parameter int OwnershipSlotStateOffset = 1016;
  parameter int OwnershipSlotStateSize = 48;
  parameter int OwnershipSlotStateRotOwnerAuthOffset = 1016;
  parameter int OwnershipSlotStateRotOwnerAuthSize = 16;
  parameter int OwnershipSlotStatePlatIntegAuthOffset = 1032;
  parameter int OwnershipSlotStatePlatIntegAuthSize = 16;
  parameter int OwnershipSlotStatePlatOwnerAuthOffset = 1048;
  parameter int OwnershipSlotStatePlatOwnerAuthSize = 16;
  parameter int RotCreatorAuthOffset = 1064;
  parameter int RotCreatorAuthSize = 1424;
  parameter int RotCreatorAuthNonRawMfwCodesignKeyOffset = 1064;
  parameter int RotCreatorAuthNonRawMfwCodesignKeySize = 160;
  parameter int RotCreatorAuthOwnershipStateOffset = 1224;
  parameter int RotCreatorAuthOwnershipStateSize = 4;
  parameter int RotCreatorAuthRom2PatchSigverifyKeyOffset = 1228;
  parameter int RotCreatorAuthRom2PatchSigverifyKeySize = 160;
  parameter int RotCreatorAuthKeymanifestKeyOffset = 1388;
  parameter int RotCreatorAuthKeymanifestKeySize = 160;
  parameter int RotCreatorAuthUnlock4xferKeyOffset = 1548;
  parameter int RotCreatorAuthUnlock4xferKeySize = 160;
  parameter int RotCreatorAuthIdentityCertOffset = 1708;
  parameter int RotCreatorAuthIdentityCertSize = 768;
  parameter int RotCreatorAuthDigestOffset = 2480;
  parameter int RotCreatorAuthDigestSize = 8;
  parameter int RotOwnerAuthSlot0Offset = 2488;
  parameter int RotOwnerAuthSlot0Size = 328;
  parameter int RotOwnerAuthSlot0KeymanifestKeyOffset = 2488;
  parameter int RotOwnerAuthSlot0KeymanifestKeySize = 160;
  parameter int RotOwnerAuthSlot0Unlock4xferKeyOffset = 2648;
  parameter int RotOwnerAuthSlot0Unlock4xferKeySize = 160;
  parameter int RotOwnerAuthSlot0DigestOffset = 2808;
  parameter int RotOwnerAuthSlot0DigestSize = 8;
  parameter int RotOwnerAuthSlot1Offset = 2816;
  parameter int RotOwnerAuthSlot1Size = 328;
  parameter int RotOwnerAuthSlot1KeymanifestKeyOffset = 2816;
  parameter int RotOwnerAuthSlot1KeymanifestKeySize = 160;
  parameter int RotOwnerAuthSlot1Unlock4xferKeyOffset = 2976;
  parameter int RotOwnerAuthSlot1Unlock4xferKeySize = 160;
  parameter int RotOwnerAuthSlot1DigestOffset = 3136;
  parameter int RotOwnerAuthSlot1DigestSize = 8;
  parameter int PlatIntegAuthSlot0Offset = 3144;
  parameter int PlatIntegAuthSlot0Size = 328;
  parameter int PlatIntegAuthSlot0KeymanifestKeyOffset = 3144;
  parameter int PlatIntegAuthSlot0KeymanifestKeySize = 160;
  parameter int PlatIntegAuthSlot0Unlock4xferKeyOffset = 3304;
  parameter int PlatIntegAuthSlot0Unlock4xferKeySize = 160;
  parameter int PlatIntegAuthSlot0DigestOffset = 3464;
  parameter int PlatIntegAuthSlot0DigestSize = 8;
  parameter int PlatIntegAuthSlot1Offset = 3472;
  parameter int PlatIntegAuthSlot1Size = 328;
  parameter int PlatIntegAuthSlot1KeymanifestKeyOffset = 3472;
  parameter int PlatIntegAuthSlot1KeymanifestKeySize = 160;
  parameter int PlatIntegAuthSlot1Unlock4xferKeyOffset = 3632;
  parameter int PlatIntegAuthSlot1Unlock4xferKeySize = 160;
  parameter int PlatIntegAuthSlot1DigestOffset = 3792;
  parameter int PlatIntegAuthSlot1DigestSize = 8;
  parameter int PlatOwnerAuthSlot0Offset = 3800;
  parameter int PlatOwnerAuthSlot0Size = 328;
  parameter int PlatOwnerAuthSlot0KeymanifestKeyOffset = 3800;
  parameter int PlatOwnerAuthSlot0KeymanifestKeySize = 160;
  parameter int PlatOwnerAuthSlot0Unlock4xferKeyOffset = 3960;
  parameter int PlatOwnerAuthSlot0Unlock4xferKeySize = 160;
  parameter int PlatOwnerAuthSlot0DigestOffset = 4120;
  parameter int PlatOwnerAuthSlot0DigestSize = 8;
  parameter int PlatOwnerAuthSlot1Offset = 4128;
  parameter int PlatOwnerAuthSlot1Size = 328;
  parameter int PlatOwnerAuthSlot1KeymanifestKeyOffset = 4128;
  parameter int PlatOwnerAuthSlot1KeymanifestKeySize = 160;
  parameter int PlatOwnerAuthSlot1Unlock4xferKeyOffset = 4288;
  parameter int PlatOwnerAuthSlot1Unlock4xferKeySize = 160;
  parameter int PlatOwnerAuthSlot1DigestOffset = 4448;
  parameter int PlatOwnerAuthSlot1DigestSize = 8;
  parameter int PlatOwnerAuthSlot2Offset = 4456;
  parameter int PlatOwnerAuthSlot2Size = 328;
  parameter int PlatOwnerAuthSlot2KeymanifestKeyOffset = 4456;
  parameter int PlatOwnerAuthSlot2KeymanifestKeySize = 160;
  parameter int PlatOwnerAuthSlot2Unlock4xferKeyOffset = 4616;
  parameter int PlatOwnerAuthSlot2Unlock4xferKeySize = 160;
  parameter int PlatOwnerAuthSlot2DigestOffset = 4776;
  parameter int PlatOwnerAuthSlot2DigestSize = 8;
  parameter int ExtNvmOffset = 4784;
  parameter int ExtNvmSize = 1024;
  parameter int ExtNvmAntireplayFreshnessCntOffset = 4784;
  parameter int ExtNvmAntireplayFreshnessCntSize = 1024;
  parameter int RomPatchOffset = 5808;
  parameter int RomPatchSize = 10104;
  parameter int RomPatchDataOffset = 5808;
  parameter int RomPatchDataSize = 9192;
  parameter int RomPatchDigestOffset = 15904;
  parameter int RomPatchDigestSize = 8;
  parameter int SocFusesOffset = 15912;
  parameter int SocFusesSize = 4104;
  parameter int SocFusesDataOffset = 15912;
  parameter int SocFusesDataSize = 4096;
  parameter int SocFusesDigestOffset = 20008;
  parameter int SocFusesDigestSize = 8;
  parameter int HwCfg0Offset = 20016;
  parameter int HwCfg0Size = 72;
  parameter int DeviceIdOffset = 20016;
  parameter int DeviceIdSize = 32;
  parameter int ManufStateOffset = 20048;
  parameter int ManufStateSize = 32;
  parameter int HwCfg0DigestOffset = 20080;
  parameter int HwCfg0DigestSize = 8;
  parameter int HwCfg1Offset = 20088;
  parameter int HwCfg1Size = 16;
  parameter int SocDbgStateOffset = 20088;
  parameter int SocDbgStateSize = 4;
  parameter int EnSramIfetchOffset = 20092;
  parameter int EnSramIfetchSize = 1;
  parameter int HwCfg1DigestOffset = 20096;
  parameter int HwCfg1DigestSize = 8;
  parameter int Secret0Offset = 20104;
  parameter int Secret0Size = 40;
  parameter int TestUnlockTokenOffset = 20104;
  parameter int TestUnlockTokenSize = 16;
  parameter int TestExitTokenOffset = 20120;
  parameter int TestExitTokenSize = 16;
  parameter int Secret0DigestOffset = 20136;
  parameter int Secret0DigestSize = 8;
  parameter int Secret1Offset = 20144;
  parameter int Secret1Size = 88;
  parameter int FlashAddrKeySeedOffset = 20144;
  parameter int FlashAddrKeySeedSize = 32;
  parameter int FlashDataKeySeedOffset = 20176;
  parameter int FlashDataKeySeedSize = 32;
  parameter int SramDataKeySeedOffset = 20208;
  parameter int SramDataKeySeedSize = 16;
  parameter int Secret1DigestOffset = 20224;
  parameter int Secret1DigestSize = 8;
  parameter int Secret2Offset = 20232;
  parameter int Secret2Size = 120;
  parameter int RmaTokenOffset = 20232;
  parameter int RmaTokenSize = 16;
  parameter int CreatorRootKeyShare0Offset = 20248;
  parameter int CreatorRootKeyShare0Size = 32;
  parameter int CreatorRootKeyShare1Offset = 20280;
  parameter int CreatorRootKeyShare1Size = 32;
  parameter int CreatorSeedOffset = 20312;
  parameter int CreatorSeedSize = 32;
  parameter int Secret2DigestOffset = 20344;
  parameter int Secret2DigestSize = 8;
  parameter int Secret3Offset = 20352;
  parameter int Secret3Size = 40;
  parameter int OwnerSeedOffset = 20352;
  parameter int OwnerSeedSize = 32;
  parameter int Secret3DigestOffset = 20384;
  parameter int Secret3DigestSize = 8;
  parameter int LifeCycleOffset = 20392;
  parameter int LifeCycleSize = 88;
  parameter int LcTransitionCntOffset = 20392;
  parameter int LcTransitionCntSize = 48;
  parameter int LcStateOffset = 20440;
  parameter int LcStateSize = 40;
  parameter int NumAlerts = 5;

  // Address widths within the block
  parameter int CoreAw = 16;
  parameter int PrimAw = 7;

  // Number of registers for every interface
  parameter int NumRegsCore = 95;
  parameter int NumRegsPrim = 20;

  // Number of registers for every interface
  parameter int NumRegsCore = 95;
  parameter int NumRegsPrim = 8;

  ///////////////////////////////////////////////
  // Typedefs for registers for core interface //
  ///////////////////////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
    } otp_error;
    struct packed {
      logic        q;
    } otp_operation_done;
  } otp_ctrl_reg2hw_intr_state_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } otp_error;
    struct packed {
      logic        q;
    } otp_operation_done;
  } otp_ctrl_reg2hw_intr_enable_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } otp_error;
    struct packed {
      logic        q;
      logic        qe;
    } otp_operation_done;
  } otp_ctrl_reg2hw_intr_test_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } recov_prim_otp_alert;
    struct packed {
      logic        q;
      logic        qe;
    } fatal_prim_otp_alert;
    struct packed {
      logic        q;
      logic        qe;
    } fatal_bus_integ_error;
    struct packed {
      logic        q;
      logic        qe;
    } fatal_check_error;
    struct packed {
      logic        q;
      logic        qe;
    } fatal_macro_error;
  } otp_ctrl_reg2hw_alert_test_reg_t;

  typedef struct packed {
    logic        q;
    logic        qe;
  } otp_ctrl_reg2hw_direct_access_regwen_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } digest;
    struct packed {
      logic        q;
      logic        qe;
    } wr;
    struct packed {
      logic        q;
      logic        qe;
    } rd;
  } otp_ctrl_reg2hw_direct_access_cmd_reg_t;

  typedef struct packed {
    logic [14:0] q;
  } otp_ctrl_reg2hw_direct_access_address_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } otp_ctrl_reg2hw_direct_access_wdata_mreg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } consistency;
    struct packed {
      logic        q;
      logic        qe;
    } integrity;
  } otp_ctrl_reg2hw_check_trigger_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } otp_ctrl_reg2hw_check_timeout_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } otp_ctrl_reg2hw_integrity_check_period_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } otp_ctrl_reg2hw_consistency_check_period_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_vendor_test_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_creator_sw_cfg_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_owner_sw_cfg_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_ownership_slot_state_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_rot_creator_auth_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_rot_owner_auth_slot0_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_rot_owner_auth_slot1_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_plat_integ_auth_slot0_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_plat_integ_auth_slot1_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_plat_owner_auth_slot0_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_plat_owner_auth_slot1_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_plat_owner_auth_slot2_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_ext_nvm_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_rom_patch_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_soc_fuses_read_lock_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } otp_operation_done;
    struct packed {
      logic        d;
      logic        de;
    } otp_error;
  } otp_ctrl_hw2reg_intr_state_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } vendor_test_error;
    struct packed {
      logic        d;
    } creator_sw_cfg_error;
    struct packed {
      logic        d;
    } owner_sw_cfg_error;
    struct packed {
      logic        d;
    } ownership_slot_state_error;
    struct packed {
      logic        d;
    } rot_creator_auth_error;
    struct packed {
      logic        d;
    } rot_owner_auth_slot0_error;
    struct packed {
      logic        d;
    } rot_owner_auth_slot1_error;
    struct packed {
      logic        d;
    } plat_integ_auth_slot0_error;
    struct packed {
      logic        d;
    } plat_integ_auth_slot1_error;
    struct packed {
      logic        d;
    } plat_owner_auth_slot0_error;
    struct packed {
      logic        d;
    } plat_owner_auth_slot1_error;
    struct packed {
      logic        d;
    } plat_owner_auth_slot2_error;
    struct packed {
      logic        d;
    } ext_nvm_error;
    struct packed {
      logic        d;
    } rom_patch_error;
    struct packed {
      logic        d;
    } soc_fuses_error;
    struct packed {
      logic        d;
    } hw_cfg0_error;
    struct packed {
      logic        d;
    } hw_cfg1_error;
    struct packed {
      logic        d;
    } secret0_error;
    struct packed {
      logic        d;
    } secret1_error;
    struct packed {
      logic        d;
    } secret2_error;
    struct packed {
      logic        d;
    } secret3_error;
    struct packed {
      logic        d;
    } life_cycle_error;
    struct packed {
      logic        d;
    } dai_error;
    struct packed {
      logic        d;
    } lci_error;
    struct packed {
      logic        d;
    } timeout_error;
    struct packed {
      logic        d;
    } lfsr_fsm_error;
    struct packed {
      logic        d;
    } scrambling_fsm_error;
    struct packed {
      logic        d;
    } key_deriv_fsm_error;
    struct packed {
      logic        d;
    } bus_integ_error;
    struct packed {
      logic        d;
    } dai_idle;
    struct packed {
      logic        d;
    } check_pending;
  } otp_ctrl_hw2reg_status_reg_t;

  typedef struct packed {
    logic [2:0]  d;
  } otp_ctrl_hw2reg_err_code_mreg_t;

  typedef struct packed {
    logic        d;
  } otp_ctrl_hw2reg_direct_access_regwen_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_direct_access_rdata_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_vendor_test_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_creator_sw_cfg_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_owner_sw_cfg_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_rot_creator_auth_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_rot_owner_auth_slot0_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_rot_owner_auth_slot1_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_plat_integ_auth_slot0_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_plat_integ_auth_slot1_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_plat_owner_auth_slot0_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_plat_owner_auth_slot1_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_plat_owner_auth_slot2_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_rom_patch_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_soc_fuses_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_hw_cfg0_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_hw_cfg1_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_secret0_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_secret1_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_secret2_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_secret3_digest_mreg_t;

  // Register -> HW type for core interface
  typedef struct packed {
    otp_ctrl_reg2hw_intr_state_reg_t intr_state; // [219:218]
    otp_ctrl_reg2hw_intr_enable_reg_t intr_enable; // [217:216]
    otp_ctrl_reg2hw_intr_test_reg_t intr_test; // [215:212]
    otp_ctrl_reg2hw_alert_test_reg_t alert_test; // [211:202]
    otp_ctrl_reg2hw_direct_access_regwen_reg_t direct_access_regwen; // [201:200]
    otp_ctrl_reg2hw_direct_access_cmd_reg_t direct_access_cmd; // [199:194]
    otp_ctrl_reg2hw_direct_access_address_reg_t direct_access_address; // [193:179]
    otp_ctrl_reg2hw_direct_access_wdata_mreg_t [1:0] direct_access_wdata; // [178:115]
    otp_ctrl_reg2hw_check_trigger_reg_t check_trigger; // [114:111]
    otp_ctrl_reg2hw_check_timeout_reg_t check_timeout; // [110:79]
    otp_ctrl_reg2hw_integrity_check_period_reg_t integrity_check_period; // [78:47]
    otp_ctrl_reg2hw_consistency_check_period_reg_t consistency_check_period; // [46:15]
    otp_ctrl_reg2hw_vendor_test_read_lock_reg_t vendor_test_read_lock; // [14:14]
    otp_ctrl_reg2hw_creator_sw_cfg_read_lock_reg_t creator_sw_cfg_read_lock; // [13:13]
    otp_ctrl_reg2hw_owner_sw_cfg_read_lock_reg_t owner_sw_cfg_read_lock; // [12:12]
    otp_ctrl_reg2hw_ownership_slot_state_read_lock_reg_t ownership_slot_state_read_lock; // [11:11]
    otp_ctrl_reg2hw_rot_creator_auth_read_lock_reg_t rot_creator_auth_read_lock; // [10:10]
    otp_ctrl_reg2hw_rot_owner_auth_slot0_read_lock_reg_t rot_owner_auth_slot0_read_lock; // [9:9]
    otp_ctrl_reg2hw_rot_owner_auth_slot1_read_lock_reg_t rot_owner_auth_slot1_read_lock; // [8:8]
    otp_ctrl_reg2hw_plat_integ_auth_slot0_read_lock_reg_t plat_integ_auth_slot0_read_lock; // [7:7]
    otp_ctrl_reg2hw_plat_integ_auth_slot1_read_lock_reg_t plat_integ_auth_slot1_read_lock; // [6:6]
    otp_ctrl_reg2hw_plat_owner_auth_slot0_read_lock_reg_t plat_owner_auth_slot0_read_lock; // [5:5]
    otp_ctrl_reg2hw_plat_owner_auth_slot1_read_lock_reg_t plat_owner_auth_slot1_read_lock; // [4:4]
    otp_ctrl_reg2hw_plat_owner_auth_slot2_read_lock_reg_t plat_owner_auth_slot2_read_lock; // [3:3]
    otp_ctrl_reg2hw_ext_nvm_read_lock_reg_t ext_nvm_read_lock; // [2:2]
    otp_ctrl_reg2hw_rom_patch_read_lock_reg_t rom_patch_read_lock; // [1:1]
    otp_ctrl_reg2hw_soc_fuses_read_lock_reg_t soc_fuses_read_lock; // [0:0]
  } otp_ctrl_core_reg2hw_t;

  // HW -> register type for core interface
  typedef struct packed {
    otp_ctrl_hw2reg_intr_state_reg_t intr_state; // [1387:1384]
    otp_ctrl_hw2reg_status_reg_t status; // [1383:1353]
    otp_ctrl_hw2reg_err_code_mreg_t [23:0] err_code; // [1352:1281]
    otp_ctrl_hw2reg_direct_access_regwen_reg_t direct_access_regwen; // [1280:1280]
    otp_ctrl_hw2reg_direct_access_rdata_mreg_t [1:0] direct_access_rdata; // [1279:1216]
    otp_ctrl_hw2reg_vendor_test_digest_mreg_t [1:0] vendor_test_digest; // [1215:1152]
    otp_ctrl_hw2reg_creator_sw_cfg_digest_mreg_t [1:0] creator_sw_cfg_digest; // [1151:1088]
    otp_ctrl_hw2reg_owner_sw_cfg_digest_mreg_t [1:0] owner_sw_cfg_digest; // [1087:1024]
    otp_ctrl_hw2reg_rot_creator_auth_digest_mreg_t [1:0] rot_creator_auth_digest; // [1023:960]
    otp_ctrl_hw2reg_rot_owner_auth_slot0_digest_mreg_t [1:0]
        rot_owner_auth_slot0_digest; // [959:896]
    otp_ctrl_hw2reg_rot_owner_auth_slot1_digest_mreg_t [1:0]
        rot_owner_auth_slot1_digest; // [895:832]
    otp_ctrl_hw2reg_plat_integ_auth_slot0_digest_mreg_t [1:0]
        plat_integ_auth_slot0_digest; // [831:768]
    otp_ctrl_hw2reg_plat_integ_auth_slot1_digest_mreg_t [1:0]
        plat_integ_auth_slot1_digest; // [767:704]
    otp_ctrl_hw2reg_plat_owner_auth_slot0_digest_mreg_t [1:0]
        plat_owner_auth_slot0_digest; // [703:640]
    otp_ctrl_hw2reg_plat_owner_auth_slot1_digest_mreg_t [1:0]
        plat_owner_auth_slot1_digest; // [639:576]
    otp_ctrl_hw2reg_plat_owner_auth_slot2_digest_mreg_t [1:0]
        plat_owner_auth_slot2_digest; // [575:512]
    otp_ctrl_hw2reg_rom_patch_digest_mreg_t [1:0] rom_patch_digest; // [511:448]
    otp_ctrl_hw2reg_soc_fuses_digest_mreg_t [1:0] soc_fuses_digest; // [447:384]
    otp_ctrl_hw2reg_hw_cfg0_digest_mreg_t [1:0] hw_cfg0_digest; // [383:320]
    otp_ctrl_hw2reg_hw_cfg1_digest_mreg_t [1:0] hw_cfg1_digest; // [319:256]
    otp_ctrl_hw2reg_secret0_digest_mreg_t [1:0] secret0_digest; // [255:192]
    otp_ctrl_hw2reg_secret1_digest_mreg_t [1:0] secret1_digest; // [191:128]
    otp_ctrl_hw2reg_secret2_digest_mreg_t [1:0] secret2_digest; // [127:64]
    otp_ctrl_hw2reg_secret3_digest_mreg_t [1:0] secret3_digest; // [63:0]
  } otp_ctrl_core_hw2reg_t;

  // Register offsets for core interface
  parameter logic [CoreAw-1:0] OTP_CTRL_INTR_STATE_OFFSET = 16'h 0;
  parameter logic [CoreAw-1:0] OTP_CTRL_INTR_ENABLE_OFFSET = 16'h 4;
  parameter logic [CoreAw-1:0] OTP_CTRL_INTR_TEST_OFFSET = 16'h 8;
  parameter logic [CoreAw-1:0] OTP_CTRL_ALERT_TEST_OFFSET = 16'h c;
  parameter logic [CoreAw-1:0] OTP_CTRL_STATUS_OFFSET = 16'h 10;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_0_OFFSET = 16'h 14;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_1_OFFSET = 16'h 18;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_2_OFFSET = 16'h 1c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_3_OFFSET = 16'h 20;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_4_OFFSET = 16'h 24;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_5_OFFSET = 16'h 28;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_6_OFFSET = 16'h 2c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_7_OFFSET = 16'h 30;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_8_OFFSET = 16'h 34;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_9_OFFSET = 16'h 38;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_10_OFFSET = 16'h 3c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_11_OFFSET = 16'h 40;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_12_OFFSET = 16'h 44;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_13_OFFSET = 16'h 48;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_14_OFFSET = 16'h 4c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_15_OFFSET = 16'h 50;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_16_OFFSET = 16'h 54;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_17_OFFSET = 16'h 58;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_18_OFFSET = 16'h 5c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_19_OFFSET = 16'h 60;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_20_OFFSET = 16'h 64;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_21_OFFSET = 16'h 68;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_22_OFFSET = 16'h 6c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_23_OFFSET = 16'h 70;
  parameter logic [CoreAw-1:0] OTP_CTRL_DIRECT_ACCESS_REGWEN_OFFSET = 16'h 74;
  parameter logic [CoreAw-1:0] OTP_CTRL_DIRECT_ACCESS_CMD_OFFSET = 16'h 78;
  parameter logic [CoreAw-1:0] OTP_CTRL_DIRECT_ACCESS_ADDRESS_OFFSET = 16'h 7c;
  parameter logic [CoreAw-1:0] OTP_CTRL_DIRECT_ACCESS_WDATA_0_OFFSET = 16'h 80;
  parameter logic [CoreAw-1:0] OTP_CTRL_DIRECT_ACCESS_WDATA_1_OFFSET = 16'h 84;
  parameter logic [CoreAw-1:0] OTP_CTRL_DIRECT_ACCESS_RDATA_0_OFFSET = 16'h 88;
  parameter logic [CoreAw-1:0] OTP_CTRL_DIRECT_ACCESS_RDATA_1_OFFSET = 16'h 8c;
  parameter logic [CoreAw-1:0] OTP_CTRL_CHECK_TRIGGER_REGWEN_OFFSET = 16'h 90;
  parameter logic [CoreAw-1:0] OTP_CTRL_CHECK_TRIGGER_OFFSET = 16'h 94;
  parameter logic [CoreAw-1:0] OTP_CTRL_CHECK_REGWEN_OFFSET = 16'h 98;
  parameter logic [CoreAw-1:0] OTP_CTRL_CHECK_TIMEOUT_OFFSET = 16'h 9c;
  parameter logic [CoreAw-1:0] OTP_CTRL_INTEGRITY_CHECK_PERIOD_OFFSET = 16'h a0;
  parameter logic [CoreAw-1:0] OTP_CTRL_CONSISTENCY_CHECK_PERIOD_OFFSET = 16'h a4;
  parameter logic [CoreAw-1:0] OTP_CTRL_VENDOR_TEST_READ_LOCK_OFFSET = 16'h a8;
  parameter logic [CoreAw-1:0] OTP_CTRL_CREATOR_SW_CFG_READ_LOCK_OFFSET = 16'h ac;
  parameter logic [CoreAw-1:0] OTP_CTRL_OWNER_SW_CFG_READ_LOCK_OFFSET = 16'h b0;
  parameter logic [CoreAw-1:0] OTP_CTRL_OWNERSHIP_SLOT_STATE_READ_LOCK_OFFSET = 16'h b4;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_CREATOR_AUTH_READ_LOCK_OFFSET = 16'h b8;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_READ_LOCK_OFFSET = 16'h bc;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_READ_LOCK_OFFSET = 16'h c0;
  parameter logic [CoreAw-1:0] OTP_CTRL_PLAT_INTEG_AUTH_SLOT0_READ_LOCK_OFFSET = 16'h c4;
  parameter logic [CoreAw-1:0] OTP_CTRL_PLAT_INTEG_AUTH_SLOT1_READ_LOCK_OFFSET = 16'h c8;
  parameter logic [CoreAw-1:0] OTP_CTRL_PLAT_OWNER_AUTH_SLOT0_READ_LOCK_OFFSET = 16'h cc;
  parameter logic [CoreAw-1:0] OTP_CTRL_PLAT_OWNER_AUTH_SLOT1_READ_LOCK_OFFSET = 16'h d0;
  parameter logic [CoreAw-1:0] OTP_CTRL_PLAT_OWNER_AUTH_SLOT2_READ_LOCK_OFFSET = 16'h d4;
  parameter logic [CoreAw-1:0] OTP_CTRL_EXT_NVM_READ_LOCK_OFFSET = 16'h d8;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROM_PATCH_READ_LOCK_OFFSET = 16'h dc;
  parameter logic [CoreAw-1:0] OTP_CTRL_SOC_FUSES_READ_LOCK_OFFSET = 16'h e0;
  parameter logic [CoreAw-1:0] OTP_CTRL_VENDOR_TEST_DIGEST_0_OFFSET = 16'h e4;
  parameter logic [CoreAw-1:0] OTP_CTRL_VENDOR_TEST_DIGEST_1_OFFSET = 16'h e8;
  parameter logic [CoreAw-1:0] OTP_CTRL_CREATOR_SW_CFG_DIGEST_0_OFFSET = 16'h ec;
  parameter logic [CoreAw-1:0] OTP_CTRL_CREATOR_SW_CFG_DIGEST_1_OFFSET = 16'h f0;
  parameter logic [CoreAw-1:0] OTP_CTRL_OWNER_SW_CFG_DIGEST_0_OFFSET = 16'h f4;
  parameter logic [CoreAw-1:0] OTP_CTRL_OWNER_SW_CFG_DIGEST_1_OFFSET = 16'h f8;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_CREATOR_AUTH_DIGEST_0_OFFSET = 16'h fc;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_CREATOR_AUTH_DIGEST_1_OFFSET = 16'h 100;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_0_OFFSET = 16'h 104;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_1_OFFSET = 16'h 108;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_0_OFFSET = 16'h 10c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_1_OFFSET = 16'h 110;
  parameter logic [CoreAw-1:0] OTP_CTRL_PLAT_INTEG_AUTH_SLOT0_DIGEST_0_OFFSET = 16'h 114;
  parameter logic [CoreAw-1:0] OTP_CTRL_PLAT_INTEG_AUTH_SLOT0_DIGEST_1_OFFSET = 16'h 118;
  parameter logic [CoreAw-1:0] OTP_CTRL_PLAT_INTEG_AUTH_SLOT1_DIGEST_0_OFFSET = 16'h 11c;
  parameter logic [CoreAw-1:0] OTP_CTRL_PLAT_INTEG_AUTH_SLOT1_DIGEST_1_OFFSET = 16'h 120;
  parameter logic [CoreAw-1:0] OTP_CTRL_PLAT_OWNER_AUTH_SLOT0_DIGEST_0_OFFSET = 16'h 124;
  parameter logic [CoreAw-1:0] OTP_CTRL_PLAT_OWNER_AUTH_SLOT0_DIGEST_1_OFFSET = 16'h 128;
  parameter logic [CoreAw-1:0] OTP_CTRL_PLAT_OWNER_AUTH_SLOT1_DIGEST_0_OFFSET = 16'h 12c;
  parameter logic [CoreAw-1:0] OTP_CTRL_PLAT_OWNER_AUTH_SLOT1_DIGEST_1_OFFSET = 16'h 130;
  parameter logic [CoreAw-1:0] OTP_CTRL_PLAT_OWNER_AUTH_SLOT2_DIGEST_0_OFFSET = 16'h 134;
  parameter logic [CoreAw-1:0] OTP_CTRL_PLAT_OWNER_AUTH_SLOT2_DIGEST_1_OFFSET = 16'h 138;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROM_PATCH_DIGEST_0_OFFSET = 16'h 13c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROM_PATCH_DIGEST_1_OFFSET = 16'h 140;
  parameter logic [CoreAw-1:0] OTP_CTRL_SOC_FUSES_DIGEST_0_OFFSET = 16'h 144;
  parameter logic [CoreAw-1:0] OTP_CTRL_SOC_FUSES_DIGEST_1_OFFSET = 16'h 148;
  parameter logic [CoreAw-1:0] OTP_CTRL_HW_CFG0_DIGEST_0_OFFSET = 16'h 14c;
  parameter logic [CoreAw-1:0] OTP_CTRL_HW_CFG0_DIGEST_1_OFFSET = 16'h 150;
  parameter logic [CoreAw-1:0] OTP_CTRL_HW_CFG1_DIGEST_0_OFFSET = 16'h 154;
  parameter logic [CoreAw-1:0] OTP_CTRL_HW_CFG1_DIGEST_1_OFFSET = 16'h 158;
  parameter logic [CoreAw-1:0] OTP_CTRL_SECRET0_DIGEST_0_OFFSET = 16'h 15c;
  parameter logic [CoreAw-1:0] OTP_CTRL_SECRET0_DIGEST_1_OFFSET = 16'h 160;
  parameter logic [CoreAw-1:0] OTP_CTRL_SECRET1_DIGEST_0_OFFSET = 16'h 164;
  parameter logic [CoreAw-1:0] OTP_CTRL_SECRET1_DIGEST_1_OFFSET = 16'h 168;
  parameter logic [CoreAw-1:0] OTP_CTRL_SECRET2_DIGEST_0_OFFSET = 16'h 16c;
  parameter logic [CoreAw-1:0] OTP_CTRL_SECRET2_DIGEST_1_OFFSET = 16'h 170;
  parameter logic [CoreAw-1:0] OTP_CTRL_SECRET3_DIGEST_0_OFFSET = 16'h 174;
  parameter logic [CoreAw-1:0] OTP_CTRL_SECRET3_DIGEST_1_OFFSET = 16'h 178;

  // Reset values for hwext registers and their fields for core interface
  parameter logic [1:0] OTP_CTRL_INTR_TEST_RESVAL = 2'h 0;
  parameter logic [0:0] OTP_CTRL_INTR_TEST_OTP_OPERATION_DONE_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_INTR_TEST_OTP_ERROR_RESVAL = 1'h 0;
  parameter logic [4:0] OTP_CTRL_ALERT_TEST_RESVAL = 5'h 0;
  parameter logic [0:0] OTP_CTRL_ALERT_TEST_FATAL_MACRO_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_ALERT_TEST_FATAL_CHECK_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_ALERT_TEST_FATAL_BUS_INTEG_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_ALERT_TEST_FATAL_PRIM_OTP_ALERT_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_ALERT_TEST_RECOV_PRIM_OTP_ALERT_RESVAL = 1'h 0;
  parameter logic [30:0] OTP_CTRL_STATUS_RESVAL = 31'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_VENDOR_TEST_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_CREATOR_SW_CFG_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_OWNER_SW_CFG_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_OWNERSHIP_SLOT_STATE_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_ROT_CREATOR_AUTH_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_ROT_OWNER_AUTH_SLOT0_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_ROT_OWNER_AUTH_SLOT1_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_PLAT_INTEG_AUTH_SLOT0_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_PLAT_INTEG_AUTH_SLOT1_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_PLAT_OWNER_AUTH_SLOT0_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_PLAT_OWNER_AUTH_SLOT1_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_PLAT_OWNER_AUTH_SLOT2_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_EXT_NVM_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_ROM_PATCH_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_SOC_FUSES_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_HW_CFG0_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_HW_CFG1_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_SECRET0_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_SECRET1_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_SECRET2_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_SECRET3_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_LIFE_CYCLE_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_DAI_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_LCI_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_TIMEOUT_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_LFSR_FSM_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_SCRAMBLING_FSM_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_KEY_DERIV_FSM_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_BUS_INTEG_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_DAI_IDLE_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_CHECK_PENDING_RESVAL = 1'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_0_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_0_ERR_CODE_0_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_1_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_1_ERR_CODE_1_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_2_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_2_ERR_CODE_2_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_3_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_3_ERR_CODE_3_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_4_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_4_ERR_CODE_4_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_5_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_5_ERR_CODE_5_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_6_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_6_ERR_CODE_6_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_7_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_7_ERR_CODE_7_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_8_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_8_ERR_CODE_8_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_9_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_9_ERR_CODE_9_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_10_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_10_ERR_CODE_10_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_11_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_11_ERR_CODE_11_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_12_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_12_ERR_CODE_12_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_13_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_13_ERR_CODE_13_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_14_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_14_ERR_CODE_14_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_15_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_15_ERR_CODE_15_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_16_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_16_ERR_CODE_16_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_17_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_17_ERR_CODE_17_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_18_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_18_ERR_CODE_18_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_19_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_19_ERR_CODE_19_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_20_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_20_ERR_CODE_20_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_21_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_21_ERR_CODE_21_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_22_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_22_ERR_CODE_22_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_23_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_23_ERR_CODE_23_RESVAL = 3'h 0;
  parameter logic [0:0] OTP_CTRL_DIRECT_ACCESS_REGWEN_RESVAL = 1'h 1;
  parameter logic [0:0] OTP_CTRL_DIRECT_ACCESS_REGWEN_DIRECT_ACCESS_REGWEN_RESVAL = 1'h 1;
  parameter logic [2:0] OTP_CTRL_DIRECT_ACCESS_CMD_RESVAL = 3'h 0;
  parameter logic [0:0] OTP_CTRL_DIRECT_ACCESS_CMD_RD_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_DIRECT_ACCESS_CMD_WR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_DIRECT_ACCESS_CMD_DIGEST_RESVAL = 1'h 0;
  parameter logic [31:0] OTP_CTRL_DIRECT_ACCESS_RDATA_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_DIRECT_ACCESS_RDATA_0_DIRECT_ACCESS_RDATA_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_DIRECT_ACCESS_RDATA_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_DIRECT_ACCESS_RDATA_1_DIRECT_ACCESS_RDATA_1_RESVAL = 32'h 0;
  parameter logic [1:0] OTP_CTRL_CHECK_TRIGGER_RESVAL = 2'h 0;
  parameter logic [0:0] OTP_CTRL_CHECK_TRIGGER_INTEGRITY_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_CHECK_TRIGGER_CONSISTENCY_RESVAL = 1'h 0;
  parameter logic [31:0] OTP_CTRL_VENDOR_TEST_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_VENDOR_TEST_DIGEST_0_VENDOR_TEST_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_VENDOR_TEST_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_VENDOR_TEST_DIGEST_1_VENDOR_TEST_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_CREATOR_SW_CFG_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_CREATOR_SW_CFG_DIGEST_0_CREATOR_SW_CFG_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_CREATOR_SW_CFG_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_CREATOR_SW_CFG_DIGEST_1_CREATOR_SW_CFG_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_OWNER_SW_CFG_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_OWNER_SW_CFG_DIGEST_0_OWNER_SW_CFG_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_OWNER_SW_CFG_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_OWNER_SW_CFG_DIGEST_1_OWNER_SW_CFG_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_CREATOR_AUTH_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_CREATOR_AUTH_DIGEST_0_ROT_CREATOR_AUTH_DIGEST_0_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_CREATOR_AUTH_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_CREATOR_AUTH_DIGEST_1_ROT_CREATOR_AUTH_DIGEST_1_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_0_ROT_OWNER_AUTH_SLOT0_DIGEST_0_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_1_ROT_OWNER_AUTH_SLOT0_DIGEST_1_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_0_ROT_OWNER_AUTH_SLOT1_DIGEST_0_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_1_ROT_OWNER_AUTH_SLOT1_DIGEST_1_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_PLAT_INTEG_AUTH_SLOT0_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_PLAT_INTEG_AUTH_SLOT0_DIGEST_0_PLAT_INTEG_AUTH_SLOT0_DIGEST_0_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_PLAT_INTEG_AUTH_SLOT0_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_PLAT_INTEG_AUTH_SLOT0_DIGEST_1_PLAT_INTEG_AUTH_SLOT0_DIGEST_1_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_PLAT_INTEG_AUTH_SLOT1_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_PLAT_INTEG_AUTH_SLOT1_DIGEST_0_PLAT_INTEG_AUTH_SLOT1_DIGEST_0_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_PLAT_INTEG_AUTH_SLOT1_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_PLAT_INTEG_AUTH_SLOT1_DIGEST_1_PLAT_INTEG_AUTH_SLOT1_DIGEST_1_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_PLAT_OWNER_AUTH_SLOT0_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_PLAT_OWNER_AUTH_SLOT0_DIGEST_0_PLAT_OWNER_AUTH_SLOT0_DIGEST_0_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_PLAT_OWNER_AUTH_SLOT0_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_PLAT_OWNER_AUTH_SLOT0_DIGEST_1_PLAT_OWNER_AUTH_SLOT0_DIGEST_1_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_PLAT_OWNER_AUTH_SLOT1_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_PLAT_OWNER_AUTH_SLOT1_DIGEST_0_PLAT_OWNER_AUTH_SLOT1_DIGEST_0_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_PLAT_OWNER_AUTH_SLOT1_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_PLAT_OWNER_AUTH_SLOT1_DIGEST_1_PLAT_OWNER_AUTH_SLOT1_DIGEST_1_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_PLAT_OWNER_AUTH_SLOT2_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_PLAT_OWNER_AUTH_SLOT2_DIGEST_0_PLAT_OWNER_AUTH_SLOT2_DIGEST_0_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_PLAT_OWNER_AUTH_SLOT2_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_PLAT_OWNER_AUTH_SLOT2_DIGEST_1_PLAT_OWNER_AUTH_SLOT2_DIGEST_1_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROM_PATCH_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_ROM_PATCH_DIGEST_0_ROM_PATCH_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_ROM_PATCH_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_ROM_PATCH_DIGEST_1_ROM_PATCH_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SOC_FUSES_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SOC_FUSES_DIGEST_0_SOC_FUSES_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SOC_FUSES_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SOC_FUSES_DIGEST_1_SOC_FUSES_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG0_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG0_DIGEST_0_HW_CFG0_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG0_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG0_DIGEST_1_HW_CFG0_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG1_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG1_DIGEST_0_HW_CFG1_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG1_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG1_DIGEST_1_HW_CFG1_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET0_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET0_DIGEST_0_SECRET0_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET0_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET0_DIGEST_1_SECRET0_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET1_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET1_DIGEST_0_SECRET1_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET1_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET1_DIGEST_1_SECRET1_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET2_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET2_DIGEST_0_SECRET2_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET2_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET2_DIGEST_1_SECRET2_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET3_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET3_DIGEST_0_SECRET3_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET3_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET3_DIGEST_1_SECRET3_DIGEST_1_RESVAL = 32'h 0;

  // Window parameters for core interface
  parameter logic [CoreAw-1:0] OTP_CTRL_SW_CFG_WINDOW_OFFSET = 16'h 8000;
  parameter int unsigned       OTP_CTRL_SW_CFG_WINDOW_SIZE   = 'h 8000;
  parameter int unsigned       OTP_CTRL_SW_CFG_WINDOW_IDX    = 0;

  // Register index for core interface
  typedef enum int {
    OTP_CTRL_INTR_STATE,
    OTP_CTRL_INTR_ENABLE,
    OTP_CTRL_INTR_TEST,
    OTP_CTRL_ALERT_TEST,
    OTP_CTRL_STATUS,
    OTP_CTRL_ERR_CODE_0,
    OTP_CTRL_ERR_CODE_1,
    OTP_CTRL_ERR_CODE_2,
    OTP_CTRL_ERR_CODE_3,
    OTP_CTRL_ERR_CODE_4,
    OTP_CTRL_ERR_CODE_5,
    OTP_CTRL_ERR_CODE_6,
    OTP_CTRL_ERR_CODE_7,
    OTP_CTRL_ERR_CODE_8,
    OTP_CTRL_ERR_CODE_9,
    OTP_CTRL_ERR_CODE_10,
    OTP_CTRL_ERR_CODE_11,
    OTP_CTRL_ERR_CODE_12,
    OTP_CTRL_ERR_CODE_13,
    OTP_CTRL_ERR_CODE_14,
    OTP_CTRL_ERR_CODE_15,
    OTP_CTRL_ERR_CODE_16,
    OTP_CTRL_ERR_CODE_17,
    OTP_CTRL_ERR_CODE_18,
    OTP_CTRL_ERR_CODE_19,
    OTP_CTRL_ERR_CODE_20,
    OTP_CTRL_ERR_CODE_21,
    OTP_CTRL_ERR_CODE_22,
    OTP_CTRL_ERR_CODE_23,
    OTP_CTRL_DIRECT_ACCESS_REGWEN,
    OTP_CTRL_DIRECT_ACCESS_CMD,
    OTP_CTRL_DIRECT_ACCESS_ADDRESS,
    OTP_CTRL_DIRECT_ACCESS_WDATA_0,
    OTP_CTRL_DIRECT_ACCESS_WDATA_1,
    OTP_CTRL_DIRECT_ACCESS_RDATA_0,
    OTP_CTRL_DIRECT_ACCESS_RDATA_1,
    OTP_CTRL_CHECK_TRIGGER_REGWEN,
    OTP_CTRL_CHECK_TRIGGER,
    OTP_CTRL_CHECK_REGWEN,
    OTP_CTRL_CHECK_TIMEOUT,
    OTP_CTRL_INTEGRITY_CHECK_PERIOD,
    OTP_CTRL_CONSISTENCY_CHECK_PERIOD,
    OTP_CTRL_VENDOR_TEST_READ_LOCK,
    OTP_CTRL_CREATOR_SW_CFG_READ_LOCK,
    OTP_CTRL_OWNER_SW_CFG_READ_LOCK,
    OTP_CTRL_OWNERSHIP_SLOT_STATE_READ_LOCK,
    OTP_CTRL_ROT_CREATOR_AUTH_READ_LOCK,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT0_READ_LOCK,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT1_READ_LOCK,
    OTP_CTRL_PLAT_INTEG_AUTH_SLOT0_READ_LOCK,
    OTP_CTRL_PLAT_INTEG_AUTH_SLOT1_READ_LOCK,
    OTP_CTRL_PLAT_OWNER_AUTH_SLOT0_READ_LOCK,
    OTP_CTRL_PLAT_OWNER_AUTH_SLOT1_READ_LOCK,
    OTP_CTRL_PLAT_OWNER_AUTH_SLOT2_READ_LOCK,
    OTP_CTRL_EXT_NVM_READ_LOCK,
    OTP_CTRL_ROM_PATCH_READ_LOCK,
    OTP_CTRL_SOC_FUSES_READ_LOCK,
    OTP_CTRL_VENDOR_TEST_DIGEST_0,
    OTP_CTRL_VENDOR_TEST_DIGEST_1,
    OTP_CTRL_CREATOR_SW_CFG_DIGEST_0,
    OTP_CTRL_CREATOR_SW_CFG_DIGEST_1,
    OTP_CTRL_OWNER_SW_CFG_DIGEST_0,
    OTP_CTRL_OWNER_SW_CFG_DIGEST_1,
    OTP_CTRL_ROT_CREATOR_AUTH_DIGEST_0,
    OTP_CTRL_ROT_CREATOR_AUTH_DIGEST_1,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_0,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_1,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_0,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_1,
    OTP_CTRL_PLAT_INTEG_AUTH_SLOT0_DIGEST_0,
    OTP_CTRL_PLAT_INTEG_AUTH_SLOT0_DIGEST_1,
    OTP_CTRL_PLAT_INTEG_AUTH_SLOT1_DIGEST_0,
    OTP_CTRL_PLAT_INTEG_AUTH_SLOT1_DIGEST_1,
    OTP_CTRL_PLAT_OWNER_AUTH_SLOT0_DIGEST_0,
    OTP_CTRL_PLAT_OWNER_AUTH_SLOT0_DIGEST_1,
    OTP_CTRL_PLAT_OWNER_AUTH_SLOT1_DIGEST_0,
    OTP_CTRL_PLAT_OWNER_AUTH_SLOT1_DIGEST_1,
    OTP_CTRL_PLAT_OWNER_AUTH_SLOT2_DIGEST_0,
    OTP_CTRL_PLAT_OWNER_AUTH_SLOT2_DIGEST_1,
    OTP_CTRL_ROM_PATCH_DIGEST_0,
    OTP_CTRL_ROM_PATCH_DIGEST_1,
    OTP_CTRL_SOC_FUSES_DIGEST_0,
    OTP_CTRL_SOC_FUSES_DIGEST_1,
    OTP_CTRL_HW_CFG0_DIGEST_0,
    OTP_CTRL_HW_CFG0_DIGEST_1,
    OTP_CTRL_HW_CFG1_DIGEST_0,
    OTP_CTRL_HW_CFG1_DIGEST_1,
    OTP_CTRL_SECRET0_DIGEST_0,
    OTP_CTRL_SECRET0_DIGEST_1,
    OTP_CTRL_SECRET1_DIGEST_0,
    OTP_CTRL_SECRET1_DIGEST_1,
    OTP_CTRL_SECRET2_DIGEST_0,
    OTP_CTRL_SECRET2_DIGEST_1,
    OTP_CTRL_SECRET3_DIGEST_0,
    OTP_CTRL_SECRET3_DIGEST_1
  } otp_ctrl_core_id_e;

  // Register width information to check illegal writes for core interface
  parameter logic [3:0] OTP_CTRL_CORE_PERMIT [95] = '{
    4'b 0001, // index[ 0] OTP_CTRL_INTR_STATE
    4'b 0001, // index[ 1] OTP_CTRL_INTR_ENABLE
    4'b 0001, // index[ 2] OTP_CTRL_INTR_TEST
    4'b 0001, // index[ 3] OTP_CTRL_ALERT_TEST
    4'b 1111, // index[ 4] OTP_CTRL_STATUS
    4'b 0001, // index[ 5] OTP_CTRL_ERR_CODE_0
    4'b 0001, // index[ 6] OTP_CTRL_ERR_CODE_1
    4'b 0001, // index[ 7] OTP_CTRL_ERR_CODE_2
    4'b 0001, // index[ 8] OTP_CTRL_ERR_CODE_3
    4'b 0001, // index[ 9] OTP_CTRL_ERR_CODE_4
    4'b 0001, // index[10] OTP_CTRL_ERR_CODE_5
    4'b 0001, // index[11] OTP_CTRL_ERR_CODE_6
    4'b 0001, // index[12] OTP_CTRL_ERR_CODE_7
    4'b 0001, // index[13] OTP_CTRL_ERR_CODE_8
    4'b 0001, // index[14] OTP_CTRL_ERR_CODE_9
    4'b 0001, // index[15] OTP_CTRL_ERR_CODE_10
    4'b 0001, // index[16] OTP_CTRL_ERR_CODE_11
    4'b 0001, // index[17] OTP_CTRL_ERR_CODE_12
    4'b 0001, // index[18] OTP_CTRL_ERR_CODE_13
    4'b 0001, // index[19] OTP_CTRL_ERR_CODE_14
    4'b 0001, // index[20] OTP_CTRL_ERR_CODE_15
    4'b 0001, // index[21] OTP_CTRL_ERR_CODE_16
    4'b 0001, // index[22] OTP_CTRL_ERR_CODE_17
    4'b 0001, // index[23] OTP_CTRL_ERR_CODE_18
    4'b 0001, // index[24] OTP_CTRL_ERR_CODE_19
    4'b 0001, // index[25] OTP_CTRL_ERR_CODE_20
    4'b 0001, // index[26] OTP_CTRL_ERR_CODE_21
    4'b 0001, // index[27] OTP_CTRL_ERR_CODE_22
    4'b 0001, // index[28] OTP_CTRL_ERR_CODE_23
    4'b 0001, // index[29] OTP_CTRL_DIRECT_ACCESS_REGWEN
    4'b 0001, // index[30] OTP_CTRL_DIRECT_ACCESS_CMD
    4'b 0011, // index[31] OTP_CTRL_DIRECT_ACCESS_ADDRESS
    4'b 1111, // index[32] OTP_CTRL_DIRECT_ACCESS_WDATA_0
    4'b 1111, // index[33] OTP_CTRL_DIRECT_ACCESS_WDATA_1
    4'b 1111, // index[34] OTP_CTRL_DIRECT_ACCESS_RDATA_0
    4'b 1111, // index[35] OTP_CTRL_DIRECT_ACCESS_RDATA_1
    4'b 0001, // index[36] OTP_CTRL_CHECK_TRIGGER_REGWEN
    4'b 0001, // index[37] OTP_CTRL_CHECK_TRIGGER
    4'b 0001, // index[38] OTP_CTRL_CHECK_REGWEN
    4'b 1111, // index[39] OTP_CTRL_CHECK_TIMEOUT
    4'b 1111, // index[40] OTP_CTRL_INTEGRITY_CHECK_PERIOD
    4'b 1111, // index[41] OTP_CTRL_CONSISTENCY_CHECK_PERIOD
    4'b 0001, // index[42] OTP_CTRL_VENDOR_TEST_READ_LOCK
    4'b 0001, // index[43] OTP_CTRL_CREATOR_SW_CFG_READ_LOCK
    4'b 0001, // index[44] OTP_CTRL_OWNER_SW_CFG_READ_LOCK
    4'b 0001, // index[45] OTP_CTRL_OWNERSHIP_SLOT_STATE_READ_LOCK
    4'b 0001, // index[46] OTP_CTRL_ROT_CREATOR_AUTH_READ_LOCK
    4'b 0001, // index[47] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_READ_LOCK
    4'b 0001, // index[48] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_READ_LOCK
    4'b 0001, // index[49] OTP_CTRL_PLAT_INTEG_AUTH_SLOT0_READ_LOCK
    4'b 0001, // index[50] OTP_CTRL_PLAT_INTEG_AUTH_SLOT1_READ_LOCK
    4'b 0001, // index[51] OTP_CTRL_PLAT_OWNER_AUTH_SLOT0_READ_LOCK
    4'b 0001, // index[52] OTP_CTRL_PLAT_OWNER_AUTH_SLOT1_READ_LOCK
    4'b 0001, // index[53] OTP_CTRL_PLAT_OWNER_AUTH_SLOT2_READ_LOCK
    4'b 0001, // index[54] OTP_CTRL_EXT_NVM_READ_LOCK
    4'b 0001, // index[55] OTP_CTRL_ROM_PATCH_READ_LOCK
    4'b 0001, // index[56] OTP_CTRL_SOC_FUSES_READ_LOCK
    4'b 1111, // index[57] OTP_CTRL_VENDOR_TEST_DIGEST_0
    4'b 1111, // index[58] OTP_CTRL_VENDOR_TEST_DIGEST_1
    4'b 1111, // index[59] OTP_CTRL_CREATOR_SW_CFG_DIGEST_0
    4'b 1111, // index[60] OTP_CTRL_CREATOR_SW_CFG_DIGEST_1
    4'b 1111, // index[61] OTP_CTRL_OWNER_SW_CFG_DIGEST_0
    4'b 1111, // index[62] OTP_CTRL_OWNER_SW_CFG_DIGEST_1
    4'b 1111, // index[63] OTP_CTRL_ROT_CREATOR_AUTH_DIGEST_0
    4'b 1111, // index[64] OTP_CTRL_ROT_CREATOR_AUTH_DIGEST_1
    4'b 1111, // index[65] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_0
    4'b 1111, // index[66] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_1
    4'b 1111, // index[67] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_0
    4'b 1111, // index[68] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_1
    4'b 1111, // index[69] OTP_CTRL_PLAT_INTEG_AUTH_SLOT0_DIGEST_0
    4'b 1111, // index[70] OTP_CTRL_PLAT_INTEG_AUTH_SLOT0_DIGEST_1
    4'b 1111, // index[71] OTP_CTRL_PLAT_INTEG_AUTH_SLOT1_DIGEST_0
    4'b 1111, // index[72] OTP_CTRL_PLAT_INTEG_AUTH_SLOT1_DIGEST_1
    4'b 1111, // index[73] OTP_CTRL_PLAT_OWNER_AUTH_SLOT0_DIGEST_0
    4'b 1111, // index[74] OTP_CTRL_PLAT_OWNER_AUTH_SLOT0_DIGEST_1
    4'b 1111, // index[75] OTP_CTRL_PLAT_OWNER_AUTH_SLOT1_DIGEST_0
    4'b 1111, // index[76] OTP_CTRL_PLAT_OWNER_AUTH_SLOT1_DIGEST_1
    4'b 1111, // index[77] OTP_CTRL_PLAT_OWNER_AUTH_SLOT2_DIGEST_0
    4'b 1111, // index[78] OTP_CTRL_PLAT_OWNER_AUTH_SLOT2_DIGEST_1
    4'b 1111, // index[79] OTP_CTRL_ROM_PATCH_DIGEST_0
    4'b 1111, // index[80] OTP_CTRL_ROM_PATCH_DIGEST_1
    4'b 1111, // index[81] OTP_CTRL_SOC_FUSES_DIGEST_0
    4'b 1111, // index[82] OTP_CTRL_SOC_FUSES_DIGEST_1
    4'b 1111, // index[83] OTP_CTRL_HW_CFG0_DIGEST_0
    4'b 1111, // index[84] OTP_CTRL_HW_CFG0_DIGEST_1
    4'b 1111, // index[85] OTP_CTRL_HW_CFG1_DIGEST_0
    4'b 1111, // index[86] OTP_CTRL_HW_CFG1_DIGEST_1
    4'b 1111, // index[87] OTP_CTRL_SECRET0_DIGEST_0
    4'b 1111, // index[88] OTP_CTRL_SECRET0_DIGEST_1
    4'b 1111, // index[89] OTP_CTRL_SECRET1_DIGEST_0
    4'b 1111, // index[90] OTP_CTRL_SECRET1_DIGEST_1
    4'b 1111, // index[91] OTP_CTRL_SECRET2_DIGEST_0
    4'b 1111, // index[92] OTP_CTRL_SECRET2_DIGEST_1
    4'b 1111, // index[93] OTP_CTRL_SECRET3_DIGEST_0
    4'b 1111  // index[94] OTP_CTRL_SECRET3_DIGEST_1
  };

  ///////////////////////////////////////////////
  // Typedefs for registers for prim interface //
  ///////////////////////////////////////////////

  typedef struct packed {
    struct packed {
      logic [10:0] q;
    } field4;
    struct packed {
      logic [5:0]  q;
    } field3;
    struct packed {
      logic        q;
    } redundancy_autoinit_disable;
    struct packed {
      logic        q;
    } ecc_disable;
    struct packed {
      logic        q;
    } read_margin;
    struct packed {
      logic [1:0]  q;
    } test_row_col_sel;
    struct packed {
      logic        q;
    } ecc_sel;
    struct packed {
      logic [1:0]  q;
    } macro_mode;
  } otp_ctrl_reg2hw_macro_control_reg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  q;
    } ecc_info_3;
    struct packed {
      logic [7:0]  q;
    } ecc_info_2;
    struct packed {
      logic [7:0]  q;
    } ecc_info_1;
    struct packed {
      logic [7:0]  q;
    } ecc_info_0;
  } otp_ctrl_reg2hw_read_ecc_info_reg_t;

  typedef struct packed {
    struct packed {
      logic [8:0]  q;
    } tsur_ps_cs_cycles;
    struct packed {
      logic [9:0] q;
    } tsur_ps_cycles;
    struct packed {
      logic [11:0] q;
    } tsur_pd_ps_cycles;
  } otp_ctrl_reg2hw_fuse_wrapper_rd_cfg_0_reg_t;

  typedef struct packed {
    struct packed {
      logic [9:0] q;
    } tsq_cycles;
    struct packed {
      logic [9:0] q;
    } tsup_ps_cycles;
    struct packed {
      logic [8:0]  q;
    } tsup_ps_cs_cycles;
  } otp_ctrl_reg2hw_fuse_wrapper_rd_cfg_1_reg_t;

  typedef struct packed {
    struct packed {
      logic [6:0]  q;
    } tsur_ld_cycles;
    struct packed {
      logic [13:0] q;
    } tpgm_cycles;
    struct packed {
      logic [10:0] q;
    } tsq_m_cycles;
  } otp_ctrl_reg2hw_fuse_wrapper_rd_cfg_2_reg_t;

  typedef struct packed {
    struct packed {
      logic [8:0]  q;
    } thp_cs_cycles;
    struct packed {
      logic [9:0] q;
    } thp_ps_cycles;
    struct packed {
      logic [9:0] q;
    } thr_ps_cycles;
  } otp_ctrl_reg2hw_fuse_wrapper_rd_cfg_3_reg_t;

  typedef struct packed {
    struct packed {
      logic [8:0]  q;
    } thr_ps_cs_cycles;
    struct packed {
      logic [8:0]  q;
    } thp_ps_cs_cycles;
    struct packed {
      logic [8:0]  q;
    } thr_cs_cycles;
  } otp_ctrl_reg2hw_fuse_wrapper_rd_cfg_4_reg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  q;
    } tsup_ld_cycles;
    struct packed {
      logic [7:0]  q;
    } thp_a_cycles;
    struct packed {
      logic [7:0]  q;
    } tsup_a_cycles;
    struct packed {
      logic [7:0]  q;
    } tsur_a_cycles;
  } otp_ctrl_reg2hw_fuse_wrapper_rd_cfg_5_reg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  q;
    } thr_a_cycles;
    struct packed {
      logic [10:0] q;
    } trd_m_cycles;
    struct packed {
      logic [9:0] q;
    } trd_cycles;
  } otp_ctrl_reg2hw_fuse_wrapper_rd_cfg_6_reg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  q;
    } addr_capture_cycles;
    struct packed {
      logic [7:0]  q;
    } data_capture_cycles;
    struct packed {
      logic [7:0]  q;
    } thp_pd_ps_cycles;
  } otp_ctrl_reg2hw_fuse_wrapper_rd_cfg_7_reg_t;

  typedef struct packed {
    logic [17:0] q;
  } otp_ctrl_reg2hw_fuse_wrapper_rd_cfg_8_reg_t;

  typedef struct packed {
    struct packed {
      logic [8:0]  q;
    } tsur_ps_cs_cycles;
    struct packed {
      logic [9:0] q;
    } tsur_ps_cycles;
    struct packed {
      logic [11:0] q;
    } tsur_pd_ps_cycles;
  } otp_ctrl_reg2hw_fuse_wrapper_wr_cfg_0_reg_t;

  typedef struct packed {
    struct packed {
      logic [9:0] q;
    } tsq_cycles;
    struct packed {
      logic [9:0] q;
    } tsup_ps_cycles;
    struct packed {
      logic [8:0]  q;
    } tsup_ps_cs_cycles;
  } otp_ctrl_reg2hw_fuse_wrapper_wr_cfg_1_reg_t;

  typedef struct packed {
    struct packed {
      logic [6:0]  q;
    } tsur_ld_cycles;
    struct packed {
      logic [13:0] q;
    } tpgm_cycles;
    struct packed {
      logic [10:0] q;
    } tsq_m_cycles;
  } otp_ctrl_reg2hw_fuse_wrapper_wr_cfg_2_reg_t;

  typedef struct packed {
    struct packed {
      logic [8:0]  q;
    } thp_cs_cycles;
    struct packed {
      logic [9:0] q;
    } thp_ps_cycles;
    struct packed {
      logic [9:0] q;
    } thr_ps_cycles;
  } otp_ctrl_reg2hw_fuse_wrapper_wr_cfg_3_reg_t;

  typedef struct packed {
    struct packed {
      logic [8:0]  q;
    } thr_ps_cs_cycles;
    struct packed {
      logic [8:0]  q;
    } thp_ps_cs_cycles;
    struct packed {
      logic [8:0]  q;
    } thr_cs_cycles;
  } otp_ctrl_reg2hw_fuse_wrapper_wr_cfg_4_reg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  q;
    } tsup_ld_cycles;
    struct packed {
      logic [7:0]  q;
    } thp_a_cycles;
    struct packed {
      logic [7:0]  q;
    } tsup_a_cycles;
    struct packed {
      logic [7:0]  q;
    } tsur_a_cycles;
  } otp_ctrl_reg2hw_fuse_wrapper_wr_cfg_5_reg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  q;
    } thr_a_cycles;
    struct packed {
      logic [10:0] q;
    } trd_m_cycles;
    struct packed {
      logic [9:0] q;
    } trd_cycles;
  } otp_ctrl_reg2hw_fuse_wrapper_wr_cfg_6_reg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  q;
    } addr_capture_cycles;
    struct packed {
      logic [7:0]  q;
    } data_capture_cycles;
    struct packed {
      logic [7:0]  q;
    } thp_pd_ps_cycles;
  } otp_ctrl_reg2hw_fuse_wrapper_wr_cfg_7_reg_t;

  typedef struct packed {
    logic [17:0] q;
  } otp_ctrl_reg2hw_fuse_wrapper_wr_cfg_8_reg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  d;
      logic        de;
    } ecc_info_0;
    struct packed {
      logic [7:0]  d;
      logic        de;
    } ecc_info_1;
    struct packed {
      logic [7:0]  d;
      logic        de;
    } ecc_info_2;
    struct packed {
      logic [7:0]  d;
      logic        de;
    } ecc_info_3;
  } otp_ctrl_hw2reg_read_ecc_info_reg_t;

  // Register -> HW type for prim interface
  typedef struct packed {
    otp_ctrl_reg2hw_macro_control_reg_t macro_control; // [558:534]
    otp_ctrl_reg2hw_read_ecc_info_reg_t read_ecc_info; // [533:502]
    otp_ctrl_reg2hw_fuse_wrapper_rd_cfg_0_reg_t fuse_wrapper_rd_cfg_0; // [501:471]
    otp_ctrl_reg2hw_fuse_wrapper_rd_cfg_1_reg_t fuse_wrapper_rd_cfg_1; // [470:442]
    otp_ctrl_reg2hw_fuse_wrapper_rd_cfg_2_reg_t fuse_wrapper_rd_cfg_2; // [441:410]
    otp_ctrl_reg2hw_fuse_wrapper_rd_cfg_3_reg_t fuse_wrapper_rd_cfg_3; // [409:381]
    otp_ctrl_reg2hw_fuse_wrapper_rd_cfg_4_reg_t fuse_wrapper_rd_cfg_4; // [380:354]
    otp_ctrl_reg2hw_fuse_wrapper_rd_cfg_5_reg_t fuse_wrapper_rd_cfg_5; // [353:322]
    otp_ctrl_reg2hw_fuse_wrapper_rd_cfg_6_reg_t fuse_wrapper_rd_cfg_6; // [321:293]
    otp_ctrl_reg2hw_fuse_wrapper_rd_cfg_7_reg_t fuse_wrapper_rd_cfg_7; // [292:269]
    otp_ctrl_reg2hw_fuse_wrapper_rd_cfg_8_reg_t fuse_wrapper_rd_cfg_8; // [268:251]
    otp_ctrl_reg2hw_fuse_wrapper_wr_cfg_0_reg_t fuse_wrapper_wr_cfg_0; // [250:220]
    otp_ctrl_reg2hw_fuse_wrapper_wr_cfg_1_reg_t fuse_wrapper_wr_cfg_1; // [219:191]
    otp_ctrl_reg2hw_fuse_wrapper_wr_cfg_2_reg_t fuse_wrapper_wr_cfg_2; // [190:159]
    otp_ctrl_reg2hw_fuse_wrapper_wr_cfg_3_reg_t fuse_wrapper_wr_cfg_3; // [158:130]
    otp_ctrl_reg2hw_fuse_wrapper_wr_cfg_4_reg_t fuse_wrapper_wr_cfg_4; // [129:103]
    otp_ctrl_reg2hw_fuse_wrapper_wr_cfg_5_reg_t fuse_wrapper_wr_cfg_5; // [102:71]
    otp_ctrl_reg2hw_fuse_wrapper_wr_cfg_6_reg_t fuse_wrapper_wr_cfg_6; // [70:42]
    otp_ctrl_reg2hw_fuse_wrapper_wr_cfg_7_reg_t fuse_wrapper_wr_cfg_7; // [41:18]
    otp_ctrl_reg2hw_fuse_wrapper_wr_cfg_8_reg_t fuse_wrapper_wr_cfg_8; // [17:0]
  } otp_ctrl_prim_reg2hw_t;

  // HW -> register type for prim interface
  typedef struct packed {
    otp_ctrl_hw2reg_read_ecc_info_reg_t read_ecc_info; // [35:0]
  } otp_ctrl_prim_hw2reg_t;

  // Register offsets for prim interface
  parameter logic [PrimAw-1:0] OTP_CTRL_MACRO_CONTROL_OFFSET = 7'h 0;
  parameter logic [PrimAw-1:0] OTP_CTRL_READ_ECC_INFO_OFFSET = 7'h 4;
  parameter logic [PrimAw-1:0] OTP_CTRL_FUSE_WRAPPER_RD_CFG_0_OFFSET = 7'h 8;
  parameter logic [PrimAw-1:0] OTP_CTRL_FUSE_WRAPPER_RD_CFG_1_OFFSET = 7'h c;
  parameter logic [PrimAw-1:0] OTP_CTRL_FUSE_WRAPPER_RD_CFG_2_OFFSET = 7'h 10;
  parameter logic [PrimAw-1:0] OTP_CTRL_FUSE_WRAPPER_RD_CFG_3_OFFSET = 7'h 14;
  parameter logic [PrimAw-1:0] OTP_CTRL_FUSE_WRAPPER_RD_CFG_4_OFFSET = 7'h 18;
  parameter logic [PrimAw-1:0] OTP_CTRL_FUSE_WRAPPER_RD_CFG_5_OFFSET = 7'h 1c;
  parameter logic [PrimAw-1:0] OTP_CTRL_FUSE_WRAPPER_RD_CFG_6_OFFSET = 7'h 20;
  parameter logic [PrimAw-1:0] OTP_CTRL_FUSE_WRAPPER_RD_CFG_7_OFFSET = 7'h 24;
  parameter logic [PrimAw-1:0] OTP_CTRL_FUSE_WRAPPER_RD_CFG_8_OFFSET = 7'h 28;
  parameter logic [PrimAw-1:0] OTP_CTRL_FUSE_WRAPPER_WR_CFG_0_OFFSET = 7'h 2c;
  parameter logic [PrimAw-1:0] OTP_CTRL_FUSE_WRAPPER_WR_CFG_1_OFFSET = 7'h 30;
  parameter logic [PrimAw-1:0] OTP_CTRL_FUSE_WRAPPER_WR_CFG_2_OFFSET = 7'h 34;
  parameter logic [PrimAw-1:0] OTP_CTRL_FUSE_WRAPPER_WR_CFG_3_OFFSET = 7'h 38;
  parameter logic [PrimAw-1:0] OTP_CTRL_FUSE_WRAPPER_WR_CFG_4_OFFSET = 7'h 3c;
  parameter logic [PrimAw-1:0] OTP_CTRL_FUSE_WRAPPER_WR_CFG_5_OFFSET = 7'h 40;
  parameter logic [PrimAw-1:0] OTP_CTRL_FUSE_WRAPPER_WR_CFG_6_OFFSET = 7'h 44;
  parameter logic [PrimAw-1:0] OTP_CTRL_FUSE_WRAPPER_WR_CFG_7_OFFSET = 7'h 48;
  parameter logic [PrimAw-1:0] OTP_CTRL_FUSE_WRAPPER_WR_CFG_8_OFFSET = 7'h 4c;

  // Register index for prim interface
  typedef enum int {
    OTP_CTRL_MACRO_CONTROL,
    OTP_CTRL_READ_ECC_INFO,
    OTP_CTRL_FUSE_WRAPPER_RD_CFG_0,
    OTP_CTRL_FUSE_WRAPPER_RD_CFG_1,
    OTP_CTRL_FUSE_WRAPPER_RD_CFG_2,
    OTP_CTRL_FUSE_WRAPPER_RD_CFG_3,
    OTP_CTRL_FUSE_WRAPPER_RD_CFG_4,
    OTP_CTRL_FUSE_WRAPPER_RD_CFG_5,
    OTP_CTRL_FUSE_WRAPPER_RD_CFG_6,
    OTP_CTRL_FUSE_WRAPPER_RD_CFG_7,
    OTP_CTRL_FUSE_WRAPPER_RD_CFG_8,
    OTP_CTRL_FUSE_WRAPPER_WR_CFG_0,
    OTP_CTRL_FUSE_WRAPPER_WR_CFG_1,
    OTP_CTRL_FUSE_WRAPPER_WR_CFG_2,
    OTP_CTRL_FUSE_WRAPPER_WR_CFG_3,
    OTP_CTRL_FUSE_WRAPPER_WR_CFG_4,
    OTP_CTRL_FUSE_WRAPPER_WR_CFG_5,
    OTP_CTRL_FUSE_WRAPPER_WR_CFG_6,
    OTP_CTRL_FUSE_WRAPPER_WR_CFG_7,
    OTP_CTRL_FUSE_WRAPPER_WR_CFG_8
  } otp_ctrl_prim_id_e;

  // Register width information to check illegal writes for prim interface
  parameter logic [3:0] OTP_CTRL_PRIM_PERMIT [20] = '{
    4'b 1111, // index[ 0] OTP_CTRL_MACRO_CONTROL
    4'b 1111, // index[ 1] OTP_CTRL_READ_ECC_INFO
    4'b 1111, // index[ 2] OTP_CTRL_FUSE_WRAPPER_RD_CFG_0
    4'b 1111, // index[ 3] OTP_CTRL_FUSE_WRAPPER_RD_CFG_1
    4'b 1111, // index[ 4] OTP_CTRL_FUSE_WRAPPER_RD_CFG_2
    4'b 1111, // index[ 5] OTP_CTRL_FUSE_WRAPPER_RD_CFG_3
    4'b 1111, // index[ 6] OTP_CTRL_FUSE_WRAPPER_RD_CFG_4
    4'b 1111, // index[ 7] OTP_CTRL_FUSE_WRAPPER_RD_CFG_5
    4'b 1111, // index[ 8] OTP_CTRL_FUSE_WRAPPER_RD_CFG_6
    4'b 0111, // index[ 9] OTP_CTRL_FUSE_WRAPPER_RD_CFG_7
    4'b 0111, // index[10] OTP_CTRL_FUSE_WRAPPER_RD_CFG_8
    4'b 1111, // index[11] OTP_CTRL_FUSE_WRAPPER_WR_CFG_0
    4'b 1111, // index[12] OTP_CTRL_FUSE_WRAPPER_WR_CFG_1
    4'b 1111, // index[13] OTP_CTRL_FUSE_WRAPPER_WR_CFG_2
    4'b 1111, // index[14] OTP_CTRL_FUSE_WRAPPER_WR_CFG_3
    4'b 1111, // index[15] OTP_CTRL_FUSE_WRAPPER_WR_CFG_4
    4'b 1111, // index[16] OTP_CTRL_FUSE_WRAPPER_WR_CFG_5
    4'b 1111, // index[17] OTP_CTRL_FUSE_WRAPPER_WR_CFG_6
    4'b 0111, // index[18] OTP_CTRL_FUSE_WRAPPER_WR_CFG_7
    4'b 0111  // index[19] OTP_CTRL_FUSE_WRAPPER_WR_CFG_8
  };

endpackage
