// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_mio_mbx package generated by `tlgen.py` tool

package tl_mio_mbx_pkg;

  localparam logic [31:0] ADDR_SPACE_MBX0__SOC      = 32'h 01485000;
  localparam logic [31:0] ADDR_SPACE_MBX1__SOC      = 32'h 01485100;
  localparam logic [31:0] ADDR_SPACE_MBX2__SOC      = 32'h 01485200;
  localparam logic [31:0] ADDR_SPACE_MBX3__SOC      = 32'h 01485300;
  localparam logic [31:0] ADDR_SPACE_MBX4__SOC      = 32'h 01485400;
  localparam logic [31:0] ADDR_SPACE_MBX5__SOC      = 32'h 01485500;
  localparam logic [31:0] ADDR_SPACE_MBX_PCIE0__SOC = 32'h 01480100;
  localparam logic [31:0] ADDR_SPACE_RACL_CTRL      = 32'h 01483000;
  localparam logic [31:0] ADDR_SPACE_AC_RANGE_CHECK = 32'h 01484000;

  localparam logic [31:0] ADDR_MASK_MBX0__SOC      = 32'h 0000001f;
  localparam logic [31:0] ADDR_MASK_MBX1__SOC      = 32'h 0000001f;
  localparam logic [31:0] ADDR_MASK_MBX2__SOC      = 32'h 0000001f;
  localparam logic [31:0] ADDR_MASK_MBX3__SOC      = 32'h 0000001f;
  localparam logic [31:0] ADDR_MASK_MBX4__SOC      = 32'h 0000001f;
  localparam logic [31:0] ADDR_MASK_MBX5__SOC      = 32'h 0000001f;
  localparam logic [31:0] ADDR_MASK_MBX_PCIE0__SOC = 32'h 0000001f;
  localparam logic [31:0] ADDR_MASK_RACL_CTRL      = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_AC_RANGE_CHECK = 32'h 000003ff;

  localparam int N_HOST   = 1;
  localparam int N_DEVICE = 9;

  typedef enum int {
    TlMbx0Soc = 0,
    TlMbx1Soc = 1,
    TlMbx2Soc = 2,
    TlMbx3Soc = 3,
    TlMbx4Soc = 4,
    TlMbx5Soc = 5,
    TlMbxPcie0Soc = 6,
    TlRaclCtrl = 7,
    TlAcRangeCheck = 8
  } tl_device_e;

  typedef enum int {
    TlMioMbx = 0
  } tl_host_e;

endpackage
