// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_pwc_main module generated by `tlgen.py` tool
// all reset signals should be generated from one reset signal to not make any deadlock
//
// Interconnect
// rv_core_ibex_pwc.corei
//   -> s1n_29
//     -> sm1_30
//       -> rv_dm.mem
//     -> sm1_31
//       -> sram_ctrl_main.ram
//     -> sm1_32
//       -> pwc_soc_proxy.ctn
// rv_core_ibex_pwc.cored
//   -> s1n_33
//     -> sm1_30
//       -> rv_dm.mem
//     -> sm1_34
//       -> rv_dm.regs
//     -> sm1_31
//       -> sram_ctrl_main.ram
//     -> sm1_36
//       -> asf_35
//         -> pwc_peri
//     -> sm1_37
//       -> rv_plic_pwc
//     -> sm1_38
//       -> sram_ctrl_main.regs
//     -> sm1_39
//       -> rv_core_ibex_pwc.cfg
//     -> sm1_40
//       -> sram_ctrl_mbox.ram
//     -> sm1_41
//       -> sram_ctrl_mbox.regs
//     -> sm1_32
//       -> pwc_soc_proxy.ctn
//     -> sm1_42
//       -> dma
//     -> sm1_43
//       -> mbx0.core
//     -> sm1_44
//       -> mbx1.core
//     -> sm1_45
//       -> mbx2.core
//     -> sm1_46
//       -> mbx3.core
//     -> sm1_47
//       -> mbx4.core
//     -> sm1_48
//       -> mbx5.core
//     -> sm1_49
//       -> mbx_pcie0.core
// rv_dm.sba
//   -> s1n_50
//     -> sm1_30
//       -> rv_dm.mem
//     -> sm1_34
//       -> rv_dm.regs
//     -> sm1_31
//       -> sram_ctrl_main.ram
//     -> sm1_36
//       -> asf_35
//         -> pwc_peri
//     -> sm1_37
//       -> rv_plic_pwc
//     -> sm1_38
//       -> sram_ctrl_main.regs
//     -> sm1_39
//       -> rv_core_ibex_pwc.cfg
//     -> sm1_40
//       -> sram_ctrl_mbox.ram
//     -> sm1_41
//       -> sram_ctrl_mbox.regs
//     -> sm1_32
//       -> pwc_soc_proxy.ctn
//     -> sm1_42
//       -> dma
//     -> sm1_43
//       -> mbx0.core
//     -> sm1_44
//       -> mbx1.core
//     -> sm1_45
//       -> mbx2.core
//     -> sm1_46
//       -> mbx3.core
//     -> sm1_47
//       -> mbx4.core
//     -> sm1_48
//       -> mbx5.core
//     -> sm1_49
//       -> mbx_pcie0.core
// dma.host
//   -> s1n_51
//     -> sm1_31
//       -> sram_ctrl_main.ram
//     -> sm1_40
//       -> sram_ctrl_mbox.ram
//     -> sm1_32
//       -> pwc_soc_proxy.ctn
//     -> sm1_36
//       -> asf_35
//         -> pwc_peri
// mbx0.sram
//   -> s1n_52
//     -> sm1_40
//       -> sram_ctrl_mbox.ram
// mbx1.sram
//   -> s1n_53
//     -> sm1_40
//       -> sram_ctrl_mbox.ram
// mbx2.sram
//   -> s1n_54
//     -> sm1_40
//       -> sram_ctrl_mbox.ram
// mbx3.sram
//   -> s1n_55
//     -> sm1_40
//       -> sram_ctrl_mbox.ram
// mbx4.sram
//   -> s1n_56
//     -> sm1_40
//       -> sram_ctrl_mbox.ram
// mbx5.sram
//   -> s1n_57
//     -> sm1_40
//       -> sram_ctrl_mbox.ram
// mbx_pcie0.sram
//   -> s1n_58
//     -> sm1_40
//       -> sram_ctrl_mbox.ram

module xbar_pwc_main (
  input clk_main_i,
  input clk_fixed_i,
  input rst_main_ni,
  input rst_fixed_ni,

  // Host interfaces
  input  tlul_pkg::tl_h2d_t tl_rv_core_ibex_pwc__corei_i,
  output tlul_pkg::tl_d2h_t tl_rv_core_ibex_pwc__corei_o,
  input  tlul_pkg::tl_h2d_t tl_rv_core_ibex_pwc__cored_i,
  output tlul_pkg::tl_d2h_t tl_rv_core_ibex_pwc__cored_o,
  input  tlul_pkg::tl_h2d_t tl_rv_dm__sba_i,
  output tlul_pkg::tl_d2h_t tl_rv_dm__sba_o,
  input  tlul_pkg::tl_h2d_t tl_dma__host_i,
  output tlul_pkg::tl_d2h_t tl_dma__host_o,
  input  tlul_pkg::tl_h2d_t tl_mbx0__sram_i,
  output tlul_pkg::tl_d2h_t tl_mbx0__sram_o,
  input  tlul_pkg::tl_h2d_t tl_mbx1__sram_i,
  output tlul_pkg::tl_d2h_t tl_mbx1__sram_o,
  input  tlul_pkg::tl_h2d_t tl_mbx2__sram_i,
  output tlul_pkg::tl_d2h_t tl_mbx2__sram_o,
  input  tlul_pkg::tl_h2d_t tl_mbx3__sram_i,
  output tlul_pkg::tl_d2h_t tl_mbx3__sram_o,
  input  tlul_pkg::tl_h2d_t tl_mbx4__sram_i,
  output tlul_pkg::tl_d2h_t tl_mbx4__sram_o,
  input  tlul_pkg::tl_h2d_t tl_mbx5__sram_i,
  output tlul_pkg::tl_d2h_t tl_mbx5__sram_o,
  input  tlul_pkg::tl_h2d_t tl_mbx_pcie0__sram_i,
  output tlul_pkg::tl_d2h_t tl_mbx_pcie0__sram_o,

  // Device interfaces
  output tlul_pkg::tl_h2d_t tl_rv_dm__regs_o,
  input  tlul_pkg::tl_d2h_t tl_rv_dm__regs_i,
  output tlul_pkg::tl_h2d_t tl_rv_dm__mem_o,
  input  tlul_pkg::tl_d2h_t tl_rv_dm__mem_i,
  output tlul_pkg::tl_h2d_t tl_pwc_peri_o,
  input  tlul_pkg::tl_d2h_t tl_pwc_peri_i,
  output tlul_pkg::tl_h2d_t tl_pwc_soc_proxy__ctn_o,
  input  tlul_pkg::tl_d2h_t tl_pwc_soc_proxy__ctn_i,
  output tlul_pkg::tl_h2d_t tl_rv_plic_pwc_o,
  input  tlul_pkg::tl_d2h_t tl_rv_plic_pwc_i,
  output tlul_pkg::tl_h2d_t tl_rv_core_ibex_pwc__cfg_o,
  input  tlul_pkg::tl_d2h_t tl_rv_core_ibex_pwc__cfg_i,
  output tlul_pkg::tl_h2d_t tl_sram_ctrl_main__regs_o,
  input  tlul_pkg::tl_d2h_t tl_sram_ctrl_main__regs_i,
  output tlul_pkg::tl_h2d_t tl_sram_ctrl_main__ram_o,
  input  tlul_pkg::tl_d2h_t tl_sram_ctrl_main__ram_i,
  output tlul_pkg::tl_h2d_t tl_sram_ctrl_mbox__regs_o,
  input  tlul_pkg::tl_d2h_t tl_sram_ctrl_mbox__regs_i,
  output tlul_pkg::tl_h2d_t tl_sram_ctrl_mbox__ram_o,
  input  tlul_pkg::tl_d2h_t tl_sram_ctrl_mbox__ram_i,
  output tlul_pkg::tl_h2d_t tl_dma_o,
  input  tlul_pkg::tl_d2h_t tl_dma_i,
  output tlul_pkg::tl_h2d_t tl_mbx0__core_o,
  input  tlul_pkg::tl_d2h_t tl_mbx0__core_i,
  output tlul_pkg::tl_h2d_t tl_mbx1__core_o,
  input  tlul_pkg::tl_d2h_t tl_mbx1__core_i,
  output tlul_pkg::tl_h2d_t tl_mbx2__core_o,
  input  tlul_pkg::tl_d2h_t tl_mbx2__core_i,
  output tlul_pkg::tl_h2d_t tl_mbx3__core_o,
  input  tlul_pkg::tl_d2h_t tl_mbx3__core_i,
  output tlul_pkg::tl_h2d_t tl_mbx4__core_o,
  input  tlul_pkg::tl_d2h_t tl_mbx4__core_i,
  output tlul_pkg::tl_h2d_t tl_mbx5__core_o,
  input  tlul_pkg::tl_d2h_t tl_mbx5__core_i,
  output tlul_pkg::tl_h2d_t tl_mbx_pcie0__core_o,
  input  tlul_pkg::tl_d2h_t tl_mbx_pcie0__core_i,

  input prim_mubi_pkg::mubi4_t scanmode_i
);

  import tlul_pkg::*;
  import tl_pwc_main_pkg::*;

  // scanmode_i is currently not used, but provisioned for future use
  // this assignment prevents lint warnings
  logic unused_scanmode;
  assign unused_scanmode = ^scanmode_i;

  tl_h2d_t tl_s1n_29_us_h2d ;
  tl_d2h_t tl_s1n_29_us_d2h ;


  tl_h2d_t tl_s1n_29_ds_h2d [3];
  tl_d2h_t tl_s1n_29_ds_d2h [3];

  // Create steering signal
  logic [1:0] dev_sel_s1n_29;


  tl_h2d_t tl_sm1_30_us_h2d [3];
  tl_d2h_t tl_sm1_30_us_d2h [3];

  tl_h2d_t tl_sm1_30_ds_h2d ;
  tl_d2h_t tl_sm1_30_ds_d2h ;


  tl_h2d_t tl_sm1_31_us_h2d [4];
  tl_d2h_t tl_sm1_31_us_d2h [4];

  tl_h2d_t tl_sm1_31_ds_h2d ;
  tl_d2h_t tl_sm1_31_ds_d2h ;


  tl_h2d_t tl_sm1_32_us_h2d [4];
  tl_d2h_t tl_sm1_32_us_d2h [4];

  tl_h2d_t tl_sm1_32_ds_h2d ;
  tl_d2h_t tl_sm1_32_ds_d2h ;

  tl_h2d_t tl_s1n_33_us_h2d ;
  tl_d2h_t tl_s1n_33_us_d2h ;


  tl_h2d_t tl_s1n_33_ds_h2d [18];
  tl_d2h_t tl_s1n_33_ds_d2h [18];

  // Create steering signal
  logic [4:0] dev_sel_s1n_33;


  tl_h2d_t tl_sm1_34_us_h2d [2];
  tl_d2h_t tl_sm1_34_us_d2h [2];

  tl_h2d_t tl_sm1_34_ds_h2d ;
  tl_d2h_t tl_sm1_34_ds_d2h ;

  tl_h2d_t tl_asf_35_us_h2d ;
  tl_d2h_t tl_asf_35_us_d2h ;
  tl_h2d_t tl_asf_35_ds_h2d ;
  tl_d2h_t tl_asf_35_ds_d2h ;


  tl_h2d_t tl_sm1_36_us_h2d [3];
  tl_d2h_t tl_sm1_36_us_d2h [3];

  tl_h2d_t tl_sm1_36_ds_h2d ;
  tl_d2h_t tl_sm1_36_ds_d2h ;


  tl_h2d_t tl_sm1_37_us_h2d [2];
  tl_d2h_t tl_sm1_37_us_d2h [2];

  tl_h2d_t tl_sm1_37_ds_h2d ;
  tl_d2h_t tl_sm1_37_ds_d2h ;


  tl_h2d_t tl_sm1_38_us_h2d [2];
  tl_d2h_t tl_sm1_38_us_d2h [2];

  tl_h2d_t tl_sm1_38_ds_h2d ;
  tl_d2h_t tl_sm1_38_ds_d2h ;


  tl_h2d_t tl_sm1_39_us_h2d [2];
  tl_d2h_t tl_sm1_39_us_d2h [2];

  tl_h2d_t tl_sm1_39_ds_h2d ;
  tl_d2h_t tl_sm1_39_ds_d2h ;


  tl_h2d_t tl_sm1_40_us_h2d [10];
  tl_d2h_t tl_sm1_40_us_d2h [10];

  tl_h2d_t tl_sm1_40_ds_h2d ;
  tl_d2h_t tl_sm1_40_ds_d2h ;


  tl_h2d_t tl_sm1_41_us_h2d [2];
  tl_d2h_t tl_sm1_41_us_d2h [2];

  tl_h2d_t tl_sm1_41_ds_h2d ;
  tl_d2h_t tl_sm1_41_ds_d2h ;


  tl_h2d_t tl_sm1_42_us_h2d [2];
  tl_d2h_t tl_sm1_42_us_d2h [2];

  tl_h2d_t tl_sm1_42_ds_h2d ;
  tl_d2h_t tl_sm1_42_ds_d2h ;


  tl_h2d_t tl_sm1_43_us_h2d [2];
  tl_d2h_t tl_sm1_43_us_d2h [2];

  tl_h2d_t tl_sm1_43_ds_h2d ;
  tl_d2h_t tl_sm1_43_ds_d2h ;


  tl_h2d_t tl_sm1_44_us_h2d [2];
  tl_d2h_t tl_sm1_44_us_d2h [2];

  tl_h2d_t tl_sm1_44_ds_h2d ;
  tl_d2h_t tl_sm1_44_ds_d2h ;


  tl_h2d_t tl_sm1_45_us_h2d [2];
  tl_d2h_t tl_sm1_45_us_d2h [2];

  tl_h2d_t tl_sm1_45_ds_h2d ;
  tl_d2h_t tl_sm1_45_ds_d2h ;


  tl_h2d_t tl_sm1_46_us_h2d [2];
  tl_d2h_t tl_sm1_46_us_d2h [2];

  tl_h2d_t tl_sm1_46_ds_h2d ;
  tl_d2h_t tl_sm1_46_ds_d2h ;


  tl_h2d_t tl_sm1_47_us_h2d [2];
  tl_d2h_t tl_sm1_47_us_d2h [2];

  tl_h2d_t tl_sm1_47_ds_h2d ;
  tl_d2h_t tl_sm1_47_ds_d2h ;


  tl_h2d_t tl_sm1_48_us_h2d [2];
  tl_d2h_t tl_sm1_48_us_d2h [2];

  tl_h2d_t tl_sm1_48_ds_h2d ;
  tl_d2h_t tl_sm1_48_ds_d2h ;


  tl_h2d_t tl_sm1_49_us_h2d [2];
  tl_d2h_t tl_sm1_49_us_d2h [2];

  tl_h2d_t tl_sm1_49_ds_h2d ;
  tl_d2h_t tl_sm1_49_ds_d2h ;

  tl_h2d_t tl_s1n_50_us_h2d ;
  tl_d2h_t tl_s1n_50_us_d2h ;


  tl_h2d_t tl_s1n_50_ds_h2d [18];
  tl_d2h_t tl_s1n_50_ds_d2h [18];

  // Create steering signal
  logic [4:0] dev_sel_s1n_50;

  tl_h2d_t tl_s1n_51_us_h2d ;
  tl_d2h_t tl_s1n_51_us_d2h ;


  tl_h2d_t tl_s1n_51_ds_h2d [4];
  tl_d2h_t tl_s1n_51_ds_d2h [4];

  // Create steering signal
  logic [2:0] dev_sel_s1n_51;

  tl_h2d_t tl_s1n_52_us_h2d ;
  tl_d2h_t tl_s1n_52_us_d2h ;


  tl_h2d_t tl_s1n_52_ds_h2d [1];
  tl_d2h_t tl_s1n_52_ds_d2h [1];

  // Create steering signal
  logic [0:0] dev_sel_s1n_52;

  tl_h2d_t tl_s1n_53_us_h2d ;
  tl_d2h_t tl_s1n_53_us_d2h ;


  tl_h2d_t tl_s1n_53_ds_h2d [1];
  tl_d2h_t tl_s1n_53_ds_d2h [1];

  // Create steering signal
  logic [0:0] dev_sel_s1n_53;

  tl_h2d_t tl_s1n_54_us_h2d ;
  tl_d2h_t tl_s1n_54_us_d2h ;


  tl_h2d_t tl_s1n_54_ds_h2d [1];
  tl_d2h_t tl_s1n_54_ds_d2h [1];

  // Create steering signal
  logic [0:0] dev_sel_s1n_54;

  tl_h2d_t tl_s1n_55_us_h2d ;
  tl_d2h_t tl_s1n_55_us_d2h ;


  tl_h2d_t tl_s1n_55_ds_h2d [1];
  tl_d2h_t tl_s1n_55_ds_d2h [1];

  // Create steering signal
  logic [0:0] dev_sel_s1n_55;

  tl_h2d_t tl_s1n_56_us_h2d ;
  tl_d2h_t tl_s1n_56_us_d2h ;


  tl_h2d_t tl_s1n_56_ds_h2d [1];
  tl_d2h_t tl_s1n_56_ds_d2h [1];

  // Create steering signal
  logic [0:0] dev_sel_s1n_56;

  tl_h2d_t tl_s1n_57_us_h2d ;
  tl_d2h_t tl_s1n_57_us_d2h ;


  tl_h2d_t tl_s1n_57_ds_h2d [1];
  tl_d2h_t tl_s1n_57_ds_d2h [1];

  // Create steering signal
  logic [0:0] dev_sel_s1n_57;

  tl_h2d_t tl_s1n_58_us_h2d ;
  tl_d2h_t tl_s1n_58_us_d2h ;


  tl_h2d_t tl_s1n_58_ds_h2d [1];
  tl_d2h_t tl_s1n_58_ds_d2h [1];

  // Create steering signal
  logic [0:0] dev_sel_s1n_58;



  assign tl_sm1_30_us_h2d[0] = tl_s1n_29_ds_h2d[0];
  assign tl_s1n_29_ds_d2h[0] = tl_sm1_30_us_d2h[0];

  assign tl_sm1_31_us_h2d[0] = tl_s1n_29_ds_h2d[1];
  assign tl_s1n_29_ds_d2h[1] = tl_sm1_31_us_d2h[0];

  assign tl_sm1_32_us_h2d[0] = tl_s1n_29_ds_h2d[2];
  assign tl_s1n_29_ds_d2h[2] = tl_sm1_32_us_d2h[0];

  assign tl_sm1_30_us_h2d[1] = tl_s1n_33_ds_h2d[0];
  assign tl_s1n_33_ds_d2h[0] = tl_sm1_30_us_d2h[1];

  assign tl_sm1_34_us_h2d[0] = tl_s1n_33_ds_h2d[1];
  assign tl_s1n_33_ds_d2h[1] = tl_sm1_34_us_d2h[0];

  assign tl_sm1_31_us_h2d[1] = tl_s1n_33_ds_h2d[2];
  assign tl_s1n_33_ds_d2h[2] = tl_sm1_31_us_d2h[1];

  assign tl_sm1_36_us_h2d[0] = tl_s1n_33_ds_h2d[3];
  assign tl_s1n_33_ds_d2h[3] = tl_sm1_36_us_d2h[0];

  assign tl_sm1_37_us_h2d[0] = tl_s1n_33_ds_h2d[4];
  assign tl_s1n_33_ds_d2h[4] = tl_sm1_37_us_d2h[0];

  assign tl_sm1_38_us_h2d[0] = tl_s1n_33_ds_h2d[5];
  assign tl_s1n_33_ds_d2h[5] = tl_sm1_38_us_d2h[0];

  assign tl_sm1_39_us_h2d[0] = tl_s1n_33_ds_h2d[6];
  assign tl_s1n_33_ds_d2h[6] = tl_sm1_39_us_d2h[0];

  assign tl_sm1_40_us_h2d[0] = tl_s1n_33_ds_h2d[7];
  assign tl_s1n_33_ds_d2h[7] = tl_sm1_40_us_d2h[0];

  assign tl_sm1_41_us_h2d[0] = tl_s1n_33_ds_h2d[8];
  assign tl_s1n_33_ds_d2h[8] = tl_sm1_41_us_d2h[0];

  assign tl_sm1_32_us_h2d[1] = tl_s1n_33_ds_h2d[9];
  assign tl_s1n_33_ds_d2h[9] = tl_sm1_32_us_d2h[1];

  assign tl_sm1_42_us_h2d[0] = tl_s1n_33_ds_h2d[10];
  assign tl_s1n_33_ds_d2h[10] = tl_sm1_42_us_d2h[0];

  assign tl_sm1_43_us_h2d[0] = tl_s1n_33_ds_h2d[11];
  assign tl_s1n_33_ds_d2h[11] = tl_sm1_43_us_d2h[0];

  assign tl_sm1_44_us_h2d[0] = tl_s1n_33_ds_h2d[12];
  assign tl_s1n_33_ds_d2h[12] = tl_sm1_44_us_d2h[0];

  assign tl_sm1_45_us_h2d[0] = tl_s1n_33_ds_h2d[13];
  assign tl_s1n_33_ds_d2h[13] = tl_sm1_45_us_d2h[0];

  assign tl_sm1_46_us_h2d[0] = tl_s1n_33_ds_h2d[14];
  assign tl_s1n_33_ds_d2h[14] = tl_sm1_46_us_d2h[0];

  assign tl_sm1_47_us_h2d[0] = tl_s1n_33_ds_h2d[15];
  assign tl_s1n_33_ds_d2h[15] = tl_sm1_47_us_d2h[0];

  assign tl_sm1_48_us_h2d[0] = tl_s1n_33_ds_h2d[16];
  assign tl_s1n_33_ds_d2h[16] = tl_sm1_48_us_d2h[0];

  assign tl_sm1_49_us_h2d[0] = tl_s1n_33_ds_h2d[17];
  assign tl_s1n_33_ds_d2h[17] = tl_sm1_49_us_d2h[0];

  assign tl_sm1_30_us_h2d[2] = tl_s1n_50_ds_h2d[0];
  assign tl_s1n_50_ds_d2h[0] = tl_sm1_30_us_d2h[2];

  assign tl_sm1_34_us_h2d[1] = tl_s1n_50_ds_h2d[1];
  assign tl_s1n_50_ds_d2h[1] = tl_sm1_34_us_d2h[1];

  assign tl_sm1_31_us_h2d[2] = tl_s1n_50_ds_h2d[2];
  assign tl_s1n_50_ds_d2h[2] = tl_sm1_31_us_d2h[2];

  assign tl_sm1_36_us_h2d[1] = tl_s1n_50_ds_h2d[3];
  assign tl_s1n_50_ds_d2h[3] = tl_sm1_36_us_d2h[1];

  assign tl_sm1_37_us_h2d[1] = tl_s1n_50_ds_h2d[4];
  assign tl_s1n_50_ds_d2h[4] = tl_sm1_37_us_d2h[1];

  assign tl_sm1_38_us_h2d[1] = tl_s1n_50_ds_h2d[5];
  assign tl_s1n_50_ds_d2h[5] = tl_sm1_38_us_d2h[1];

  assign tl_sm1_39_us_h2d[1] = tl_s1n_50_ds_h2d[6];
  assign tl_s1n_50_ds_d2h[6] = tl_sm1_39_us_d2h[1];

  assign tl_sm1_40_us_h2d[1] = tl_s1n_50_ds_h2d[7];
  assign tl_s1n_50_ds_d2h[7] = tl_sm1_40_us_d2h[1];

  assign tl_sm1_41_us_h2d[1] = tl_s1n_50_ds_h2d[8];
  assign tl_s1n_50_ds_d2h[8] = tl_sm1_41_us_d2h[1];

  assign tl_sm1_32_us_h2d[2] = tl_s1n_50_ds_h2d[9];
  assign tl_s1n_50_ds_d2h[9] = tl_sm1_32_us_d2h[2];

  assign tl_sm1_42_us_h2d[1] = tl_s1n_50_ds_h2d[10];
  assign tl_s1n_50_ds_d2h[10] = tl_sm1_42_us_d2h[1];

  assign tl_sm1_43_us_h2d[1] = tl_s1n_50_ds_h2d[11];
  assign tl_s1n_50_ds_d2h[11] = tl_sm1_43_us_d2h[1];

  assign tl_sm1_44_us_h2d[1] = tl_s1n_50_ds_h2d[12];
  assign tl_s1n_50_ds_d2h[12] = tl_sm1_44_us_d2h[1];

  assign tl_sm1_45_us_h2d[1] = tl_s1n_50_ds_h2d[13];
  assign tl_s1n_50_ds_d2h[13] = tl_sm1_45_us_d2h[1];

  assign tl_sm1_46_us_h2d[1] = tl_s1n_50_ds_h2d[14];
  assign tl_s1n_50_ds_d2h[14] = tl_sm1_46_us_d2h[1];

  assign tl_sm1_47_us_h2d[1] = tl_s1n_50_ds_h2d[15];
  assign tl_s1n_50_ds_d2h[15] = tl_sm1_47_us_d2h[1];

  assign tl_sm1_48_us_h2d[1] = tl_s1n_50_ds_h2d[16];
  assign tl_s1n_50_ds_d2h[16] = tl_sm1_48_us_d2h[1];

  assign tl_sm1_49_us_h2d[1] = tl_s1n_50_ds_h2d[17];
  assign tl_s1n_50_ds_d2h[17] = tl_sm1_49_us_d2h[1];

  assign tl_sm1_31_us_h2d[3] = tl_s1n_51_ds_h2d[0];
  assign tl_s1n_51_ds_d2h[0] = tl_sm1_31_us_d2h[3];

  assign tl_sm1_40_us_h2d[2] = tl_s1n_51_ds_h2d[1];
  assign tl_s1n_51_ds_d2h[1] = tl_sm1_40_us_d2h[2];

  assign tl_sm1_32_us_h2d[3] = tl_s1n_51_ds_h2d[2];
  assign tl_s1n_51_ds_d2h[2] = tl_sm1_32_us_d2h[3];

  assign tl_sm1_36_us_h2d[2] = tl_s1n_51_ds_h2d[3];
  assign tl_s1n_51_ds_d2h[3] = tl_sm1_36_us_d2h[2];

  assign tl_sm1_40_us_h2d[3] = tl_s1n_52_ds_h2d[0];
  assign tl_s1n_52_ds_d2h[0] = tl_sm1_40_us_d2h[3];

  assign tl_sm1_40_us_h2d[4] = tl_s1n_53_ds_h2d[0];
  assign tl_s1n_53_ds_d2h[0] = tl_sm1_40_us_d2h[4];

  assign tl_sm1_40_us_h2d[5] = tl_s1n_54_ds_h2d[0];
  assign tl_s1n_54_ds_d2h[0] = tl_sm1_40_us_d2h[5];

  assign tl_sm1_40_us_h2d[6] = tl_s1n_55_ds_h2d[0];
  assign tl_s1n_55_ds_d2h[0] = tl_sm1_40_us_d2h[6];

  assign tl_sm1_40_us_h2d[7] = tl_s1n_56_ds_h2d[0];
  assign tl_s1n_56_ds_d2h[0] = tl_sm1_40_us_d2h[7];

  assign tl_sm1_40_us_h2d[8] = tl_s1n_57_ds_h2d[0];
  assign tl_s1n_57_ds_d2h[0] = tl_sm1_40_us_d2h[8];

  assign tl_sm1_40_us_h2d[9] = tl_s1n_58_ds_h2d[0];
  assign tl_s1n_58_ds_d2h[0] = tl_sm1_40_us_d2h[9];

  assign tl_s1n_29_us_h2d = tl_rv_core_ibex_pwc__corei_i;
  assign tl_rv_core_ibex_pwc__corei_o = tl_s1n_29_us_d2h;

  assign tl_rv_dm__mem_o = tl_sm1_30_ds_h2d;
  assign tl_sm1_30_ds_d2h = tl_rv_dm__mem_i;

  assign tl_sram_ctrl_main__ram_o = tl_sm1_31_ds_h2d;
  assign tl_sm1_31_ds_d2h = tl_sram_ctrl_main__ram_i;

  assign tl_pwc_soc_proxy__ctn_o = tl_sm1_32_ds_h2d;
  assign tl_sm1_32_ds_d2h = tl_pwc_soc_proxy__ctn_i;

  assign tl_s1n_33_us_h2d = tl_rv_core_ibex_pwc__cored_i;
  assign tl_rv_core_ibex_pwc__cored_o = tl_s1n_33_us_d2h;

  assign tl_rv_dm__regs_o = tl_sm1_34_ds_h2d;
  assign tl_sm1_34_ds_d2h = tl_rv_dm__regs_i;

  assign tl_pwc_peri_o = tl_asf_35_ds_h2d;
  assign tl_asf_35_ds_d2h = tl_pwc_peri_i;

  assign tl_asf_35_us_h2d = tl_sm1_36_ds_h2d;
  assign tl_sm1_36_ds_d2h = tl_asf_35_us_d2h;

  assign tl_rv_plic_pwc_o = tl_sm1_37_ds_h2d;
  assign tl_sm1_37_ds_d2h = tl_rv_plic_pwc_i;

  assign tl_sram_ctrl_main__regs_o = tl_sm1_38_ds_h2d;
  assign tl_sm1_38_ds_d2h = tl_sram_ctrl_main__regs_i;

  assign tl_rv_core_ibex_pwc__cfg_o = tl_sm1_39_ds_h2d;
  assign tl_sm1_39_ds_d2h = tl_rv_core_ibex_pwc__cfg_i;

  assign tl_sram_ctrl_mbox__ram_o = tl_sm1_40_ds_h2d;
  assign tl_sm1_40_ds_d2h = tl_sram_ctrl_mbox__ram_i;

  assign tl_sram_ctrl_mbox__regs_o = tl_sm1_41_ds_h2d;
  assign tl_sm1_41_ds_d2h = tl_sram_ctrl_mbox__regs_i;

  assign tl_dma_o = tl_sm1_42_ds_h2d;
  assign tl_sm1_42_ds_d2h = tl_dma_i;

  assign tl_mbx0__core_o = tl_sm1_43_ds_h2d;
  assign tl_sm1_43_ds_d2h = tl_mbx0__core_i;

  assign tl_mbx1__core_o = tl_sm1_44_ds_h2d;
  assign tl_sm1_44_ds_d2h = tl_mbx1__core_i;

  assign tl_mbx2__core_o = tl_sm1_45_ds_h2d;
  assign tl_sm1_45_ds_d2h = tl_mbx2__core_i;

  assign tl_mbx3__core_o = tl_sm1_46_ds_h2d;
  assign tl_sm1_46_ds_d2h = tl_mbx3__core_i;

  assign tl_mbx4__core_o = tl_sm1_47_ds_h2d;
  assign tl_sm1_47_ds_d2h = tl_mbx4__core_i;

  assign tl_mbx5__core_o = tl_sm1_48_ds_h2d;
  assign tl_sm1_48_ds_d2h = tl_mbx5__core_i;

  assign tl_mbx_pcie0__core_o = tl_sm1_49_ds_h2d;
  assign tl_sm1_49_ds_d2h = tl_mbx_pcie0__core_i;

  assign tl_s1n_50_us_h2d = tl_rv_dm__sba_i;
  assign tl_rv_dm__sba_o = tl_s1n_50_us_d2h;

  assign tl_s1n_51_us_h2d = tl_dma__host_i;
  assign tl_dma__host_o = tl_s1n_51_us_d2h;

  assign tl_s1n_52_us_h2d = tl_mbx0__sram_i;
  assign tl_mbx0__sram_o = tl_s1n_52_us_d2h;

  assign tl_s1n_53_us_h2d = tl_mbx1__sram_i;
  assign tl_mbx1__sram_o = tl_s1n_53_us_d2h;

  assign tl_s1n_54_us_h2d = tl_mbx2__sram_i;
  assign tl_mbx2__sram_o = tl_s1n_54_us_d2h;

  assign tl_s1n_55_us_h2d = tl_mbx3__sram_i;
  assign tl_mbx3__sram_o = tl_s1n_55_us_d2h;

  assign tl_s1n_56_us_h2d = tl_mbx4__sram_i;
  assign tl_mbx4__sram_o = tl_s1n_56_us_d2h;

  assign tl_s1n_57_us_h2d = tl_mbx5__sram_i;
  assign tl_mbx5__sram_o = tl_s1n_57_us_d2h;

  assign tl_s1n_58_us_h2d = tl_mbx_pcie0__sram_i;
  assign tl_mbx_pcie0__sram_o = tl_s1n_58_us_d2h;

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_29 = 2'd3;
    if ((tl_s1n_29_us_h2d.a_address &
         ~(ADDR_MASK_RV_DM__MEM)) == ADDR_SPACE_RV_DM__MEM) begin
      dev_sel_s1n_29 = 2'd0;

    end else if ((tl_s1n_29_us_h2d.a_address &
                  ~(ADDR_MASK_SRAM_CTRL_MAIN__RAM)) == ADDR_SPACE_SRAM_CTRL_MAIN__RAM) begin
      dev_sel_s1n_29 = 2'd1;

    end else if (((tl_s1n_29_us_h2d.a_address < (ADDR_SPACE_PWC_SOC_PROXY__CTN + ADDR_SIZE_PWC_SOC_PROXY__CTN)) &&
       (tl_s1n_29_us_h2d.a_address >= ADDR_SPACE_PWC_SOC_PROXY__CTN))) begin
      dev_sel_s1n_29 = 2'd2;
end
  end

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_33 = 5'd18;
    if ((tl_s1n_33_us_h2d.a_address &
         ~(ADDR_MASK_RV_DM__MEM)) == ADDR_SPACE_RV_DM__MEM) begin
      dev_sel_s1n_33 = 5'd0;

    end else if ((tl_s1n_33_us_h2d.a_address &
                  ~(ADDR_MASK_RV_DM__REGS)) == ADDR_SPACE_RV_DM__REGS) begin
      dev_sel_s1n_33 = 5'd1;

    end else if ((tl_s1n_33_us_h2d.a_address &
                  ~(ADDR_MASK_SRAM_CTRL_MAIN__RAM)) == ADDR_SPACE_SRAM_CTRL_MAIN__RAM) begin
      dev_sel_s1n_33 = 5'd2;

    end else if ((tl_s1n_33_us_h2d.a_address &
                  ~(ADDR_MASK_PWC_PERI)) == ADDR_SPACE_PWC_PERI) begin
      dev_sel_s1n_33 = 5'd3;

    end else if ((tl_s1n_33_us_h2d.a_address &
                  ~(ADDR_MASK_RV_PLIC_PWC)) == ADDR_SPACE_RV_PLIC_PWC) begin
      dev_sel_s1n_33 = 5'd4;

    end else if ((tl_s1n_33_us_h2d.a_address &
                  ~(ADDR_MASK_SRAM_CTRL_MAIN__REGS)) == ADDR_SPACE_SRAM_CTRL_MAIN__REGS) begin
      dev_sel_s1n_33 = 5'd5;

    end else if ((tl_s1n_33_us_h2d.a_address &
                  ~(ADDR_MASK_RV_CORE_IBEX_PWC__CFG)) == ADDR_SPACE_RV_CORE_IBEX_PWC__CFG) begin
      dev_sel_s1n_33 = 5'd6;

    end else if ((tl_s1n_33_us_h2d.a_address &
                  ~(ADDR_MASK_SRAM_CTRL_MBOX__RAM)) == ADDR_SPACE_SRAM_CTRL_MBOX__RAM) begin
      dev_sel_s1n_33 = 5'd7;

    end else if ((tl_s1n_33_us_h2d.a_address &
                  ~(ADDR_MASK_SRAM_CTRL_MBOX__REGS)) == ADDR_SPACE_SRAM_CTRL_MBOX__REGS) begin
      dev_sel_s1n_33 = 5'd8;

    end else if (((tl_s1n_33_us_h2d.a_address < (ADDR_SPACE_PWC_SOC_PROXY__CTN + ADDR_SIZE_PWC_SOC_PROXY__CTN)) &&
       (tl_s1n_33_us_h2d.a_address >= ADDR_SPACE_PWC_SOC_PROXY__CTN))) begin
      dev_sel_s1n_33 = 5'd9;

    end else if ((tl_s1n_33_us_h2d.a_address &
                  ~(ADDR_MASK_DMA)) == ADDR_SPACE_DMA) begin
      dev_sel_s1n_33 = 5'd10;

    end else if ((tl_s1n_33_us_h2d.a_address &
                  ~(ADDR_MASK_MBX0__CORE)) == ADDR_SPACE_MBX0__CORE) begin
      dev_sel_s1n_33 = 5'd11;

    end else if ((tl_s1n_33_us_h2d.a_address &
                  ~(ADDR_MASK_MBX1__CORE)) == ADDR_SPACE_MBX1__CORE) begin
      dev_sel_s1n_33 = 5'd12;

    end else if ((tl_s1n_33_us_h2d.a_address &
                  ~(ADDR_MASK_MBX2__CORE)) == ADDR_SPACE_MBX2__CORE) begin
      dev_sel_s1n_33 = 5'd13;

    end else if ((tl_s1n_33_us_h2d.a_address &
                  ~(ADDR_MASK_MBX3__CORE)) == ADDR_SPACE_MBX3__CORE) begin
      dev_sel_s1n_33 = 5'd14;

    end else if ((tl_s1n_33_us_h2d.a_address &
                  ~(ADDR_MASK_MBX4__CORE)) == ADDR_SPACE_MBX4__CORE) begin
      dev_sel_s1n_33 = 5'd15;

    end else if ((tl_s1n_33_us_h2d.a_address &
                  ~(ADDR_MASK_MBX5__CORE)) == ADDR_SPACE_MBX5__CORE) begin
      dev_sel_s1n_33 = 5'd16;

    end else if ((tl_s1n_33_us_h2d.a_address &
                  ~(ADDR_MASK_MBX_PCIE0__CORE)) == ADDR_SPACE_MBX_PCIE0__CORE) begin
      dev_sel_s1n_33 = 5'd17;
end
  end

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_50 = 5'd18;
    if ((tl_s1n_50_us_h2d.a_address &
         ~(ADDR_MASK_RV_DM__MEM)) == ADDR_SPACE_RV_DM__MEM) begin
      dev_sel_s1n_50 = 5'd0;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_RV_DM__REGS)) == ADDR_SPACE_RV_DM__REGS) begin
      dev_sel_s1n_50 = 5'd1;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_SRAM_CTRL_MAIN__RAM)) == ADDR_SPACE_SRAM_CTRL_MAIN__RAM) begin
      dev_sel_s1n_50 = 5'd2;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_PWC_PERI)) == ADDR_SPACE_PWC_PERI) begin
      dev_sel_s1n_50 = 5'd3;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_RV_PLIC_PWC)) == ADDR_SPACE_RV_PLIC_PWC) begin
      dev_sel_s1n_50 = 5'd4;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_SRAM_CTRL_MAIN__REGS)) == ADDR_SPACE_SRAM_CTRL_MAIN__REGS) begin
      dev_sel_s1n_50 = 5'd5;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_RV_CORE_IBEX_PWC__CFG)) == ADDR_SPACE_RV_CORE_IBEX_PWC__CFG) begin
      dev_sel_s1n_50 = 5'd6;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_SRAM_CTRL_MBOX__RAM)) == ADDR_SPACE_SRAM_CTRL_MBOX__RAM) begin
      dev_sel_s1n_50 = 5'd7;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_SRAM_CTRL_MBOX__REGS)) == ADDR_SPACE_SRAM_CTRL_MBOX__REGS) begin
      dev_sel_s1n_50 = 5'd8;

    end else if (((tl_s1n_50_us_h2d.a_address < (ADDR_SPACE_PWC_SOC_PROXY__CTN + ADDR_SIZE_PWC_SOC_PROXY__CTN)) &&
       (tl_s1n_50_us_h2d.a_address >= ADDR_SPACE_PWC_SOC_PROXY__CTN))) begin
      dev_sel_s1n_50 = 5'd9;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_DMA)) == ADDR_SPACE_DMA) begin
      dev_sel_s1n_50 = 5'd10;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_MBX0__CORE)) == ADDR_SPACE_MBX0__CORE) begin
      dev_sel_s1n_50 = 5'd11;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_MBX1__CORE)) == ADDR_SPACE_MBX1__CORE) begin
      dev_sel_s1n_50 = 5'd12;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_MBX2__CORE)) == ADDR_SPACE_MBX2__CORE) begin
      dev_sel_s1n_50 = 5'd13;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_MBX3__CORE)) == ADDR_SPACE_MBX3__CORE) begin
      dev_sel_s1n_50 = 5'd14;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_MBX4__CORE)) == ADDR_SPACE_MBX4__CORE) begin
      dev_sel_s1n_50 = 5'd15;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_MBX5__CORE)) == ADDR_SPACE_MBX5__CORE) begin
      dev_sel_s1n_50 = 5'd16;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_MBX_PCIE0__CORE)) == ADDR_SPACE_MBX_PCIE0__CORE) begin
      dev_sel_s1n_50 = 5'd17;
end
  end

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_51 = 3'd4;
    if ((tl_s1n_51_us_h2d.a_address &
         ~(ADDR_MASK_SRAM_CTRL_MAIN__RAM)) == ADDR_SPACE_SRAM_CTRL_MAIN__RAM) begin
      dev_sel_s1n_51 = 3'd0;

    end else if ((tl_s1n_51_us_h2d.a_address &
                  ~(ADDR_MASK_SRAM_CTRL_MBOX__RAM)) == ADDR_SPACE_SRAM_CTRL_MBOX__RAM) begin
      dev_sel_s1n_51 = 3'd1;

    end else if (((tl_s1n_51_us_h2d.a_address < (ADDR_SPACE_PWC_SOC_PROXY__CTN + ADDR_SIZE_PWC_SOC_PROXY__CTN)) &&
       (tl_s1n_51_us_h2d.a_address >= ADDR_SPACE_PWC_SOC_PROXY__CTN))) begin
      dev_sel_s1n_51 = 3'd2;

    end else if ((tl_s1n_51_us_h2d.a_address &
                  ~(ADDR_MASK_PWC_PERI)) == ADDR_SPACE_PWC_PERI) begin
      dev_sel_s1n_51 = 3'd3;
end
  end

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_52 = 1'd1;
    if ((tl_s1n_52_us_h2d.a_address &
         ~(ADDR_MASK_SRAM_CTRL_MBOX__RAM)) == ADDR_SPACE_SRAM_CTRL_MBOX__RAM) begin
      dev_sel_s1n_52 = 1'd0;
end
  end

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_53 = 1'd1;
    if ((tl_s1n_53_us_h2d.a_address &
         ~(ADDR_MASK_SRAM_CTRL_MBOX__RAM)) == ADDR_SPACE_SRAM_CTRL_MBOX__RAM) begin
      dev_sel_s1n_53 = 1'd0;
end
  end

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_54 = 1'd1;
    if ((tl_s1n_54_us_h2d.a_address &
         ~(ADDR_MASK_SRAM_CTRL_MBOX__RAM)) == ADDR_SPACE_SRAM_CTRL_MBOX__RAM) begin
      dev_sel_s1n_54 = 1'd0;
end
  end

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_55 = 1'd1;
    if ((tl_s1n_55_us_h2d.a_address &
         ~(ADDR_MASK_SRAM_CTRL_MBOX__RAM)) == ADDR_SPACE_SRAM_CTRL_MBOX__RAM) begin
      dev_sel_s1n_55 = 1'd0;
end
  end

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_56 = 1'd1;
    if ((tl_s1n_56_us_h2d.a_address &
         ~(ADDR_MASK_SRAM_CTRL_MBOX__RAM)) == ADDR_SPACE_SRAM_CTRL_MBOX__RAM) begin
      dev_sel_s1n_56 = 1'd0;
end
  end

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_57 = 1'd1;
    if ((tl_s1n_57_us_h2d.a_address &
         ~(ADDR_MASK_SRAM_CTRL_MBOX__RAM)) == ADDR_SPACE_SRAM_CTRL_MBOX__RAM) begin
      dev_sel_s1n_57 = 1'd0;
end
  end

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_58 = 1'd1;
    if ((tl_s1n_58_us_h2d.a_address &
         ~(ADDR_MASK_SRAM_CTRL_MBOX__RAM)) == ADDR_SPACE_SRAM_CTRL_MBOX__RAM) begin
      dev_sel_s1n_58 = 1'd0;
end
  end


  // Instantiation phase
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h0),
    .DReqDepth (12'h0),
    .DRspDepth (12'h0),
    .N         (3)
  ) u_s1n_29 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_s1n_29_us_h2d),
    .tl_h_o       (tl_s1n_29_us_d2h),
    .tl_d_o       (tl_s1n_29_ds_h2d),
    .tl_d_i       (tl_s1n_29_ds_d2h),
    .dev_select_i (dev_sel_s1n_29)
  );
  tlul_socket_m1 #(
    .HReqDepth (12'h0),
    .HRspDepth (12'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (3)
  ) u_sm1_30 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_30_us_h2d),
    .tl_h_o       (tl_sm1_30_us_d2h),
    .tl_d_o       (tl_sm1_30_ds_h2d),
    .tl_d_i       (tl_sm1_30_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (16'h0),
    .HRspDepth (16'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (4)
  ) u_sm1_31 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_31_us_h2d),
    .tl_h_o       (tl_sm1_31_us_d2h),
    .tl_d_o       (tl_sm1_31_ds_h2d),
    .tl_d_i       (tl_sm1_31_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (16'h0),
    .HRspDepth (16'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (4)
  ) u_sm1_32 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_32_us_h2d),
    .tl_h_o       (tl_sm1_32_us_d2h),
    .tl_d_o       (tl_sm1_32_ds_h2d),
    .tl_d_i       (tl_sm1_32_ds_d2h)
  );
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h0),
    .DReqDepth (72'h0),
    .DRspDepth (72'h0),
    .N         (18)
  ) u_s1n_33 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_s1n_33_us_h2d),
    .tl_h_o       (tl_s1n_33_us_d2h),
    .tl_d_o       (tl_s1n_33_ds_h2d),
    .tl_d_i       (tl_s1n_33_ds_d2h),
    .dev_select_i (dev_sel_s1n_33)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (2)
  ) u_sm1_34 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_34_us_h2d),
    .tl_h_o       (tl_sm1_34_us_d2h),
    .tl_d_o       (tl_sm1_34_ds_h2d),
    .tl_d_i       (tl_sm1_34_ds_d2h)
  );
  tlul_fifo_async #(
    .ReqDepth        (1),
    .RspDepth        (1)
  ) u_asf_35 (
    .clk_h_i      (clk_main_i),
    .rst_h_ni     (rst_main_ni),
    .clk_d_i      (clk_fixed_i),
    .rst_d_ni     (rst_fixed_ni),
    .tl_h_i       (tl_asf_35_us_h2d),
    .tl_h_o       (tl_asf_35_us_d2h),
    .tl_d_o       (tl_asf_35_ds_h2d),
    .tl_d_i       (tl_asf_35_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (12'h0),
    .HRspDepth (12'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (3)
  ) u_sm1_36 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_36_us_h2d),
    .tl_h_o       (tl_sm1_36_us_d2h),
    .tl_d_o       (tl_sm1_36_ds_h2d),
    .tl_d_i       (tl_sm1_36_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (2)
  ) u_sm1_37 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_37_us_h2d),
    .tl_h_o       (tl_sm1_37_us_d2h),
    .tl_d_o       (tl_sm1_37_ds_h2d),
    .tl_d_i       (tl_sm1_37_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (2)
  ) u_sm1_38 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_38_us_h2d),
    .tl_h_o       (tl_sm1_38_us_d2h),
    .tl_d_o       (tl_sm1_38_ds_h2d),
    .tl_d_i       (tl_sm1_38_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (2)
  ) u_sm1_39 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_39_us_h2d),
    .tl_h_o       (tl_sm1_39_us_d2h),
    .tl_d_o       (tl_sm1_39_ds_h2d),
    .tl_d_i       (tl_sm1_39_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (40'h0),
    .HRspDepth (40'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (10)
  ) u_sm1_40 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_40_us_h2d),
    .tl_h_o       (tl_sm1_40_us_d2h),
    .tl_d_o       (tl_sm1_40_ds_h2d),
    .tl_d_i       (tl_sm1_40_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (2)
  ) u_sm1_41 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_41_us_h2d),
    .tl_h_o       (tl_sm1_41_us_d2h),
    .tl_d_o       (tl_sm1_41_ds_h2d),
    .tl_d_i       (tl_sm1_41_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (2)
  ) u_sm1_42 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_42_us_h2d),
    .tl_h_o       (tl_sm1_42_us_d2h),
    .tl_d_o       (tl_sm1_42_ds_h2d),
    .tl_d_i       (tl_sm1_42_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (2)
  ) u_sm1_43 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_43_us_h2d),
    .tl_h_o       (tl_sm1_43_us_d2h),
    .tl_d_o       (tl_sm1_43_ds_h2d),
    .tl_d_i       (tl_sm1_43_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (2)
  ) u_sm1_44 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_44_us_h2d),
    .tl_h_o       (tl_sm1_44_us_d2h),
    .tl_d_o       (tl_sm1_44_ds_h2d),
    .tl_d_i       (tl_sm1_44_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (2)
  ) u_sm1_45 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_45_us_h2d),
    .tl_h_o       (tl_sm1_45_us_d2h),
    .tl_d_o       (tl_sm1_45_ds_h2d),
    .tl_d_i       (tl_sm1_45_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (2)
  ) u_sm1_46 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_46_us_h2d),
    .tl_h_o       (tl_sm1_46_us_d2h),
    .tl_d_o       (tl_sm1_46_ds_h2d),
    .tl_d_i       (tl_sm1_46_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (2)
  ) u_sm1_47 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_47_us_h2d),
    .tl_h_o       (tl_sm1_47_us_d2h),
    .tl_d_o       (tl_sm1_47_ds_h2d),
    .tl_d_i       (tl_sm1_47_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (2)
  ) u_sm1_48 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_48_us_h2d),
    .tl_h_o       (tl_sm1_48_us_d2h),
    .tl_d_o       (tl_sm1_48_ds_h2d),
    .tl_d_i       (tl_sm1_48_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (2)
  ) u_sm1_49 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_sm1_49_us_h2d),
    .tl_h_o       (tl_sm1_49_us_d2h),
    .tl_d_o       (tl_sm1_49_ds_h2d),
    .tl_d_i       (tl_sm1_49_ds_d2h)
  );
  tlul_socket_1n #(
    .HReqPass  (1'b0),
    .HRspPass  (1'b0),
    .DReqDepth (72'h0),
    .DRspDepth (72'h0),
    .N         (18)
  ) u_s1n_50 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_s1n_50_us_h2d),
    .tl_h_o       (tl_s1n_50_us_d2h),
    .tl_d_o       (tl_s1n_50_ds_h2d),
    .tl_d_i       (tl_s1n_50_ds_d2h),
    .dev_select_i (dev_sel_s1n_50)
  );
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h0),
    .DReqDepth (16'h0),
    .DRspDepth (16'h0),
    .N         (4)
  ) u_s1n_51 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_s1n_51_us_h2d),
    .tl_h_o       (tl_s1n_51_us_d2h),
    .tl_d_o       (tl_s1n_51_ds_h2d),
    .tl_d_i       (tl_s1n_51_ds_d2h),
    .dev_select_i (dev_sel_s1n_51)
  );
  tlul_socket_1n #(
    .HReqPass  (1'b0),
    .HRspPass  (1'b0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .N         (1)
  ) u_s1n_52 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_s1n_52_us_h2d),
    .tl_h_o       (tl_s1n_52_us_d2h),
    .tl_d_o       (tl_s1n_52_ds_h2d),
    .tl_d_i       (tl_s1n_52_ds_d2h),
    .dev_select_i (dev_sel_s1n_52)
  );
  tlul_socket_1n #(
    .HReqPass  (1'b0),
    .HRspPass  (1'b0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .N         (1)
  ) u_s1n_53 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_s1n_53_us_h2d),
    .tl_h_o       (tl_s1n_53_us_d2h),
    .tl_d_o       (tl_s1n_53_ds_h2d),
    .tl_d_i       (tl_s1n_53_ds_d2h),
    .dev_select_i (dev_sel_s1n_53)
  );
  tlul_socket_1n #(
    .HReqPass  (1'b0),
    .HRspPass  (1'b0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .N         (1)
  ) u_s1n_54 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_s1n_54_us_h2d),
    .tl_h_o       (tl_s1n_54_us_d2h),
    .tl_d_o       (tl_s1n_54_ds_h2d),
    .tl_d_i       (tl_s1n_54_ds_d2h),
    .dev_select_i (dev_sel_s1n_54)
  );
  tlul_socket_1n #(
    .HReqPass  (1'b0),
    .HRspPass  (1'b0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .N         (1)
  ) u_s1n_55 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_s1n_55_us_h2d),
    .tl_h_o       (tl_s1n_55_us_d2h),
    .tl_d_o       (tl_s1n_55_ds_h2d),
    .tl_d_i       (tl_s1n_55_ds_d2h),
    .dev_select_i (dev_sel_s1n_55)
  );
  tlul_socket_1n #(
    .HReqPass  (1'b0),
    .HRspPass  (1'b0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .N         (1)
  ) u_s1n_56 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_s1n_56_us_h2d),
    .tl_h_o       (tl_s1n_56_us_d2h),
    .tl_d_o       (tl_s1n_56_ds_h2d),
    .tl_d_i       (tl_s1n_56_ds_d2h),
    .dev_select_i (dev_sel_s1n_56)
  );
  tlul_socket_1n #(
    .HReqPass  (1'b0),
    .HRspPass  (1'b0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .N         (1)
  ) u_s1n_57 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_s1n_57_us_h2d),
    .tl_h_o       (tl_s1n_57_us_d2h),
    .tl_d_o       (tl_s1n_57_ds_h2d),
    .tl_d_i       (tl_s1n_57_ds_d2h),
    .dev_select_i (dev_sel_s1n_57)
  );
  tlul_socket_1n #(
    .HReqPass  (1'b0),
    .HRspPass  (1'b0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .N         (1)
  ) u_s1n_58 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_s1n_58_us_h2d),
    .tl_h_o       (tl_s1n_58_us_d2h),
    .tl_d_o       (tl_s1n_58_ds_h2d),
    .tl_d_i       (tl_s1n_58_ds_d2h),
    .dev_select_i (dev_sel_s1n_58)
  );

endmodule
// Local Variables:
// fill-column:1
// verilog-auto-arg-sort:t
// verilog-typedef-regexp: "_[etu]$"
// End:
