// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// This file was generated automatically.
// Please do not modify content of this file directly.
// File generated by using template: "toplevel.rs.tpl"
// To regenerate this file follow OpenTitan topgen documentations.

#![allow(dead_code)]

//! This file contains enums and consts for use within the Rust codebase.
//!
//! These definitions are for information that depends on the top-specific chip
//! configuration, which includes:
//! - Device Memory Information (for Peripherals and Memory)
//! - PLIC Interrupt ID Names and Source Mappings
//! - Alert ID Names and Source Mappings

use core::convert::TryFrom;

/// Peripheral base address for gpio in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const GPIO_BASE_ADDR: usize = 0x30000000;

/// Peripheral size for gpio in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #GPIO_BASE_ADDR and
/// `GPIO_BASE_ADDR + GPIO_SIZE_BYTES`.
pub const GPIO_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for rv_timer in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_TIMER_BASE_ADDR: usize = 0x30100000;

/// Peripheral size for rv_timer in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_TIMER_BASE_ADDR and
/// `RV_TIMER_BASE_ADDR + RV_TIMER_SIZE_BYTES`.
pub const RV_TIMER_SIZE_BYTES: usize = 0x200;

/// Peripheral base address for aon_timer_aon in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const AON_TIMER_AON_BASE_ADDR: usize = 0x30470000;

/// Peripheral size for aon_timer_aon in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #AON_TIMER_AON_BASE_ADDR and
/// `AON_TIMER_AON_BASE_ADDR + AON_TIMER_AON_SIZE_BYTES`.
pub const AON_TIMER_AON_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for ctn device on pwc_soc_proxy in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const PWC_SOC_PROXY_CTN_BASE_ADDR: usize = 0x40000000;

/// Peripheral size for ctn device on pwc_soc_proxy in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #PWC_SOC_PROXY_CTN_BASE_ADDR and
/// `PWC_SOC_PROXY_CTN_BASE_ADDR + PWC_SOC_PROXY_CTN_SIZE_BYTES`.
pub const PWC_SOC_PROXY_CTN_SIZE_BYTES: usize = 0x40000000;

/// Peripheral base address for regs device on sram_ctrl_ret_aon in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_RET_AON_REGS_BASE_ADDR: usize = 0x30500000;

/// Peripheral size for regs device on sram_ctrl_ret_aon in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_RET_AON_REGS_BASE_ADDR and
/// `SRAM_CTRL_RET_AON_REGS_BASE_ADDR + SRAM_CTRL_RET_AON_REGS_SIZE_BYTES`.
pub const SRAM_CTRL_RET_AON_REGS_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for ram device on sram_ctrl_ret_aon in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_RET_AON_RAM_BASE_ADDR: usize = 0x30600000;

/// Peripheral size for ram device on sram_ctrl_ret_aon in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_RET_AON_RAM_BASE_ADDR and
/// `SRAM_CTRL_RET_AON_RAM_BASE_ADDR + SRAM_CTRL_RET_AON_RAM_SIZE_BYTES`.
pub const SRAM_CTRL_RET_AON_RAM_SIZE_BYTES: usize = 0x1000;

/// Peripheral base address for regs device on rv_dm in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_DM_REGS_BASE_ADDR: usize = 0x21200000;

/// Peripheral size for regs device on rv_dm in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_DM_REGS_BASE_ADDR and
/// `RV_DM_REGS_BASE_ADDR + RV_DM_REGS_SIZE_BYTES`.
pub const RV_DM_REGS_SIZE_BYTES: usize = 0x10;

/// Peripheral base address for mem device on rv_dm in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_DM_MEM_BASE_ADDR: usize = 0x40000;

/// Peripheral size for mem device on rv_dm in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_DM_MEM_BASE_ADDR and
/// `RV_DM_MEM_BASE_ADDR + RV_DM_MEM_SIZE_BYTES`.
pub const RV_DM_MEM_SIZE_BYTES: usize = 0x1000;

/// Peripheral base address for rv_plic_pwc in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_PLIC_PWC_BASE_ADDR: usize = 0x28000000;

/// Peripheral size for rv_plic_pwc in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_PLIC_PWC_BASE_ADDR and
/// `RV_PLIC_PWC_BASE_ADDR + RV_PLIC_PWC_SIZE_BYTES`.
pub const RV_PLIC_PWC_SIZE_BYTES: usize = 0x8000000;

/// Peripheral base address for regs device on sram_ctrl_main in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_MAIN_REGS_BASE_ADDR: usize = 0x211C0000;

/// Peripheral size for regs device on sram_ctrl_main in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_MAIN_REGS_BASE_ADDR and
/// `SRAM_CTRL_MAIN_REGS_BASE_ADDR + SRAM_CTRL_MAIN_REGS_SIZE_BYTES`.
pub const SRAM_CTRL_MAIN_REGS_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for ram device on sram_ctrl_main in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_MAIN_RAM_BASE_ADDR: usize = 0x10000000;

/// Peripheral size for ram device on sram_ctrl_main in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_MAIN_RAM_BASE_ADDR and
/// `SRAM_CTRL_MAIN_RAM_BASE_ADDR + SRAM_CTRL_MAIN_RAM_SIZE_BYTES`.
pub const SRAM_CTRL_MAIN_RAM_SIZE_BYTES: usize = 0x10000;

/// Peripheral base address for regs device on sram_ctrl_mbox in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_MBOX_REGS_BASE_ADDR: usize = 0x211D0000;

/// Peripheral size for regs device on sram_ctrl_mbox in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_MBOX_REGS_BASE_ADDR and
/// `SRAM_CTRL_MBOX_REGS_BASE_ADDR + SRAM_CTRL_MBOX_REGS_SIZE_BYTES`.
pub const SRAM_CTRL_MBOX_REGS_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for ram device on sram_ctrl_mbox in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_MBOX_RAM_BASE_ADDR: usize = 0x11000000;

/// Peripheral size for ram device on sram_ctrl_mbox in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_MBOX_RAM_BASE_ADDR and
/// `SRAM_CTRL_MBOX_RAM_BASE_ADDR + SRAM_CTRL_MBOX_RAM_SIZE_BYTES`.
pub const SRAM_CTRL_MBOX_RAM_SIZE_BYTES: usize = 0x1000;

/// Peripheral base address for dma in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const DMA_BASE_ADDR: usize = 0x22010000;

/// Peripheral size for dma in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #DMA_BASE_ADDR and
/// `DMA_BASE_ADDR + DMA_SIZE_BYTES`.
pub const DMA_SIZE_BYTES: usize = 0x200;

/// Peripheral base address for core device on mbx0 in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX0_CORE_BASE_ADDR: usize = 0x22000000;

/// Peripheral size for core device on mbx0 in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX0_CORE_BASE_ADDR and
/// `MBX0_CORE_BASE_ADDR + MBX0_CORE_SIZE_BYTES`.
pub const MBX0_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx1 in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX1_CORE_BASE_ADDR: usize = 0x22000100;

/// Peripheral size for core device on mbx1 in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX1_CORE_BASE_ADDR and
/// `MBX1_CORE_BASE_ADDR + MBX1_CORE_SIZE_BYTES`.
pub const MBX1_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx2 in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX2_CORE_BASE_ADDR: usize = 0x22000200;

/// Peripheral size for core device on mbx2 in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX2_CORE_BASE_ADDR and
/// `MBX2_CORE_BASE_ADDR + MBX2_CORE_SIZE_BYTES`.
pub const MBX2_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx3 in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX3_CORE_BASE_ADDR: usize = 0x22000300;

/// Peripheral size for core device on mbx3 in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX3_CORE_BASE_ADDR and
/// `MBX3_CORE_BASE_ADDR + MBX3_CORE_SIZE_BYTES`.
pub const MBX3_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx4 in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX4_CORE_BASE_ADDR: usize = 0x22000400;

/// Peripheral size for core device on mbx4 in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX4_CORE_BASE_ADDR and
/// `MBX4_CORE_BASE_ADDR + MBX4_CORE_SIZE_BYTES`.
pub const MBX4_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx5 in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX5_CORE_BASE_ADDR: usize = 0x22000500;

/// Peripheral size for core device on mbx5 in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX5_CORE_BASE_ADDR and
/// `MBX5_CORE_BASE_ADDR + MBX5_CORE_SIZE_BYTES`.
pub const MBX5_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx_pcie0 in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX_PCIE0_CORE_BASE_ADDR: usize = 0x22040000;

/// Peripheral size for core device on mbx_pcie0 in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX_PCIE0_CORE_BASE_ADDR and
/// `MBX_PCIE0_CORE_BASE_ADDR + MBX_PCIE0_CORE_SIZE_BYTES`.
pub const MBX_PCIE0_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for cfg device on rv_core_ibex_pwc in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_CORE_IBEX_PWC_CFG_BASE_ADDR: usize = 0x211F0000;

/// Peripheral size for cfg device on rv_core_ibex_pwc in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_CORE_IBEX_PWC_CFG_BASE_ADDR and
/// `RV_CORE_IBEX_PWC_CFG_BASE_ADDR + RV_CORE_IBEX_PWC_CFG_SIZE_BYTES`.
pub const RV_CORE_IBEX_PWC_CFG_SIZE_BYTES: usize = 0x800;

/// Memory base address for ctn in top pwc.
pub const CTN_BASE_ADDR: usize = 0x40000000;

/// Memory size for ctn in top pwc.
pub const CTN_SIZE_BYTES: usize = 0x40000000;

/// Memory base address for ram_ret_aon in top pwc.
pub const RAM_RET_AON_BASE_ADDR: usize = 0x30600000;

/// Memory size for ram_ret_aon in top pwc.
pub const RAM_RET_AON_SIZE_BYTES: usize = 0x1000;

/// Memory base address for ram_main in top pwc.
pub const RAM_MAIN_BASE_ADDR: usize = 0x10000000;

/// Memory size for ram_main in top pwc.
pub const RAM_MAIN_SIZE_BYTES: usize = 0x10000;

/// Memory base address for ram_mbox in top pwc.
pub const RAM_MBOX_BASE_ADDR: usize = 0x11000000;

/// Memory size for ram_mbox in top pwc.
pub const RAM_MBOX_SIZE_BYTES: usize = 0x1000;

/// PLIC Interrupt Source Peripheral.
///
/// Enumeration used to determine which peripheral asserted the corresponding
/// interrupt.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicPeripheral {
    /// Unknown Peripheral
    Unknown = 0,
    /// gpio
    Gpio = 1,
    /// rv_timer
    RvTimer = 2,
    /// aon_timer_aon
    AonTimerAon = 3,
    /// dma
    Dma = 4,
    /// mbx0
    Mbx0 = 5,
    /// mbx1
    Mbx1 = 6,
    /// mbx2
    Mbx2 = 7,
    /// mbx3
    Mbx3 = 8,
    /// mbx4
    Mbx4 = 9,
    /// mbx5
    Mbx5 = 10,
    /// mbx_pcie0
    MbxPcie0 = 11,
    /// racl_ctrl
    RaclCtrl = 12,
    /// ac_range_check
    AcRangeCheck = 13,
}

impl TryFrom<u32> for PlicPeripheral {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::Unknown),
            1 => Ok(Self::Gpio),
            2 => Ok(Self::RvTimer),
            3 => Ok(Self::AonTimerAon),
            4 => Ok(Self::Dma),
            5 => Ok(Self::Mbx0),
            6 => Ok(Self::Mbx1),
            7 => Ok(Self::Mbx2),
            8 => Ok(Self::Mbx3),
            9 => Ok(Self::Mbx4),
            10 => Ok(Self::Mbx5),
            11 => Ok(Self::MbxPcie0),
            12 => Ok(Self::RaclCtrl),
            13 => Ok(Self::AcRangeCheck),
            _ => Err(val),
        }
    }
}

/// PLIC Interrupt Source.
///
/// Enumeration of all PLIC interrupt sources. The interrupt sources belonging to
/// the same peripheral are guaranteed to be consecutive.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicIrqId {
    /// No Interrupt
    None = 0,
    /// gpio_gpio 0
    GpioGpio0 = 1,
    /// gpio_gpio 1
    GpioGpio1 = 2,
    /// gpio_gpio 2
    GpioGpio2 = 3,
    /// gpio_gpio 3
    GpioGpio3 = 4,
    /// gpio_gpio 4
    GpioGpio4 = 5,
    /// gpio_gpio 5
    GpioGpio5 = 6,
    /// gpio_gpio 6
    GpioGpio6 = 7,
    /// gpio_gpio 7
    GpioGpio7 = 8,
    /// gpio_gpio 8
    GpioGpio8 = 9,
    /// gpio_gpio 9
    GpioGpio9 = 10,
    /// gpio_gpio 10
    GpioGpio10 = 11,
    /// gpio_gpio 11
    GpioGpio11 = 12,
    /// gpio_gpio 12
    GpioGpio12 = 13,
    /// gpio_gpio 13
    GpioGpio13 = 14,
    /// gpio_gpio 14
    GpioGpio14 = 15,
    /// gpio_gpio 15
    GpioGpio15 = 16,
    /// gpio_gpio 16
    GpioGpio16 = 17,
    /// gpio_gpio 17
    GpioGpio17 = 18,
    /// gpio_gpio 18
    GpioGpio18 = 19,
    /// gpio_gpio 19
    GpioGpio19 = 20,
    /// gpio_gpio 20
    GpioGpio20 = 21,
    /// gpio_gpio 21
    GpioGpio21 = 22,
    /// gpio_gpio 22
    GpioGpio22 = 23,
    /// gpio_gpio 23
    GpioGpio23 = 24,
    /// gpio_gpio 24
    GpioGpio24 = 25,
    /// gpio_gpio 25
    GpioGpio25 = 26,
    /// gpio_gpio 26
    GpioGpio26 = 27,
    /// gpio_gpio 27
    GpioGpio27 = 28,
    /// gpio_gpio 28
    GpioGpio28 = 29,
    /// gpio_gpio 29
    GpioGpio29 = 30,
    /// gpio_gpio 30
    GpioGpio30 = 31,
    /// gpio_gpio 31
    GpioGpio31 = 32,
    /// rv_timer_timer_expired_hart0_timer0
    RvTimerTimerExpiredHart0Timer0 = 33,
    /// aon_timer_aon_wkup_timer_expired
    AonTimerAonWkupTimerExpired = 34,
    /// aon_timer_aon_wdog_timer_bark
    AonTimerAonWdogTimerBark = 35,
    /// dma_dma_done
    DmaDmaDone = 36,
    /// dma_dma_chunk_done
    DmaDmaChunkDone = 37,
    /// dma_dma_error
    DmaDmaError = 38,
    /// mbx0_mbx_ready
    Mbx0MbxReady = 39,
    /// mbx0_mbx_abort
    Mbx0MbxAbort = 40,
    /// mbx0_mbx_error
    Mbx0MbxError = 41,
    /// mbx1_mbx_ready
    Mbx1MbxReady = 42,
    /// mbx1_mbx_abort
    Mbx1MbxAbort = 43,
    /// mbx1_mbx_error
    Mbx1MbxError = 44,
    /// mbx2_mbx_ready
    Mbx2MbxReady = 45,
    /// mbx2_mbx_abort
    Mbx2MbxAbort = 46,
    /// mbx2_mbx_error
    Mbx2MbxError = 47,
    /// mbx3_mbx_ready
    Mbx3MbxReady = 48,
    /// mbx3_mbx_abort
    Mbx3MbxAbort = 49,
    /// mbx3_mbx_error
    Mbx3MbxError = 50,
    /// mbx4_mbx_ready
    Mbx4MbxReady = 51,
    /// mbx4_mbx_abort
    Mbx4MbxAbort = 52,
    /// mbx4_mbx_error
    Mbx4MbxError = 53,
    /// mbx5_mbx_ready
    Mbx5MbxReady = 54,
    /// mbx5_mbx_abort
    Mbx5MbxAbort = 55,
    /// mbx5_mbx_error
    Mbx5MbxError = 56,
    /// mbx_pcie0_mbx_ready
    MbxPcie0MbxReady = 57,
    /// mbx_pcie0_mbx_abort
    MbxPcie0MbxAbort = 58,
    /// mbx_pcie0_mbx_error
    MbxPcie0MbxError = 59,
    /// racl_ctrl_racl_error
    RaclCtrlRaclError = 60,
    /// ac_range_check_deny_cnt_reached
    AcRangeCheckDenyCntReached = 61,
    /// PWC_LTEU_SOC_HOT
    PwcLteuSocHot = 62,
    /// PWC_LTEU_FW_TRIP
    PwcLteuFwTrip = 63,
    /// PWC_LTEU_CAT_TRIP
    PwcLteuCatTrip = 64,
    /// LIO_GRP_A_IBEX_IRQ
    LioGrpAIbexIrq = 65,
    /// LIO_GRP_B_IBEX_IRQ
    LioGrpBIbexIrq = 66,
    /// LIO_GRP_C_IBEX_IRQ
    LioGrpCIbexIrq = 67,
    /// PWC_DVFS_SocDpaFsmstatus0
    PwcDvfsSocdpafsmstatus0 = 68,
    /// PWC_DVFS_SocDpaFsmstatus1
    PwcDvfsSocdpafsmstatus1 = 69,
    /// PWC_DVFS_SocDpaFsmstatus2
    PwcDvfsSocdpafsmstatus2 = 70,
    /// PWC_DVFS_SocDpaFsmstatus3
    PwcDvfsSocdpafsmstatus3 = 71,
    /// PWC_DVFS_SocDpaFsmstatus4
    PwcDvfsSocdpafsmstatus4 = 72,
    /// PWC_DVFS_TargetCmdAVS0
    PwcDvfsTargetcmdavs0 = 73,
    /// PWC_DVFS_TargetCmdAVS1
    PwcDvfsTargetcmdavs1 = 74,
    /// PWC_DVFS_TargetCmdAVS2
    PwcDvfsTargetcmdavs2 = 75,
    /// PWC_DVFS_TargetCmdAVS3
    PwcDvfsTargetcmdavs3 = 76,
    /// PWC_DVFS_TargetCmdAVS4
    PwcDvfsTargetcmdavs4 = 77,
    /// PWC_DVFS_TargetCmdAVS5
    PwcDvfsTargetcmdavs5 = 78,
    /// PWC_DVFS_TargetCmdAVS6
    PwcDvfsTargetcmdavs6 = 79,
    /// PWC_DVFS_TargetCmdAVS7
    PwcDvfsTargetcmdavs7 = 80,
    /// PWC_DVFS_TargetCmdAVS8
    PwcDvfsTargetcmdavs8 = 81,
    /// PWC_DVFS_TargetCmdAVS9
    PwcDvfsTargetcmdavs9 = 82,
    /// PWC_DVFS_TargetCmdAVS10
    PwcDvfsTargetcmdavs10 = 83,
    /// PWC_DVFS_TargetCmdAVS11
    PwcDvfsTargetcmdavs11 = 84,
    /// PWC_DVFS_TargetCmdAVS12
    PwcDvfsTargetcmdavs12 = 85,
    /// PWC_DVFS_TargetCmdAVS13
    PwcDvfsTargetcmdavs13 = 86,
    /// PWC_AVS_AVS_ERROR_0
    PwcAvsAvsError0 = 87,
    /// PWC_AVS_AVS_ERROR_1
    PwcAvsAvsError1 = 88,
    /// PWC_AVS_AVS_ERROR_2
    PwcAvsAvsError2 = 89,
    /// PWC_AVS_AVS_ERROR_3
    PwcAvsAvsError3 = 90,
    /// PWC_AVS_AVS_ERROR_4
    PwcAvsAvsError4 = 91,
    /// PWC_AVS_AVS_ERROR_5
    PwcAvsAvsError5 = 92,
    /// PWC_AVS_AVS_ERROR_6
    PwcAvsAvsError6 = 93,
    /// PWC_AVS_AVS_ERROR_7
    PwcAvsAvsError7 = 94,
    /// PWC_AVS_AVS_ERROR_8
    PwcAvsAvsError8 = 95,
    /// PWC_AVS_AVS_ERROR_9
    PwcAvsAvsError9 = 96,
    /// PWC_AVS_AVS_ERROR_10
    PwcAvsAvsError10 = 97,
    /// PWC_AVS_AVS_ERROR_11
    PwcAvsAvsError11 = 98,
    /// PWC_AVS_AVS_ERROR_12
    PwcAvsAvsError12 = 99,
    /// PWC_AVS_AVS_ERROR_13
    PwcAvsAvsError13 = 100,
    /// PWC_AVS_AVS_ERROR_14
    PwcAvsAvsError14 = 101,
    /// PWC_AVS_AVS_ERROR_15
    PwcAvsAvsError15 = 102,
    /// PWC_AVS_AVS_ERROR_16
    PwcAvsAvsError16 = 103,
    /// PWC_AVS_AVS_ERROR_17
    PwcAvsAvsError17 = 104,
    /// PWC_AVS_AVS_ERROR_18
    PwcAvsAvsError18 = 105,
    /// PWC_AVS_AVS_ERROR_19
    PwcAvsAvsError19 = 106,
    /// PWC_AVS_AVS_ERROR_20
    PwcAvsAvsError20 = 107,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_0
    PwcAvsAvsResponseToFw0 = 108,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_1
    PwcAvsAvsResponseToFw1 = 109,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_2
    PwcAvsAvsResponseToFw2 = 110,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_3
    PwcAvsAvsResponseToFw3 = 111,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_4
    PwcAvsAvsResponseToFw4 = 112,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_5
    PwcAvsAvsResponseToFw5 = 113,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_6
    PwcAvsAvsResponseToFw6 = 114,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_7
    PwcAvsAvsResponseToFw7 = 115,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_8
    PwcAvsAvsResponseToFw8 = 116,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_9
    PwcAvsAvsResponseToFw9 = 117,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_10
    PwcAvsAvsResponseToFw10 = 118,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_11
    PwcAvsAvsResponseToFw11 = 119,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_12
    PwcAvsAvsResponseToFw12 = 120,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_13
    PwcAvsAvsResponseToFw13 = 121,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_14
    PwcAvsAvsResponseToFw14 = 122,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_15
    PwcAvsAvsResponseToFw15 = 123,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_16
    PwcAvsAvsResponseToFw16 = 124,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_17
    PwcAvsAvsResponseToFw17 = 125,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_18
    PwcAvsAvsResponseToFw18 = 126,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_19
    PwcAvsAvsResponseToFw19 = 127,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_20
    PwcAvsAvsResponseToFw20 = 128,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_21
    PwcAvsAvsResponseToFw21 = 129,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_22
    PwcAvsAvsResponseToFw22 = 130,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_23
    PwcAvsAvsResponseToFw23 = 131,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_24
    PwcAvsAvsResponseToFw24 = 132,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_25
    PwcAvsAvsResponseToFw25 = 133,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_26
    PwcAvsAvsResponseToFw26 = 134,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_27
    PwcAvsAvsResponseToFw27 = 135,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_28
    PwcAvsAvsResponseToFw28 = 136,
    /// PWC_BCAST_C_STATE_ENTRY
    PwcBcastCStateEntry = 137,
    /// PWC_BCAST_C_STATE_EXIT
    PwcBcastCStateExit = 138,
    /// PWC_BCAST_DPA_IDLE_ENTRY
    PwcBcastDpaIdleEntry = 139,
    /// PWC_BCAST_DPA_IDLE_EXIT
    PwcBcastDpaIdleExit = 140,
    /// PWC_CCS_0_PWR_VIRUS_LVL_REQ
    PwcCcs0PwrVirusLvlReq = 141,
    /// PWC_CCS_1_PWR_VIRUS_LVL_REQ
    PwcCcs1PwrVirusLvlReq = 142,
    /// PWC_CCS_2_PWR_VIRUS_LVL_REQ
    PwcCcs2PwrVirusLvlReq = 143,
    /// PWC_CCS_3_PWR_VIRUS_LVL_REQ
    PwcCcs3PwrVirusLvlReq = 144,
    /// PWC_CCS_4_PWR_VIRUS_LVL_REQ
    PwcCcs4PwrVirusLvlReq = 145,
    /// PWC_CCS_5_PWR_VIRUS_LVL_REQ
    PwcCcs5PwrVirusLvlReq = 146,
    /// PWC_CCS_6_PWR_VIRUS_LVL_REQ
    PwcCcs6PwrVirusLvlReq = 147,
    /// PWC_CCS_7_PWR_VIRUS_LVL_REQ
    PwcCcs7PwrVirusLvlReq = 148,
    /// PWC_CCS_0_DVFS_FSM
    PwcCcs0DvfsFsm = 149,
    /// PWC_CCS_1_DVFS_FSM
    PwcCcs1DvfsFsm = 150,
    /// PWC_CCS_2_DVFS_FSM
    PwcCcs2DvfsFsm = 151,
    /// PWC_CCS_3_DVFS_FSM
    PwcCcs3DvfsFsm = 152,
    /// PWC_CCS_4_DVFS_FSM
    PwcCcs4DvfsFsm = 153,
    /// PWC_CCS_5_DVFS_FSM
    PwcCcs5DvfsFsm = 154,
    /// PWC_CCS_6_DVFS_FSM
    PwcCcs6DvfsFsm = 155,
    /// PWC_CCS_7_DVFS_FSM
    PwcCcs7DvfsFsm = 156,
    /// PWC_HMS_East_STATUS
    PwcHmsEastStatus = 157,
    /// PWC_HMS_WEST_STATUS
    PwcHmsWestStatus = 158,
    /// PWC_PCS_0_ALL_PORTS_STATUS
    PwcPcs0AllPortsStatus = 159,
    /// PWC_PCS_0_LINK_BRINGUP_0
    PwcPcs0LinkBringup0 = 160,
    /// PWC_PCS_0_LINK_BRINGUP_1
    PwcPcs0LinkBringup1 = 161,
    /// PWC_PCS_0_LINK_BRINGUP_2
    PwcPcs0LinkBringup2 = 162,
    /// PWC_PCS_0_LINK_BRINGUP_3
    PwcPcs0LinkBringup3 = 163,
    /// PWC_PCS_0_MSG_CTRL
    PwcPcs0MsgCtrl = 164,
    /// PWC_PCS_0_PHY_STATUS
    PwcPcs0PhyStatus = 165,
    /// PWC_PCS_1_ALL_PORTS_STATUS
    PwcPcs1AllPortsStatus = 166,
    /// PWC_PCS_1_LINK_BRINGUP_0
    PwcPcs1LinkBringup0 = 167,
    /// PWC_PCS_1_LINK_BRINGUP_1
    PwcPcs1LinkBringup1 = 168,
    /// PWC_PCS_1_LINK_BRINGUP_2
    PwcPcs1LinkBringup2 = 169,
    /// PWC_PCS_1_LINK_BRINGUP_3
    PwcPcs1LinkBringup3 = 170,
    /// PWC_PCS_1_MSG_CTRL
    PwcPcs1MsgCtrl = 171,
    /// PWC_PCS_1_PHY_STATUS
    PwcPcs1PhyStatus = 172,
    /// PWC_PCS_2_ALL_PORTS_STATUS
    PwcPcs2AllPortsStatus = 173,
    /// PWC_PCS_2_LINK_BRINGUP_0
    PwcPcs2LinkBringup0 = 174,
    /// PWC_PCS_2_LINK_BRINGUP_1
    PwcPcs2LinkBringup1 = 175,
    /// PWC_PCS_2_LINK_BRINGUP_2
    PwcPcs2LinkBringup2 = 176,
    /// PWC_PCS_2_LINK_BRINGUP_3
    PwcPcs2LinkBringup3 = 177,
    /// PWC_PCS_2_MSG_CTRL
    PwcPcs2MsgCtrl = 178,
    /// PWC_PCS_2_PHY_STATUS
    PwcPcs2PhyStatus = 179,
    /// PWC_PCS_3_ALL_PORTS_STATUS
    PwcPcs3AllPortsStatus = 180,
    /// PWC_PCS_3_LINK_BRINGUP_0
    PwcPcs3LinkBringup0 = 181,
    /// PWC_PCS_3_LINK_BRINGUP_1
    PwcPcs3LinkBringup1 = 182,
    /// PWC_PCS_3_LINK_BRINGUP_2
    PwcPcs3LinkBringup2 = 183,
    /// PWC_PCS_3_LINK_BRINGUP_3
    PwcPcs3LinkBringup3 = 184,
    /// PWC_PCS_3_MSG_CTRL
    PwcPcs3MsgCtrl = 185,
    /// PWC_PCS_3_PHY_STATUS
    PwcPcs3PhyStatus = 186,
    /// PWC_PCS_4_ALL_PORTS_STATUS
    PwcPcs4AllPortsStatus = 187,
    /// PWC_PCS_4_LINK_BRINGUP_0
    PwcPcs4LinkBringup0 = 188,
    /// PWC_PCS_4_LINK_BRINGUP_1
    PwcPcs4LinkBringup1 = 189,
    /// PWC_PCS_4_LINK_BRINGUP_2
    PwcPcs4LinkBringup2 = 190,
    /// PWC_PCS_4_LINK_BRINGUP_3
    PwcPcs4LinkBringup3 = 191,
    /// PWC_PCS_4_MSG_CTRL
    PwcPcs4MsgCtrl = 192,
    /// PWC_PCS_4_PHY_STATUS
    PwcPcs4PhyStatus = 193,
    /// PWC_PCS_5_ALL_PORTS_STATUS
    PwcPcs5AllPortsStatus = 194,
    /// PWC_PCS_5_LINK_BRINGUP_0
    PwcPcs5LinkBringup0 = 195,
    /// PWC_PCS_5_LINK_BRINGUP_1
    PwcPcs5LinkBringup1 = 196,
    /// PWC_PCS_5_LINK_BRINGUP_2
    PwcPcs5LinkBringup2 = 197,
    /// PWC_PCS_5_LINK_BRINGUP_3
    PwcPcs5LinkBringup3 = 198,
    /// PWC_PCS_5_MSG_CTRL
    PwcPcs5MsgCtrl = 199,
    /// PWC_PCS_5_PHY_STATUS
    PwcPcs5PhyStatus = 200,
    /// PWC_PCS_6_ALL_PORTS_STATUS
    PwcPcs6AllPortsStatus = 201,
    /// PWC_PCS_6_LINK_BRINGUP_0
    PwcPcs6LinkBringup0 = 202,
    /// PWC_PCS_6_LINK_BRINGUP_1
    PwcPcs6LinkBringup1 = 203,
    /// PWC_PCS_6_LINK_BRINGUP_2
    PwcPcs6LinkBringup2 = 204,
    /// PWC_PCS_6_LINK_BRINGUP_3
    PwcPcs6LinkBringup3 = 205,
    /// PWC_PCS_6_MSG_CTRL
    PwcPcs6MsgCtrl = 206,
    /// PWC_PCS_6_PHY_STATUS
    PwcPcs6PhyStatus = 207,
    /// PWC_PCS_7_ALL_PORTS_STATUS
    PwcPcs7AllPortsStatus = 208,
    /// PWC_PCS_7_LINK_BRINGUP_0
    PwcPcs7LinkBringup0 = 209,
    /// PWC_PCS_7_LINK_BRINGUP_1
    PwcPcs7LinkBringup1 = 210,
    /// PWC_PCS_7_LINK_BRINGUP_2
    PwcPcs7LinkBringup2 = 211,
    /// PWC_PCS_7_LINK_BRINGUP_3
    PwcPcs7LinkBringup3 = 212,
    /// PWC_PCS_7_MSG_CTRL
    PwcPcs7MsgCtrl = 213,
    /// PWC_PCS_7_PHY_STATUS
    PwcPcs7PhyStatus = 214,
    /// PWC_HDR_IPI_FROM_PWC_0
    PwcHdrIpiFromPwc0 = 215,
    /// PWC_HDR_IPI_FROM_PWC_1
    PwcHdrIpiFromPwc1 = 216,
    /// PWC_HDR_IPI_FROM_PWC_2
    PwcHdrIpiFromPwc2 = 217,
    /// PWC_HDR_IPI_FROM_ROT
    PwcHdrIpiFromRot = 218,
    /// PWC_HDR_IPI_FROM_MIO
    PwcHdrIpiFromMio = 219,
    /// PWC_HDR_IPI_FROM_DUC
    PwcHdrIpiFromDuc = 220,
    /// LIO_GRP_A_IPI_FROM_LIOGRPA_I3C0_PERIPH_RST_REQ
    LioGrpAIpiFromLiogrpaI3c0PeriphRstReq = 221,
    /// LIO_GRP_A_IPI_FROM_LIOGRPA_I3C0_CHIP_RST_REQ
    LioGrpAIpiFromLiogrpaI3c0ChipRstReq = 222,
    /// LIO_GRP_A_IPI_FROM_LIOGRPA_I3C1_PERIPH_RST_REQ
    LioGrpAIpiFromLiogrpaI3c1PeriphRstReq = 223,
    /// LIO_GRP_A_IPI_FROM_LIOGRPA_I3C1_CHIP_RST_REQ
    LioGrpAIpiFromLiogrpaI3c1ChipRstReq = 224,
    /// LIO_GRP_A_IPI_FROM_LIOGRPA_I3C2_PERIPH_RST_REQ
    LioGrpAIpiFromLiogrpaI3c2PeriphRstReq = 225,
    /// LIO_GRP_A_IPI_FROM_LIOGRPA_I3C2_CHIP_RST_REQ
    LioGrpAIpiFromLiogrpaI3c2ChipRstReq = 226,
    /// LIO_GRP_B_IPI_FROM_LIOGRPB_I3C0_PERIPH_RST_REQ
    LioGrpBIpiFromLiogrpbI3c0PeriphRstReq = 227,
    /// LIO_GRP_B_IPI_FROM_LIOGRPB_I3C0_CHIP_RST_REQ
    LioGrpBIpiFromLiogrpbI3c0ChipRstReq = 228,
    /// LIO_GRP_B_IPI_FROM_LIOGRPB_I3C1_PERIPH_RST_REQ
    LioGrpBIpiFromLiogrpbI3c1PeriphRstReq = 229,
    /// LIO_GRP_B_IPI_FROM_LIOGRPB_I3C1_CHIP_RST_REQ
    LioGrpBIpiFromLiogrpbI3c1ChipRstReq = 230,
    /// LIO_GRP_B_IPI_FROM_LIOGRPB_I3C2_PERIPH_RST_REQ
    LioGrpBIpiFromLiogrpbI3c2PeriphRstReq = 231,
    /// LIO_GRP_B_IPI_FROM_LIOGRPB_I3C2_CHIP_RST_REQ
    LioGrpBIpiFromLiogrpbI3c2ChipRstReq = 232,
    /// LIO_GRP_C_IPI_FROM_LIOGRPC_I3C0_PERIPH_RST_REQ
    LioGrpCIpiFromLiogrpcI3c0PeriphRstReq = 233,
    /// LIO_GRP_C_IPI_FROM_LIOGRPC_I3C0_CHIP_RST_REQ
    LioGrpCIpiFromLiogrpcI3c0ChipRstReq = 234,
    /// LIO_GRP_C_IPI_FROM_LIOGRPC_I3C1_PERIPH_RST_REQ
    LioGrpCIpiFromLiogrpcI3c1PeriphRstReq = 235,
    /// LIO_GRP_C_IPI_FROM_LIOGRPC_I3C1_CHIP_RST_REQ
    LioGrpCIpiFromLiogrpcI3c1ChipRstReq = 236,
    /// LIO_GRP_C_IPI_FROM_LIOGRPC_I3C2_PERIPH_RST_REQ
    LioGrpCIpiFromLiogrpcI3c2PeriphRstReq = 237,
    /// LIO_GRP_C_IPI_FROM_LIOGRPC_I3C2_CHIP_RST_REQ
    LioGrpCIpiFromLiogrpcI3c2ChipRstReq = 238,
    /// LIO_GRP_D_IPI_FROM_LIOGRPD_I3C0_PERIPH_RST_REQ
    LioGrpDIpiFromLiogrpdI3c0PeriphRstReq = 239,
    /// LIO_GRP_D_IPI_FROM_LIOGRPD_I3C0_CHIP_RST_REQ
    LioGrpDIpiFromLiogrpdI3c0ChipRstReq = 240,
    /// LIO_GRP_D_IPI_FROM_LIOGRPD_I3C1_PERIPH_RST_REQ
    LioGrpDIpiFromLiogrpdI3c1PeriphRstReq = 241,
    /// LIO_GRP_D_IPI_FROM_LIOGRPD_I3C1_CHIP_RST_REQ
    LioGrpDIpiFromLiogrpdI3c1ChipRstReq = 242,
    /// LIO_GRP_D_IPI_FROM_LIOGRPD_I3C2_PERIPH_RST_REQ
    LioGrpDIpiFromLiogrpdI3c2PeriphRstReq = 243,
    /// LIO_GRP_D_IPI_FROM_LIOGRPD_I3C2_CHIP_RST_REQ
    LioGrpDIpiFromLiogrpdI3c2ChipRstReq = 244,
}

impl TryFrom<u32> for PlicIrqId {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::None),
            1 => Ok(Self::GpioGpio0),
            2 => Ok(Self::GpioGpio1),
            3 => Ok(Self::GpioGpio2),
            4 => Ok(Self::GpioGpio3),
            5 => Ok(Self::GpioGpio4),
            6 => Ok(Self::GpioGpio5),
            7 => Ok(Self::GpioGpio6),
            8 => Ok(Self::GpioGpio7),
            9 => Ok(Self::GpioGpio8),
            10 => Ok(Self::GpioGpio9),
            11 => Ok(Self::GpioGpio10),
            12 => Ok(Self::GpioGpio11),
            13 => Ok(Self::GpioGpio12),
            14 => Ok(Self::GpioGpio13),
            15 => Ok(Self::GpioGpio14),
            16 => Ok(Self::GpioGpio15),
            17 => Ok(Self::GpioGpio16),
            18 => Ok(Self::GpioGpio17),
            19 => Ok(Self::GpioGpio18),
            20 => Ok(Self::GpioGpio19),
            21 => Ok(Self::GpioGpio20),
            22 => Ok(Self::GpioGpio21),
            23 => Ok(Self::GpioGpio22),
            24 => Ok(Self::GpioGpio23),
            25 => Ok(Self::GpioGpio24),
            26 => Ok(Self::GpioGpio25),
            27 => Ok(Self::GpioGpio26),
            28 => Ok(Self::GpioGpio27),
            29 => Ok(Self::GpioGpio28),
            30 => Ok(Self::GpioGpio29),
            31 => Ok(Self::GpioGpio30),
            32 => Ok(Self::GpioGpio31),
            33 => Ok(Self::RvTimerTimerExpiredHart0Timer0),
            34 => Ok(Self::AonTimerAonWkupTimerExpired),
            35 => Ok(Self::AonTimerAonWdogTimerBark),
            36 => Ok(Self::DmaDmaDone),
            37 => Ok(Self::DmaDmaChunkDone),
            38 => Ok(Self::DmaDmaError),
            39 => Ok(Self::Mbx0MbxReady),
            40 => Ok(Self::Mbx0MbxAbort),
            41 => Ok(Self::Mbx0MbxError),
            42 => Ok(Self::Mbx1MbxReady),
            43 => Ok(Self::Mbx1MbxAbort),
            44 => Ok(Self::Mbx1MbxError),
            45 => Ok(Self::Mbx2MbxReady),
            46 => Ok(Self::Mbx2MbxAbort),
            47 => Ok(Self::Mbx2MbxError),
            48 => Ok(Self::Mbx3MbxReady),
            49 => Ok(Self::Mbx3MbxAbort),
            50 => Ok(Self::Mbx3MbxError),
            51 => Ok(Self::Mbx4MbxReady),
            52 => Ok(Self::Mbx4MbxAbort),
            53 => Ok(Self::Mbx4MbxError),
            54 => Ok(Self::Mbx5MbxReady),
            55 => Ok(Self::Mbx5MbxAbort),
            56 => Ok(Self::Mbx5MbxError),
            57 => Ok(Self::MbxPcie0MbxReady),
            58 => Ok(Self::MbxPcie0MbxAbort),
            59 => Ok(Self::MbxPcie0MbxError),
            60 => Ok(Self::RaclCtrlRaclError),
            61 => Ok(Self::AcRangeCheckDenyCntReached),
            62 => Ok(Self::PwcLteuSocHot),
            63 => Ok(Self::PwcLteuFwTrip),
            64 => Ok(Self::PwcLteuCatTrip),
            65 => Ok(Self::LioGrpAIbexIrq),
            66 => Ok(Self::LioGrpBIbexIrq),
            67 => Ok(Self::LioGrpCIbexIrq),
            68 => Ok(Self::PwcDvfsSocdpafsmstatus0),
            69 => Ok(Self::PwcDvfsSocdpafsmstatus1),
            70 => Ok(Self::PwcDvfsSocdpafsmstatus2),
            71 => Ok(Self::PwcDvfsSocdpafsmstatus3),
            72 => Ok(Self::PwcDvfsSocdpafsmstatus4),
            73 => Ok(Self::PwcDvfsTargetcmdavs0),
            74 => Ok(Self::PwcDvfsTargetcmdavs1),
            75 => Ok(Self::PwcDvfsTargetcmdavs2),
            76 => Ok(Self::PwcDvfsTargetcmdavs3),
            77 => Ok(Self::PwcDvfsTargetcmdavs4),
            78 => Ok(Self::PwcDvfsTargetcmdavs5),
            79 => Ok(Self::PwcDvfsTargetcmdavs6),
            80 => Ok(Self::PwcDvfsTargetcmdavs7),
            81 => Ok(Self::PwcDvfsTargetcmdavs8),
            82 => Ok(Self::PwcDvfsTargetcmdavs9),
            83 => Ok(Self::PwcDvfsTargetcmdavs10),
            84 => Ok(Self::PwcDvfsTargetcmdavs11),
            85 => Ok(Self::PwcDvfsTargetcmdavs12),
            86 => Ok(Self::PwcDvfsTargetcmdavs13),
            87 => Ok(Self::PwcAvsAvsError0),
            88 => Ok(Self::PwcAvsAvsError1),
            89 => Ok(Self::PwcAvsAvsError2),
            90 => Ok(Self::PwcAvsAvsError3),
            91 => Ok(Self::PwcAvsAvsError4),
            92 => Ok(Self::PwcAvsAvsError5),
            93 => Ok(Self::PwcAvsAvsError6),
            94 => Ok(Self::PwcAvsAvsError7),
            95 => Ok(Self::PwcAvsAvsError8),
            96 => Ok(Self::PwcAvsAvsError9),
            97 => Ok(Self::PwcAvsAvsError10),
            98 => Ok(Self::PwcAvsAvsError11),
            99 => Ok(Self::PwcAvsAvsError12),
            100 => Ok(Self::PwcAvsAvsError13),
            101 => Ok(Self::PwcAvsAvsError14),
            102 => Ok(Self::PwcAvsAvsError15),
            103 => Ok(Self::PwcAvsAvsError16),
            104 => Ok(Self::PwcAvsAvsError17),
            105 => Ok(Self::PwcAvsAvsError18),
            106 => Ok(Self::PwcAvsAvsError19),
            107 => Ok(Self::PwcAvsAvsError20),
            108 => Ok(Self::PwcAvsAvsResponseToFw0),
            109 => Ok(Self::PwcAvsAvsResponseToFw1),
            110 => Ok(Self::PwcAvsAvsResponseToFw2),
            111 => Ok(Self::PwcAvsAvsResponseToFw3),
            112 => Ok(Self::PwcAvsAvsResponseToFw4),
            113 => Ok(Self::PwcAvsAvsResponseToFw5),
            114 => Ok(Self::PwcAvsAvsResponseToFw6),
            115 => Ok(Self::PwcAvsAvsResponseToFw7),
            116 => Ok(Self::PwcAvsAvsResponseToFw8),
            117 => Ok(Self::PwcAvsAvsResponseToFw9),
            118 => Ok(Self::PwcAvsAvsResponseToFw10),
            119 => Ok(Self::PwcAvsAvsResponseToFw11),
            120 => Ok(Self::PwcAvsAvsResponseToFw12),
            121 => Ok(Self::PwcAvsAvsResponseToFw13),
            122 => Ok(Self::PwcAvsAvsResponseToFw14),
            123 => Ok(Self::PwcAvsAvsResponseToFw15),
            124 => Ok(Self::PwcAvsAvsResponseToFw16),
            125 => Ok(Self::PwcAvsAvsResponseToFw17),
            126 => Ok(Self::PwcAvsAvsResponseToFw18),
            127 => Ok(Self::PwcAvsAvsResponseToFw19),
            128 => Ok(Self::PwcAvsAvsResponseToFw20),
            129 => Ok(Self::PwcAvsAvsResponseToFw21),
            130 => Ok(Self::PwcAvsAvsResponseToFw22),
            131 => Ok(Self::PwcAvsAvsResponseToFw23),
            132 => Ok(Self::PwcAvsAvsResponseToFw24),
            133 => Ok(Self::PwcAvsAvsResponseToFw25),
            134 => Ok(Self::PwcAvsAvsResponseToFw26),
            135 => Ok(Self::PwcAvsAvsResponseToFw27),
            136 => Ok(Self::PwcAvsAvsResponseToFw28),
            137 => Ok(Self::PwcBcastCStateEntry),
            138 => Ok(Self::PwcBcastCStateExit),
            139 => Ok(Self::PwcBcastDpaIdleEntry),
            140 => Ok(Self::PwcBcastDpaIdleExit),
            141 => Ok(Self::PwcCcs0PwrVirusLvlReq),
            142 => Ok(Self::PwcCcs1PwrVirusLvlReq),
            143 => Ok(Self::PwcCcs2PwrVirusLvlReq),
            144 => Ok(Self::PwcCcs3PwrVirusLvlReq),
            145 => Ok(Self::PwcCcs4PwrVirusLvlReq),
            146 => Ok(Self::PwcCcs5PwrVirusLvlReq),
            147 => Ok(Self::PwcCcs6PwrVirusLvlReq),
            148 => Ok(Self::PwcCcs7PwrVirusLvlReq),
            149 => Ok(Self::PwcCcs0DvfsFsm),
            150 => Ok(Self::PwcCcs1DvfsFsm),
            151 => Ok(Self::PwcCcs2DvfsFsm),
            152 => Ok(Self::PwcCcs3DvfsFsm),
            153 => Ok(Self::PwcCcs4DvfsFsm),
            154 => Ok(Self::PwcCcs5DvfsFsm),
            155 => Ok(Self::PwcCcs6DvfsFsm),
            156 => Ok(Self::PwcCcs7DvfsFsm),
            157 => Ok(Self::PwcHmsEastStatus),
            158 => Ok(Self::PwcHmsWestStatus),
            159 => Ok(Self::PwcPcs0AllPortsStatus),
            160 => Ok(Self::PwcPcs0LinkBringup0),
            161 => Ok(Self::PwcPcs0LinkBringup1),
            162 => Ok(Self::PwcPcs0LinkBringup2),
            163 => Ok(Self::PwcPcs0LinkBringup3),
            164 => Ok(Self::PwcPcs0MsgCtrl),
            165 => Ok(Self::PwcPcs0PhyStatus),
            166 => Ok(Self::PwcPcs1AllPortsStatus),
            167 => Ok(Self::PwcPcs1LinkBringup0),
            168 => Ok(Self::PwcPcs1LinkBringup1),
            169 => Ok(Self::PwcPcs1LinkBringup2),
            170 => Ok(Self::PwcPcs1LinkBringup3),
            171 => Ok(Self::PwcPcs1MsgCtrl),
            172 => Ok(Self::PwcPcs1PhyStatus),
            173 => Ok(Self::PwcPcs2AllPortsStatus),
            174 => Ok(Self::PwcPcs2LinkBringup0),
            175 => Ok(Self::PwcPcs2LinkBringup1),
            176 => Ok(Self::PwcPcs2LinkBringup2),
            177 => Ok(Self::PwcPcs2LinkBringup3),
            178 => Ok(Self::PwcPcs2MsgCtrl),
            179 => Ok(Self::PwcPcs2PhyStatus),
            180 => Ok(Self::PwcPcs3AllPortsStatus),
            181 => Ok(Self::PwcPcs3LinkBringup0),
            182 => Ok(Self::PwcPcs3LinkBringup1),
            183 => Ok(Self::PwcPcs3LinkBringup2),
            184 => Ok(Self::PwcPcs3LinkBringup3),
            185 => Ok(Self::PwcPcs3MsgCtrl),
            186 => Ok(Self::PwcPcs3PhyStatus),
            187 => Ok(Self::PwcPcs4AllPortsStatus),
            188 => Ok(Self::PwcPcs4LinkBringup0),
            189 => Ok(Self::PwcPcs4LinkBringup1),
            190 => Ok(Self::PwcPcs4LinkBringup2),
            191 => Ok(Self::PwcPcs4LinkBringup3),
            192 => Ok(Self::PwcPcs4MsgCtrl),
            193 => Ok(Self::PwcPcs4PhyStatus),
            194 => Ok(Self::PwcPcs5AllPortsStatus),
            195 => Ok(Self::PwcPcs5LinkBringup0),
            196 => Ok(Self::PwcPcs5LinkBringup1),
            197 => Ok(Self::PwcPcs5LinkBringup2),
            198 => Ok(Self::PwcPcs5LinkBringup3),
            199 => Ok(Self::PwcPcs5MsgCtrl),
            200 => Ok(Self::PwcPcs5PhyStatus),
            201 => Ok(Self::PwcPcs6AllPortsStatus),
            202 => Ok(Self::PwcPcs6LinkBringup0),
            203 => Ok(Self::PwcPcs6LinkBringup1),
            204 => Ok(Self::PwcPcs6LinkBringup2),
            205 => Ok(Self::PwcPcs6LinkBringup3),
            206 => Ok(Self::PwcPcs6MsgCtrl),
            207 => Ok(Self::PwcPcs6PhyStatus),
            208 => Ok(Self::PwcPcs7AllPortsStatus),
            209 => Ok(Self::PwcPcs7LinkBringup0),
            210 => Ok(Self::PwcPcs7LinkBringup1),
            211 => Ok(Self::PwcPcs7LinkBringup2),
            212 => Ok(Self::PwcPcs7LinkBringup3),
            213 => Ok(Self::PwcPcs7MsgCtrl),
            214 => Ok(Self::PwcPcs7PhyStatus),
            215 => Ok(Self::PwcHdrIpiFromPwc0),
            216 => Ok(Self::PwcHdrIpiFromPwc1),
            217 => Ok(Self::PwcHdrIpiFromPwc2),
            218 => Ok(Self::PwcHdrIpiFromRot),
            219 => Ok(Self::PwcHdrIpiFromMio),
            220 => Ok(Self::PwcHdrIpiFromDuc),
            221 => Ok(Self::LioGrpAIpiFromLiogrpaI3c0PeriphRstReq),
            222 => Ok(Self::LioGrpAIpiFromLiogrpaI3c0ChipRstReq),
            223 => Ok(Self::LioGrpAIpiFromLiogrpaI3c1PeriphRstReq),
            224 => Ok(Self::LioGrpAIpiFromLiogrpaI3c1ChipRstReq),
            225 => Ok(Self::LioGrpAIpiFromLiogrpaI3c2PeriphRstReq),
            226 => Ok(Self::LioGrpAIpiFromLiogrpaI3c2ChipRstReq),
            227 => Ok(Self::LioGrpBIpiFromLiogrpbI3c0PeriphRstReq),
            228 => Ok(Self::LioGrpBIpiFromLiogrpbI3c0ChipRstReq),
            229 => Ok(Self::LioGrpBIpiFromLiogrpbI3c1PeriphRstReq),
            230 => Ok(Self::LioGrpBIpiFromLiogrpbI3c1ChipRstReq),
            231 => Ok(Self::LioGrpBIpiFromLiogrpbI3c2PeriphRstReq),
            232 => Ok(Self::LioGrpBIpiFromLiogrpbI3c2ChipRstReq),
            233 => Ok(Self::LioGrpCIpiFromLiogrpcI3c0PeriphRstReq),
            234 => Ok(Self::LioGrpCIpiFromLiogrpcI3c0ChipRstReq),
            235 => Ok(Self::LioGrpCIpiFromLiogrpcI3c1PeriphRstReq),
            236 => Ok(Self::LioGrpCIpiFromLiogrpcI3c1ChipRstReq),
            237 => Ok(Self::LioGrpCIpiFromLiogrpcI3c2PeriphRstReq),
            238 => Ok(Self::LioGrpCIpiFromLiogrpcI3c2ChipRstReq),
            239 => Ok(Self::LioGrpDIpiFromLiogrpdI3c0PeriphRstReq),
            240 => Ok(Self::LioGrpDIpiFromLiogrpdI3c0ChipRstReq),
            241 => Ok(Self::LioGrpDIpiFromLiogrpdI3c1PeriphRstReq),
            242 => Ok(Self::LioGrpDIpiFromLiogrpdI3c1ChipRstReq),
            243 => Ok(Self::LioGrpDIpiFromLiogrpdI3c2PeriphRstReq),
            244 => Ok(Self::LioGrpDIpiFromLiogrpdI3c2ChipRstReq),
            _ => Err(val),
        }
    }
}

/// PLIC Interrupt Target.
///
/// Enumeration used to determine which set of IE, CC, threshold registers to
/// access for a given interrupt target.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicTarget {
    /// Ibex Core 0
    Ibex0 = 0,
}

/// PLIC Interrupt Source to Peripheral Map
///
/// This array is a mapping from `PlicIrqId` to
/// `PlicPeripheral`.
pub const PLIC_INTERRUPT_FOR_PERIPHERAL: [PlicPeripheral; 245] = [
    // None -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // GpioGpio0 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio1 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio2 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio3 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio4 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio5 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio6 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio7 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio8 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio9 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio10 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio11 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio12 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio13 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio14 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio15 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio16 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio17 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio18 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio19 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio20 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio21 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio22 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio23 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio24 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio25 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio26 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio27 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio28 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio29 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio30 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio31 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // RvTimerTimerExpiredHart0Timer0 -> PlicPeripheral::RvTimer
    PlicPeripheral::RvTimer,
    // AonTimerAonWkupTimerExpired -> PlicPeripheral::AonTimerAon
    PlicPeripheral::AonTimerAon,
    // AonTimerAonWdogTimerBark -> PlicPeripheral::AonTimerAon
    PlicPeripheral::AonTimerAon,
    // DmaDmaDone -> PlicPeripheral::Dma
    PlicPeripheral::Dma,
    // DmaDmaChunkDone -> PlicPeripheral::Dma
    PlicPeripheral::Dma,
    // DmaDmaError -> PlicPeripheral::Dma
    PlicPeripheral::Dma,
    // Mbx0MbxReady -> PlicPeripheral::Mbx0
    PlicPeripheral::Mbx0,
    // Mbx0MbxAbort -> PlicPeripheral::Mbx0
    PlicPeripheral::Mbx0,
    // Mbx0MbxError -> PlicPeripheral::Mbx0
    PlicPeripheral::Mbx0,
    // Mbx1MbxReady -> PlicPeripheral::Mbx1
    PlicPeripheral::Mbx1,
    // Mbx1MbxAbort -> PlicPeripheral::Mbx1
    PlicPeripheral::Mbx1,
    // Mbx1MbxError -> PlicPeripheral::Mbx1
    PlicPeripheral::Mbx1,
    // Mbx2MbxReady -> PlicPeripheral::Mbx2
    PlicPeripheral::Mbx2,
    // Mbx2MbxAbort -> PlicPeripheral::Mbx2
    PlicPeripheral::Mbx2,
    // Mbx2MbxError -> PlicPeripheral::Mbx2
    PlicPeripheral::Mbx2,
    // Mbx3MbxReady -> PlicPeripheral::Mbx3
    PlicPeripheral::Mbx3,
    // Mbx3MbxAbort -> PlicPeripheral::Mbx3
    PlicPeripheral::Mbx3,
    // Mbx3MbxError -> PlicPeripheral::Mbx3
    PlicPeripheral::Mbx3,
    // Mbx4MbxReady -> PlicPeripheral::Mbx4
    PlicPeripheral::Mbx4,
    // Mbx4MbxAbort -> PlicPeripheral::Mbx4
    PlicPeripheral::Mbx4,
    // Mbx4MbxError -> PlicPeripheral::Mbx4
    PlicPeripheral::Mbx4,
    // Mbx5MbxReady -> PlicPeripheral::Mbx5
    PlicPeripheral::Mbx5,
    // Mbx5MbxAbort -> PlicPeripheral::Mbx5
    PlicPeripheral::Mbx5,
    // Mbx5MbxError -> PlicPeripheral::Mbx5
    PlicPeripheral::Mbx5,
    // MbxPcie0MbxReady -> PlicPeripheral::MbxPcie0
    PlicPeripheral::MbxPcie0,
    // MbxPcie0MbxAbort -> PlicPeripheral::MbxPcie0
    PlicPeripheral::MbxPcie0,
    // MbxPcie0MbxError -> PlicPeripheral::MbxPcie0
    PlicPeripheral::MbxPcie0,
    // RaclCtrlRaclError -> PlicPeripheral::RaclCtrl
    PlicPeripheral::RaclCtrl,
    // AcRangeCheckDenyCntReached -> PlicPeripheral::AcRangeCheck
    PlicPeripheral::AcRangeCheck,
    // PwcLteuSocHot -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcLteuFwTrip -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcLteuCatTrip -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpAIbexIrq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpBIbexIrq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpCIbexIrq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcDvfsSocdpafsmstatus0 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcDvfsSocdpafsmstatus1 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcDvfsSocdpafsmstatus2 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcDvfsSocdpafsmstatus3 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcDvfsSocdpafsmstatus4 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcDvfsTargetcmdavs0 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcDvfsTargetcmdavs1 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcDvfsTargetcmdavs2 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcDvfsTargetcmdavs3 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcDvfsTargetcmdavs4 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcDvfsTargetcmdavs5 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcDvfsTargetcmdavs6 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcDvfsTargetcmdavs7 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcDvfsTargetcmdavs8 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcDvfsTargetcmdavs9 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcDvfsTargetcmdavs10 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcDvfsTargetcmdavs11 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcDvfsTargetcmdavs12 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcDvfsTargetcmdavs13 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError0 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError1 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError2 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError3 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError4 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError5 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError6 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError7 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError8 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError9 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError10 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError11 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError12 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError13 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError14 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError15 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError16 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError17 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError18 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError19 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsError20 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw0 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw1 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw2 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw3 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw4 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw5 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw6 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw7 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw8 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw9 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw10 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw11 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw12 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw13 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw14 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw15 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw16 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw17 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw18 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw19 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw20 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw21 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw22 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw23 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw24 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw25 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw26 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw27 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcAvsAvsResponseToFw28 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcBcastCStateEntry -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcBcastCStateExit -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcBcastDpaIdleEntry -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcBcastDpaIdleExit -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcCcs0PwrVirusLvlReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcCcs1PwrVirusLvlReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcCcs2PwrVirusLvlReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcCcs3PwrVirusLvlReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcCcs4PwrVirusLvlReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcCcs5PwrVirusLvlReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcCcs6PwrVirusLvlReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcCcs7PwrVirusLvlReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcCcs0DvfsFsm -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcCcs1DvfsFsm -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcCcs2DvfsFsm -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcCcs3DvfsFsm -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcCcs4DvfsFsm -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcCcs5DvfsFsm -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcCcs6DvfsFsm -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcCcs7DvfsFsm -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcHmsEastStatus -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcHmsWestStatus -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs0AllPortsStatus -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs0LinkBringup0 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs0LinkBringup1 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs0LinkBringup2 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs0LinkBringup3 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs0MsgCtrl -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs0PhyStatus -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs1AllPortsStatus -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs1LinkBringup0 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs1LinkBringup1 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs1LinkBringup2 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs1LinkBringup3 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs1MsgCtrl -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs1PhyStatus -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs2AllPortsStatus -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs2LinkBringup0 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs2LinkBringup1 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs2LinkBringup2 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs2LinkBringup3 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs2MsgCtrl -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs2PhyStatus -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs3AllPortsStatus -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs3LinkBringup0 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs3LinkBringup1 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs3LinkBringup2 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs3LinkBringup3 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs3MsgCtrl -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs3PhyStatus -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs4AllPortsStatus -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs4LinkBringup0 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs4LinkBringup1 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs4LinkBringup2 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs4LinkBringup3 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs4MsgCtrl -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs4PhyStatus -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs5AllPortsStatus -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs5LinkBringup0 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs5LinkBringup1 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs5LinkBringup2 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs5LinkBringup3 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs5MsgCtrl -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs5PhyStatus -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs6AllPortsStatus -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs6LinkBringup0 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs6LinkBringup1 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs6LinkBringup2 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs6LinkBringup3 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs6MsgCtrl -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs6PhyStatus -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs7AllPortsStatus -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs7LinkBringup0 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs7LinkBringup1 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs7LinkBringup2 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs7LinkBringup3 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs7MsgCtrl -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcPcs7PhyStatus -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcHdrIpiFromPwc0 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcHdrIpiFromPwc1 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcHdrIpiFromPwc2 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcHdrIpiFromRot -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcHdrIpiFromMio -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwcHdrIpiFromDuc -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpAIpiFromLiogrpaI3c0PeriphRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpAIpiFromLiogrpaI3c0ChipRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpAIpiFromLiogrpaI3c1PeriphRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpAIpiFromLiogrpaI3c1ChipRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpAIpiFromLiogrpaI3c2PeriphRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpAIpiFromLiogrpaI3c2ChipRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpBIpiFromLiogrpbI3c0PeriphRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpBIpiFromLiogrpbI3c0ChipRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpBIpiFromLiogrpbI3c1PeriphRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpBIpiFromLiogrpbI3c1ChipRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpBIpiFromLiogrpbI3c2PeriphRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpBIpiFromLiogrpbI3c2ChipRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpCIpiFromLiogrpcI3c0PeriphRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpCIpiFromLiogrpcI3c0ChipRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpCIpiFromLiogrpcI3c1PeriphRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpCIpiFromLiogrpcI3c1ChipRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpCIpiFromLiogrpcI3c2PeriphRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpCIpiFromLiogrpcI3c2ChipRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpDIpiFromLiogrpdI3c0PeriphRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpDIpiFromLiogrpdI3c0ChipRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpDIpiFromLiogrpdI3c1PeriphRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpDIpiFromLiogrpdI3c1ChipRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpDIpiFromLiogrpdI3c2PeriphRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // LioGrpDIpiFromLiogrpdI3c2ChipRstReq -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
];

/// MPWC Region
///
/// MMIO region excludes any memory that is separate from the module
/// configuration space, i.e. ROM, main SRAM, and mbx SRAM are excluded but
/// retention SRAM or spi_device are included.
pub const TOP_PWC_MPWC_BASE_ADDR: usize = 0x211C0000;
pub const TOP_PWC_MPWC_SIZE_BYTES: usize = 0xF441000;
