// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// This file was generated automatically.
// Please do not modify content of this file directly.
// File generated by using template: "toplevel.rs.tpl"
// To regenerate this file follow OpenTitan topgen documentations.

#![allow(dead_code)]

//! This file contains enums and consts for use within the Rust codebase.
//!
//! These definitions are for information that depends on the top-specific chip
//! configuration, which includes:
//! - Device Memory Information (for Peripherals and Memory)
//! - PLIC Interrupt ID Names and Source Mappings
//! - Alert ID Names and Source Mappings

use core::convert::TryFrom;

/// Peripheral base address for gpio in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const GPIO_BASE_ADDR: usize = 0x30000000;

/// Peripheral size for gpio in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #GPIO_BASE_ADDR and
/// `GPIO_BASE_ADDR + GPIO_SIZE_BYTES`.
pub const GPIO_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for rv_timer in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_TIMER_BASE_ADDR: usize = 0x30100000;

/// Peripheral size for rv_timer in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_TIMER_BASE_ADDR and
/// `RV_TIMER_BASE_ADDR + RV_TIMER_SIZE_BYTES`.
pub const RV_TIMER_SIZE_BYTES: usize = 0x200;

/// Peripheral base address for aon_timer_aon in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const AON_TIMER_AON_BASE_ADDR: usize = 0x30470000;

/// Peripheral size for aon_timer_aon in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #AON_TIMER_AON_BASE_ADDR and
/// `AON_TIMER_AON_BASE_ADDR + AON_TIMER_AON_SIZE_BYTES`.
pub const AON_TIMER_AON_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for regs device on sram_ctrl_ret_aon in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_RET_AON_REGS_BASE_ADDR: usize = 0x30500000;

/// Peripheral size for regs device on sram_ctrl_ret_aon in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_RET_AON_REGS_BASE_ADDR and
/// `SRAM_CTRL_RET_AON_REGS_BASE_ADDR + SRAM_CTRL_RET_AON_REGS_SIZE_BYTES`.
pub const SRAM_CTRL_RET_AON_REGS_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for regs device on rv_dm in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_DM_REGS_BASE_ADDR: usize = 0x21200000;

/// Peripheral size for regs device on rv_dm in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_DM_REGS_BASE_ADDR and
/// `RV_DM_REGS_BASE_ADDR + RV_DM_REGS_SIZE_BYTES`.
pub const RV_DM_REGS_SIZE_BYTES: usize = 0x10;

/// Peripheral base address for mem device on rv_dm in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_DM_MEM_BASE_ADDR: usize = 0x40000;

/// Peripheral size for mem device on rv_dm in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_DM_MEM_BASE_ADDR and
/// `RV_DM_MEM_BASE_ADDR + RV_DM_MEM_SIZE_BYTES`.
pub const RV_DM_MEM_SIZE_BYTES: usize = 0x1000;

/// Peripheral base address for rv_plic_pwc in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_PLIC_PWC_BASE_ADDR: usize = 0x28000000;

/// Peripheral size for rv_plic_pwc in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_PLIC_PWC_BASE_ADDR and
/// `RV_PLIC_PWC_BASE_ADDR + RV_PLIC_PWC_SIZE_BYTES`.
pub const RV_PLIC_PWC_SIZE_BYTES: usize = 0x8000000;

/// Peripheral base address for regs device on sram_ctrl_main in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_MAIN_REGS_BASE_ADDR: usize = 0x211C0000;

/// Peripheral size for regs device on sram_ctrl_main in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_MAIN_REGS_BASE_ADDR and
/// `SRAM_CTRL_MAIN_REGS_BASE_ADDR + SRAM_CTRL_MAIN_REGS_SIZE_BYTES`.
pub const SRAM_CTRL_MAIN_REGS_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for regs device on sram_ctrl_mbox in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_MBOX_REGS_BASE_ADDR: usize = 0x211D0000;

/// Peripheral size for regs device on sram_ctrl_mbox in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_MBOX_REGS_BASE_ADDR and
/// `SRAM_CTRL_MBOX_REGS_BASE_ADDR + SRAM_CTRL_MBOX_REGS_SIZE_BYTES`.
pub const SRAM_CTRL_MBOX_REGS_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for dma in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const DMA_BASE_ADDR: usize = 0x22010000;

/// Peripheral size for dma in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #DMA_BASE_ADDR and
/// `DMA_BASE_ADDR + DMA_SIZE_BYTES`.
pub const DMA_SIZE_BYTES: usize = 0x200;

/// Peripheral base address for core device on mbx0 in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX0_CORE_BASE_ADDR: usize = 0x22000000;

/// Peripheral size for core device on mbx0 in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX0_CORE_BASE_ADDR and
/// `MBX0_CORE_BASE_ADDR + MBX0_CORE_SIZE_BYTES`.
pub const MBX0_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx1 in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX1_CORE_BASE_ADDR: usize = 0x22000100;

/// Peripheral size for core device on mbx1 in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX1_CORE_BASE_ADDR and
/// `MBX1_CORE_BASE_ADDR + MBX1_CORE_SIZE_BYTES`.
pub const MBX1_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx2 in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX2_CORE_BASE_ADDR: usize = 0x22000200;

/// Peripheral size for core device on mbx2 in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX2_CORE_BASE_ADDR and
/// `MBX2_CORE_BASE_ADDR + MBX2_CORE_SIZE_BYTES`.
pub const MBX2_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx3 in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX3_CORE_BASE_ADDR: usize = 0x22000300;

/// Peripheral size for core device on mbx3 in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX3_CORE_BASE_ADDR and
/// `MBX3_CORE_BASE_ADDR + MBX3_CORE_SIZE_BYTES`.
pub const MBX3_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx4 in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX4_CORE_BASE_ADDR: usize = 0x22000400;

/// Peripheral size for core device on mbx4 in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX4_CORE_BASE_ADDR and
/// `MBX4_CORE_BASE_ADDR + MBX4_CORE_SIZE_BYTES`.
pub const MBX4_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx5 in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX5_CORE_BASE_ADDR: usize = 0x22000500;

/// Peripheral size for core device on mbx5 in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX5_CORE_BASE_ADDR and
/// `MBX5_CORE_BASE_ADDR + MBX5_CORE_SIZE_BYTES`.
pub const MBX5_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx_pcie0 in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX_PCIE0_CORE_BASE_ADDR: usize = 0x22040000;

/// Peripheral size for core device on mbx_pcie0 in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX_PCIE0_CORE_BASE_ADDR and
/// `MBX_PCIE0_CORE_BASE_ADDR + MBX_PCIE0_CORE_SIZE_BYTES`.
pub const MBX_PCIE0_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for cfg device on rv_core_ibex_pwc in top pwc.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_CORE_IBEX_PWC_CFG_BASE_ADDR: usize = 0x211F0000;

/// Peripheral size for cfg device on rv_core_ibex_pwc in top pwc.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_CORE_IBEX_PWC_CFG_BASE_ADDR and
/// `RV_CORE_IBEX_PWC_CFG_BASE_ADDR + RV_CORE_IBEX_PWC_CFG_SIZE_BYTES`.
pub const RV_CORE_IBEX_PWC_CFG_SIZE_BYTES: usize = 0x800;

/// Memory base address for ctn in top pwc.
pub const PWC_SOC_PROXY_CTN_BASE_ADDR: usize = 0x40000000;

/// Memory size for ctn in top pwc.
pub const PWC_SOC_PROXY_CTN_SIZE_BYTES: usize = 0x80000000;

/// Memory base address for ram_ret_aon in top pwc.
pub const SRAM_CTRL_RET_AON_RAM_BASE_ADDR: usize = 0x30600000;

/// Memory size for ram_ret_aon in top pwc.
pub const SRAM_CTRL_RET_AON_RAM_SIZE_BYTES: usize = 0x1000;

/// Memory base address for ram_main in top pwc.
pub const SRAM_CTRL_MAIN_RAM_BASE_ADDR: usize = 0x10000000;

/// Memory size for ram_main in top pwc.
pub const SRAM_CTRL_MAIN_RAM_SIZE_BYTES: usize = 0x10000;

/// Memory base address for ram_mbox in top pwc.
pub const SRAM_CTRL_MBOX_RAM_BASE_ADDR: usize = 0x11000000;

/// Memory size for ram_mbox in top pwc.
pub const SRAM_CTRL_MBOX_RAM_SIZE_BYTES: usize = 0x1000;

/// PLIC Interrupt Source Peripheral.
///
/// Enumeration used to determine which peripheral asserted the corresponding
/// interrupt.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicPwcPeripheral {
    /// Unknown Peripheral
    Unknown = 0,
    /// gpio
    Gpio = 1,
    /// rv_timer
    RvTimer = 2,
    /// aon_timer_aon
    AonTimerAon = 3,
    /// dma
    Dma = 4,
    /// mbx0
    Mbx0 = 5,
    /// mbx1
    Mbx1 = 6,
    /// mbx2
    Mbx2 = 7,
    /// mbx3
    Mbx3 = 8,
    /// mbx4
    Mbx4 = 9,
    /// mbx5
    Mbx5 = 10,
    /// mbx_pcie0
    MbxPcie0 = 11,
}

impl TryFrom<u32> for PlicPwcPeripheral {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::Unknown),
            1 => Ok(Self::Gpio),
            2 => Ok(Self::RvTimer),
            3 => Ok(Self::AonTimerAon),
            4 => Ok(Self::Dma),
            5 => Ok(Self::Mbx0),
            6 => Ok(Self::Mbx1),
            7 => Ok(Self::Mbx2),
            8 => Ok(Self::Mbx3),
            9 => Ok(Self::Mbx4),
            10 => Ok(Self::Mbx5),
            11 => Ok(Self::MbxPcie0),
            _ => Err(val),
        }
    }
}

/// PLIC Interrupt Source.
///
/// Enumeration of all PLIC interrupt sources. The interrupt sources belonging to
/// the same peripheral are guaranteed to be consecutive.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicPwcIrqId {
    /// No Interrupt
    None = 0,
    /// gpio_gpio 0
    GpioGpio0 = 1,
    /// gpio_gpio 1
    GpioGpio1 = 2,
    /// gpio_gpio 2
    GpioGpio2 = 3,
    /// gpio_gpio 3
    GpioGpio3 = 4,
    /// gpio_gpio 4
    GpioGpio4 = 5,
    /// gpio_gpio 5
    GpioGpio5 = 6,
    /// gpio_gpio 6
    GpioGpio6 = 7,
    /// gpio_gpio 7
    GpioGpio7 = 8,
    /// gpio_gpio 8
    GpioGpio8 = 9,
    /// gpio_gpio 9
    GpioGpio9 = 10,
    /// gpio_gpio 10
    GpioGpio10 = 11,
    /// gpio_gpio 11
    GpioGpio11 = 12,
    /// gpio_gpio 12
    GpioGpio12 = 13,
    /// gpio_gpio 13
    GpioGpio13 = 14,
    /// gpio_gpio 14
    GpioGpio14 = 15,
    /// gpio_gpio 15
    GpioGpio15 = 16,
    /// gpio_gpio 16
    GpioGpio16 = 17,
    /// gpio_gpio 17
    GpioGpio17 = 18,
    /// gpio_gpio 18
    GpioGpio18 = 19,
    /// gpio_gpio 19
    GpioGpio19 = 20,
    /// gpio_gpio 20
    GpioGpio20 = 21,
    /// gpio_gpio 21
    GpioGpio21 = 22,
    /// gpio_gpio 22
    GpioGpio22 = 23,
    /// gpio_gpio 23
    GpioGpio23 = 24,
    /// gpio_gpio 24
    GpioGpio24 = 25,
    /// gpio_gpio 25
    GpioGpio25 = 26,
    /// gpio_gpio 26
    GpioGpio26 = 27,
    /// gpio_gpio 27
    GpioGpio27 = 28,
    /// gpio_gpio 28
    GpioGpio28 = 29,
    /// gpio_gpio 29
    GpioGpio29 = 30,
    /// gpio_gpio 30
    GpioGpio30 = 31,
    /// gpio_gpio 31
    GpioGpio31 = 32,
    /// rv_timer_timer_expired_hart0_timer0
    RvTimerTimerExpiredHart0Timer0 = 33,
    /// aon_timer_aon_wkup_timer_expired
    AonTimerAonWkupTimerExpired = 34,
    /// aon_timer_aon_wdog_timer_bark
    AonTimerAonWdogTimerBark = 35,
    /// dma_dma_done
    DmaDmaDone = 36,
    /// dma_dma_chunk_done
    DmaDmaChunkDone = 37,
    /// dma_dma_error
    DmaDmaError = 38,
    /// mbx0_mbx_ready
    Mbx0MbxReady = 39,
    /// mbx0_mbx_abort
    Mbx0MbxAbort = 40,
    /// mbx0_mbx_error
    Mbx0MbxError = 41,
    /// mbx1_mbx_ready
    Mbx1MbxReady = 42,
    /// mbx1_mbx_abort
    Mbx1MbxAbort = 43,
    /// mbx1_mbx_error
    Mbx1MbxError = 44,
    /// mbx2_mbx_ready
    Mbx2MbxReady = 45,
    /// mbx2_mbx_abort
    Mbx2MbxAbort = 46,
    /// mbx2_mbx_error
    Mbx2MbxError = 47,
    /// mbx3_mbx_ready
    Mbx3MbxReady = 48,
    /// mbx3_mbx_abort
    Mbx3MbxAbort = 49,
    /// mbx3_mbx_error
    Mbx3MbxError = 50,
    /// mbx4_mbx_ready
    Mbx4MbxReady = 51,
    /// mbx4_mbx_abort
    Mbx4MbxAbort = 52,
    /// mbx4_mbx_error
    Mbx4MbxError = 53,
    /// mbx5_mbx_ready
    Mbx5MbxReady = 54,
    /// mbx5_mbx_abort
    Mbx5MbxAbort = 55,
    /// mbx5_mbx_error
    Mbx5MbxError = 56,
    /// mbx_pcie0_mbx_ready
    MbxPcie0MbxReady = 57,
    /// mbx_pcie0_mbx_abort
    MbxPcie0MbxAbort = 58,
    /// mbx_pcie0_mbx_error
    MbxPcie0MbxError = 59,
    /// PWC_LTEU_SOC_HOT
    PwcLteuSocHot = 60,
    /// PWC_LTEU_FW_TRIP
    PwcLteuFwTrip = 61,
    /// PWC_LTEU_CAT_TRIP
    PwcLteuCatTrip = 62,
    /// LIO_GRP_A_IBEX_IRQ
    LioGrpAIbexIrq = 63,
    /// LIO_GRP_B_IBEX_IRQ
    LioGrpBIbexIrq = 64,
    /// LIO_GRP_C_IBEX_IRQ
    LioGrpCIbexIrq = 65,
    /// DUC0_ducPvlReq0
    Duc0Ducpvlreq0 = 66,
    /// DUC1_ducPvlReq1
    Duc1Ducpvlreq1 = 67,
    /// DUC0_ducIvdrReq0
    Duc0Ducivdrreq0 = 68,
    /// DUC1_ducIvdrReq1
    Duc1Ducivdrreq1 = 69,
    /// PWC_DVFS_TargetCmdAVS0
    PwcDvfsTargetcmdavs0 = 70,
    /// PWC_DVFS_TargetCmdAVS1
    PwcDvfsTargetcmdavs1 = 71,
    /// PWC_DVFS_TargetCmdAVS2
    PwcDvfsTargetcmdavs2 = 72,
    /// PWC_DVFS_TargetCmdAVS3
    PwcDvfsTargetcmdavs3 = 73,
    /// PWC_DVFS_TargetCmdAVS4
    PwcDvfsTargetcmdavs4 = 74,
    /// PWC_DVFS_TargetCmdAVS5
    PwcDvfsTargetcmdavs5 = 75,
    /// PWC_DVFS_TargetCmdAVS6
    PwcDvfsTargetcmdavs6 = 76,
    /// PWC_DVFS_TargetCmdAVS7
    PwcDvfsTargetcmdavs7 = 77,
    /// PWC_DVFS_TargetCmdAVS8
    PwcDvfsTargetcmdavs8 = 78,
    /// PWC_DVFS_TargetCmdAVS9
    PwcDvfsTargetcmdavs9 = 79,
    /// PWC_DVFS_TargetCmdAVS10
    PwcDvfsTargetcmdavs10 = 80,
    /// PWC_DVFS_TargetCmdAVS11
    PwcDvfsTargetcmdavs11 = 81,
    /// PWC_DVFS_TargetCmdAVS12
    PwcDvfsTargetcmdavs12 = 82,
    /// PWC_DVFS_TargetCmdAVS13
    PwcDvfsTargetcmdavs13 = 83,
    /// PWC_AVS_AVS_ERROR_0
    PwcAvsAvsError0 = 84,
    /// PWC_AVS_AVS_ERROR_1
    PwcAvsAvsError1 = 85,
    /// PWC_AVS_AVS_ERROR_2
    PwcAvsAvsError2 = 86,
    /// PWC_AVS_AVS_ERROR_3
    PwcAvsAvsError3 = 87,
    /// PWC_AVS_AVS_ERROR_4
    PwcAvsAvsError4 = 88,
    /// PWC_AVS_AVS_ERROR_5
    PwcAvsAvsError5 = 89,
    /// PWC_AVS_AVS_ERROR_6
    PwcAvsAvsError6 = 90,
    /// PWC_AVS_AVS_ERROR_7
    PwcAvsAvsError7 = 91,
    /// PWC_AVS_AVS_ERROR_8
    PwcAvsAvsError8 = 92,
    /// PWC_AVS_AVS_ERROR_9
    PwcAvsAvsError9 = 93,
    /// PWC_AVS_AVS_ERROR_10
    PwcAvsAvsError10 = 94,
    /// PWC_AVS_AVS_ERROR_11
    PwcAvsAvsError11 = 95,
    /// PWC_AVS_AVS_ERROR_12
    PwcAvsAvsError12 = 96,
    /// PWC_AVS_AVS_ERROR_13
    PwcAvsAvsError13 = 97,
    /// PWC_AVS_AVS_ERROR_14
    PwcAvsAvsError14 = 98,
    /// PWC_AVS_AVS_ERROR_15
    PwcAvsAvsError15 = 99,
    /// PWC_AVS_AVS_ERROR_16
    PwcAvsAvsError16 = 100,
    /// PWC_AVS_AVS_ERROR_17
    PwcAvsAvsError17 = 101,
    /// PWC_AVS_AVS_ERROR_18
    PwcAvsAvsError18 = 102,
    /// PWC_AVS_AVS_ERROR_19
    PwcAvsAvsError19 = 103,
    /// PWC_AVS_AVS_ERROR_20
    PwcAvsAvsError20 = 104,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_0
    PwcAvsAvsResponseToFw0 = 105,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_1
    PwcAvsAvsResponseToFw1 = 106,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_2
    PwcAvsAvsResponseToFw2 = 107,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_3
    PwcAvsAvsResponseToFw3 = 108,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_4
    PwcAvsAvsResponseToFw4 = 109,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_5
    PwcAvsAvsResponseToFw5 = 110,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_6
    PwcAvsAvsResponseToFw6 = 111,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_7
    PwcAvsAvsResponseToFw7 = 112,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_8
    PwcAvsAvsResponseToFw8 = 113,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_9
    PwcAvsAvsResponseToFw9 = 114,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_10
    PwcAvsAvsResponseToFw10 = 115,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_11
    PwcAvsAvsResponseToFw11 = 116,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_12
    PwcAvsAvsResponseToFw12 = 117,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_13
    PwcAvsAvsResponseToFw13 = 118,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_14
    PwcAvsAvsResponseToFw14 = 119,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_15
    PwcAvsAvsResponseToFw15 = 120,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_16
    PwcAvsAvsResponseToFw16 = 121,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_17
    PwcAvsAvsResponseToFw17 = 122,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_18
    PwcAvsAvsResponseToFw18 = 123,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_19
    PwcAvsAvsResponseToFw19 = 124,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_20
    PwcAvsAvsResponseToFw20 = 125,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_21
    PwcAvsAvsResponseToFw21 = 126,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_22
    PwcAvsAvsResponseToFw22 = 127,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_23
    PwcAvsAvsResponseToFw23 = 128,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_24
    PwcAvsAvsResponseToFw24 = 129,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_25
    PwcAvsAvsResponseToFw25 = 130,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_26
    PwcAvsAvsResponseToFw26 = 131,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_27
    PwcAvsAvsResponseToFw27 = 132,
    /// PWC_AVS_AVS_RESPONSE_TO_FW_28
    PwcAvsAvsResponseToFw28 = 133,
    /// PWC_BCAST_C_STATE_ENTRY
    PwcBcastCStateEntry = 134,
    /// PWC_BCAST_C_STATE_EXIT
    PwcBcastCStateExit = 135,
    /// PWC_BCAST_DPA_IDLE_ENTRY
    PwcBcastDpaIdleEntry = 136,
    /// PWC_BCAST_DPA_IDLE_EXIT
    PwcBcastDpaIdleExit = 137,
    /// PWC_CCS_0_PWR_VIRUS_LVL_REQ
    PwcCcs0PwrVirusLvlReq = 138,
    /// PWC_CCS_1_PWR_VIRUS_LVL_REQ
    PwcCcs1PwrVirusLvlReq = 139,
    /// PWC_CCS_2_PWR_VIRUS_LVL_REQ
    PwcCcs2PwrVirusLvlReq = 140,
    /// PWC_CCS_3_PWR_VIRUS_LVL_REQ
    PwcCcs3PwrVirusLvlReq = 141,
    /// PWC_CCS_4_PWR_VIRUS_LVL_REQ
    PwcCcs4PwrVirusLvlReq = 142,
    /// PWC_CCS_5_PWR_VIRUS_LVL_REQ
    PwcCcs5PwrVirusLvlReq = 143,
    /// PWC_CCS_0_DVFS_FSM
    PwcCcs0DvfsFsm = 144,
    /// PWC_CCS_1_DVFS_FSM
    PwcCcs1DvfsFsm = 145,
    /// PWC_DVFS_SocDpaFsmstatus0
    PwcDvfsSocdpafsmstatus0 = 146,
    /// PWC_DVFS_SocDpaFsmstatus1
    PwcDvfsSocdpafsmstatus1 = 147,
    /// PWC_DVFS_SocDpaFsmstatus2
    PwcDvfsSocdpafsmstatus2 = 148,
    /// PWC_DVFS_SocDpaFsmstatus3
    PwcDvfsSocdpafsmstatus3 = 149,
    /// PWC_DVFS_SocDpaFsmstatus4
    PwcDvfsSocdpafsmstatus4 = 150,
    /// PWC_DVFS_SocDpaFsmstatus5
    PwcDvfsSocdpafsmstatus5 = 151,
    /// PWC_HMS_0_STATUS
    PwcHms0Status = 152,
    /// PWC_HMS_1_STATUS
    PwcHms1Status = 153,
    /// PWC_HMS_2_STATUS
    PwcHms2Status = 154,
    /// PWC_HMS_3_STATUS
    PwcHms3Status = 155,
    /// PWC_PCS_0_ALL_PORTS_STATUS
    PwcPcs0AllPortsStatus = 156,
    /// PWC_PCS_0_LINK_BRINGUP_0
    PwcPcs0LinkBringup0 = 157,
    /// PWC_PCS_0_LINK_BRINGUP_1
    PwcPcs0LinkBringup1 = 158,
    /// PWC_PCS_0_LINK_BRINGUP_2
    PwcPcs0LinkBringup2 = 159,
    /// PWC_PCS_0_LINK_BRINGUP_3
    PwcPcs0LinkBringup3 = 160,
    /// PWC_PCS_0_MSG_CTRL
    PwcPcs0MsgCtrl = 161,
    /// PWC_PCS_0_PHY_STATUS
    PwcPcs0PhyStatus = 162,
    /// PWC_PCS_1_ALL_PORTS_STATUS
    PwcPcs1AllPortsStatus = 163,
    /// PWC_PCS_1_LINK_BRINGUP_0
    PwcPcs1LinkBringup0 = 164,
    /// PWC_PCS_1_LINK_BRINGUP_1
    PwcPcs1LinkBringup1 = 165,
    /// PWC_PCS_1_LINK_BRINGUP_2
    PwcPcs1LinkBringup2 = 166,
    /// PWC_PCS_1_LINK_BRINGUP_3
    PwcPcs1LinkBringup3 = 167,
    /// PWC_PCS_1_MSG_CTRL
    PwcPcs1MsgCtrl = 168,
    /// PWC_PCS_1_PHY_STATUS
    PwcPcs1PhyStatus = 169,
    /// PWC_PCS_2_ALL_PORTS_STATUS
    PwcPcs2AllPortsStatus = 170,
    /// PWC_PCS_2_LINK_BRINGUP_0
    PwcPcs2LinkBringup0 = 171,
    /// PWC_PCS_2_LINK_BRINGUP_1
    PwcPcs2LinkBringup1 = 172,
    /// PWC_PCS_2_LINK_BRINGUP_2
    PwcPcs2LinkBringup2 = 173,
    /// PWC_PCS_2_LINK_BRINGUP_3
    PwcPcs2LinkBringup3 = 174,
    /// PWC_PCS_2_MSG_CTRL
    PwcPcs2MsgCtrl = 175,
    /// PWC_PCS_2_PHY_STATUS
    PwcPcs2PhyStatus = 176,
    /// PWC_PCS_3_ALL_PORTS_STATUS
    PwcPcs3AllPortsStatus = 177,
    /// PWC_PCS_3_LINK_BRINGUP_0
    PwcPcs3LinkBringup0 = 178,
    /// PWC_PCS_3_LINK_BRINGUP_1
    PwcPcs3LinkBringup1 = 179,
    /// PWC_PCS_3_LINK_BRINGUP_2
    PwcPcs3LinkBringup2 = 180,
    /// PWC_PCS_3_LINK_BRINGUP_3
    PwcPcs3LinkBringup3 = 181,
    /// PWC_PCS_3_MSG_CTRL
    PwcPcs3MsgCtrl = 182,
    /// PWC_PCS_3_PHY_STATUS
    PwcPcs3PhyStatus = 183,
    /// PWC_PCS_4_ALL_PORTS_STATUS
    PwcPcs4AllPortsStatus = 184,
    /// PWC_PCS_4_LINK_BRINGUP_0
    PwcPcs4LinkBringup0 = 185,
    /// PWC_PCS_4_LINK_BRINGUP_1
    PwcPcs4LinkBringup1 = 186,
    /// PWC_PCS_4_LINK_BRINGUP_2
    PwcPcs4LinkBringup2 = 187,
    /// PWC_PCS_4_LINK_BRINGUP_3
    PwcPcs4LinkBringup3 = 188,
    /// PWC_PCS_4_MSG_CTRL
    PwcPcs4MsgCtrl = 189,
    /// PWC_PCS_4_PHY_STATUS
    PwcPcs4PhyStatus = 190,
    /// PWC_PCS_5_ALL_PORTS_STATUS
    PwcPcs5AllPortsStatus = 191,
    /// PWC_PCS_5_LINK_BRINGUP_0
    PwcPcs5LinkBringup0 = 192,
    /// PWC_PCS_5_LINK_BRINGUP_1
    PwcPcs5LinkBringup1 = 193,
    /// PWC_PCS_5_LINK_BRINGUP_2
    PwcPcs5LinkBringup2 = 194,
    /// PWC_PCS_5_LINK_BRINGUP_3
    PwcPcs5LinkBringup3 = 195,
    /// PWC_PCS_5_MSG_CTRL
    PwcPcs5MsgCtrl = 196,
    /// PWC_PCS_5_PHY_STATUS
    PwcPcs5PhyStatus = 197,
    /// PWC_PCS_6_ALL_PORTS_STATUS
    PwcPcs6AllPortsStatus = 198,
    /// PWC_PCS_6_LINK_BRINGUP_0
    PwcPcs6LinkBringup0 = 199,
    /// PWC_PCS_6_LINK_BRINGUP_1
    PwcPcs6LinkBringup1 = 200,
    /// PWC_PCS_6_LINK_BRINGUP_2
    PwcPcs6LinkBringup2 = 201,
    /// PWC_PCS_6_LINK_BRINGUP_3
    PwcPcs6LinkBringup3 = 202,
    /// PWC_PCS_6_MSG_CTRL
    PwcPcs6MsgCtrl = 203,
    /// PWC_PCS_6_PHY_STATUS
    PwcPcs6PhyStatus = 204,
    /// PWC_PCS_7_ALL_PORTS_STATUS
    PwcPcs7AllPortsStatus = 205,
    /// PWC_PCS_7_LINK_BRINGUP_0
    PwcPcs7LinkBringup0 = 206,
    /// PWC_PCS_7_LINK_BRINGUP_1
    PwcPcs7LinkBringup1 = 207,
    /// PWC_PCS_7_LINK_BRINGUP_2
    PwcPcs7LinkBringup2 = 208,
    /// PWC_PCS_7_LINK_BRINGUP_3
    PwcPcs7LinkBringup3 = 209,
    /// PWC_PCS_7_MSG_CTRL
    PwcPcs7MsgCtrl = 210,
    /// PWC_PCS_7_PHY_STATUS
    PwcPcs7PhyStatus = 211,
    /// PWC_HDR_IPI_FROM_PWC_0
    PwcHdrIpiFromPwc0 = 212,
    /// PWC_HDR_IPI_FROM_PWC_1
    PwcHdrIpiFromPwc1 = 213,
    /// PWC_HDR_IPI_FROM_PWC_2
    PwcHdrIpiFromPwc2 = 214,
    /// PWC_HDR_IPI_FROM_ROT
    PwcHdrIpiFromRot = 215,
    /// PWC_HDR_IPI_FROM_MIO
    PwcHdrIpiFromMio = 216,
    /// PWC_HDR_IPI_FROM_DUC
    PwcHdrIpiFromDuc = 217,
    /// LIO_GRP_A_IPI_FROM_LIOGRPA_I3C0_PERIPH_RST_REQ
    LioGrpAIpiFromLiogrpaI3c0PeriphRstReq = 218,
    /// LIO_GRP_A_IPI_FROM_LIOGRPA_I3C0_CHIP_RST_REQ
    LioGrpAIpiFromLiogrpaI3c0ChipRstReq = 219,
    /// LIO_GRP_A_IPI_FROM_LIOGRPA_I3C1_PERIPH_RST_REQ
    LioGrpAIpiFromLiogrpaI3c1PeriphRstReq = 220,
    /// LIO_GRP_A_IPI_FROM_LIOGRPA_I3C1_CHIP_RST_REQ
    LioGrpAIpiFromLiogrpaI3c1ChipRstReq = 221,
    /// LIO_GRP_A_IPI_FROM_LIOGRPA_I3C2_PERIPH_RST_REQ
    LioGrpAIpiFromLiogrpaI3c2PeriphRstReq = 222,
    /// LIO_GRP_A_IPI_FROM_LIOGRPA_I3C2_CHIP_RST_REQ
    LioGrpAIpiFromLiogrpaI3c2ChipRstReq = 223,
    /// LIO_GRP_B_IPI_FROM_LIOGRPB_I3C0_PERIPH_RST_REQ
    LioGrpBIpiFromLiogrpbI3c0PeriphRstReq = 224,
    /// LIO_GRP_B_IPI_FROM_LIOGRPB_I3C0_CHIP_RST_REQ
    LioGrpBIpiFromLiogrpbI3c0ChipRstReq = 225,
    /// LIO_GRP_B_IPI_FROM_LIOGRPB_I3C1_PERIPH_RST_REQ
    LioGrpBIpiFromLiogrpbI3c1PeriphRstReq = 226,
    /// LIO_GRP_B_IPI_FROM_LIOGRPB_I3C1_CHIP_RST_REQ
    LioGrpBIpiFromLiogrpbI3c1ChipRstReq = 227,
    /// LIO_GRP_B_IPI_FROM_LIOGRPB_I3C2_PERIPH_RST_REQ
    LioGrpBIpiFromLiogrpbI3c2PeriphRstReq = 228,
    /// LIO_GRP_B_IPI_FROM_LIOGRPB_I3C2_CHIP_RST_REQ
    LioGrpBIpiFromLiogrpbI3c2ChipRstReq = 229,
    /// LIO_GRP_C_IPI_FROM_LIOGRPC_I3C0_PERIPH_RST_REQ
    LioGrpCIpiFromLiogrpcI3c0PeriphRstReq = 230,
    /// LIO_GRP_C_IPI_FROM_LIOGRPC_I3C0_CHIP_RST_REQ
    LioGrpCIpiFromLiogrpcI3c0ChipRstReq = 231,
    /// LIO_GRP_C_IPI_FROM_LIOGRPC_I3C1_PERIPH_RST_REQ
    LioGrpCIpiFromLiogrpcI3c1PeriphRstReq = 232,
    /// LIO_GRP_C_IPI_FROM_LIOGRPC_I3C1_CHIP_RST_REQ
    LioGrpCIpiFromLiogrpcI3c1ChipRstReq = 233,
    /// LIO_GRP_C_IPI_FROM_LIOGRPC_I3C2_PERIPH_RST_REQ
    LioGrpCIpiFromLiogrpcI3c2PeriphRstReq = 234,
    /// LIO_GRP_C_IPI_FROM_LIOGRPC_I3C2_CHIP_RST_REQ
    LioGrpCIpiFromLiogrpcI3c2ChipRstReq = 235,
    /// LIO_GRP_D_IPI_FROM_LIOGRPD_I3C0_PERIPH_RST_REQ
    LioGrpDIpiFromLiogrpdI3c0PeriphRstReq = 236,
    /// LIO_GRP_D_IPI_FROM_LIOGRPD_I3C0_CHIP_RST_REQ
    LioGrpDIpiFromLiogrpdI3c0ChipRstReq = 237,
    /// LIO_GRP_D_IPI_FROM_LIOGRPD_I3C1_PERIPH_RST_REQ
    LioGrpDIpiFromLiogrpdI3c1PeriphRstReq = 238,
    /// LIO_GRP_D_IPI_FROM_LIOGRPD_I3C1_CHIP_RST_REQ
    LioGrpDIpiFromLiogrpdI3c1ChipRstReq = 239,
    /// LIO_GRP_D_IPI_FROM_LIOGRPD_I3C2_PERIPH_RST_REQ
    LioGrpDIpiFromLiogrpdI3c2PeriphRstReq = 240,
    /// LIO_GRP_D_IPI_FROM_LIOGRPD_I3C2_CHIP_RST_REQ
    LioGrpDIpiFromLiogrpdI3c2ChipRstReq = 241,
    /// PWC_ERS0_REQ0_ERS_REQ_INTERRUPT
    PwcErs0Req0ErsReqInterrupt = 242,
    /// PWC_ERS0_REQ1_ERS_REQ_INTERRUPT
    PwcErs0Req1ErsReqInterrupt = 243,
    /// PWC_ERS1_REQ0_ERS_REQ_INTERRUPT
    PwcErs1Req0ErsReqInterrupt = 244,
    /// PWC_ERS1_REQ1_ERS_REQ_INTERRUPT
    PwcErs1Req1ErsReqInterrupt = 245,
    /// PWC_CCS_0_CSTATE_ENTRY
    PwcCcs0CstateEntry = 246,
    /// PWC_CCS_0_CSTATE_EXIT
    PwcCcs0CstateExit = 247,
    /// PWC_CCS_1_CSTATE_ENTRY
    PwcCcs1CstateEntry = 248,
    /// PWC_CCS_1_CSTATE_EXIT
    PwcCcs1CstateExit = 249,
}

impl TryFrom<u32> for PlicPwcIrqId {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::None),
            1 => Ok(Self::GpioGpio0),
            2 => Ok(Self::GpioGpio1),
            3 => Ok(Self::GpioGpio2),
            4 => Ok(Self::GpioGpio3),
            5 => Ok(Self::GpioGpio4),
            6 => Ok(Self::GpioGpio5),
            7 => Ok(Self::GpioGpio6),
            8 => Ok(Self::GpioGpio7),
            9 => Ok(Self::GpioGpio8),
            10 => Ok(Self::GpioGpio9),
            11 => Ok(Self::GpioGpio10),
            12 => Ok(Self::GpioGpio11),
            13 => Ok(Self::GpioGpio12),
            14 => Ok(Self::GpioGpio13),
            15 => Ok(Self::GpioGpio14),
            16 => Ok(Self::GpioGpio15),
            17 => Ok(Self::GpioGpio16),
            18 => Ok(Self::GpioGpio17),
            19 => Ok(Self::GpioGpio18),
            20 => Ok(Self::GpioGpio19),
            21 => Ok(Self::GpioGpio20),
            22 => Ok(Self::GpioGpio21),
            23 => Ok(Self::GpioGpio22),
            24 => Ok(Self::GpioGpio23),
            25 => Ok(Self::GpioGpio24),
            26 => Ok(Self::GpioGpio25),
            27 => Ok(Self::GpioGpio26),
            28 => Ok(Self::GpioGpio27),
            29 => Ok(Self::GpioGpio28),
            30 => Ok(Self::GpioGpio29),
            31 => Ok(Self::GpioGpio30),
            32 => Ok(Self::GpioGpio31),
            33 => Ok(Self::RvTimerTimerExpiredHart0Timer0),
            34 => Ok(Self::AonTimerAonWkupTimerExpired),
            35 => Ok(Self::AonTimerAonWdogTimerBark),
            36 => Ok(Self::DmaDmaDone),
            37 => Ok(Self::DmaDmaChunkDone),
            38 => Ok(Self::DmaDmaError),
            39 => Ok(Self::Mbx0MbxReady),
            40 => Ok(Self::Mbx0MbxAbort),
            41 => Ok(Self::Mbx0MbxError),
            42 => Ok(Self::Mbx1MbxReady),
            43 => Ok(Self::Mbx1MbxAbort),
            44 => Ok(Self::Mbx1MbxError),
            45 => Ok(Self::Mbx2MbxReady),
            46 => Ok(Self::Mbx2MbxAbort),
            47 => Ok(Self::Mbx2MbxError),
            48 => Ok(Self::Mbx3MbxReady),
            49 => Ok(Self::Mbx3MbxAbort),
            50 => Ok(Self::Mbx3MbxError),
            51 => Ok(Self::Mbx4MbxReady),
            52 => Ok(Self::Mbx4MbxAbort),
            53 => Ok(Self::Mbx4MbxError),
            54 => Ok(Self::Mbx5MbxReady),
            55 => Ok(Self::Mbx5MbxAbort),
            56 => Ok(Self::Mbx5MbxError),
            57 => Ok(Self::MbxPcie0MbxReady),
            58 => Ok(Self::MbxPcie0MbxAbort),
            59 => Ok(Self::MbxPcie0MbxError),
            60 => Ok(Self::PwcLteuSocHot),
            61 => Ok(Self::PwcLteuFwTrip),
            62 => Ok(Self::PwcLteuCatTrip),
            63 => Ok(Self::LioGrpAIbexIrq),
            64 => Ok(Self::LioGrpBIbexIrq),
            65 => Ok(Self::LioGrpCIbexIrq),
            66 => Ok(Self::Duc0Ducpvlreq0),
            67 => Ok(Self::Duc1Ducpvlreq1),
            68 => Ok(Self::Duc0Ducivdrreq0),
            69 => Ok(Self::Duc1Ducivdrreq1),
            70 => Ok(Self::PwcDvfsTargetcmdavs0),
            71 => Ok(Self::PwcDvfsTargetcmdavs1),
            72 => Ok(Self::PwcDvfsTargetcmdavs2),
            73 => Ok(Self::PwcDvfsTargetcmdavs3),
            74 => Ok(Self::PwcDvfsTargetcmdavs4),
            75 => Ok(Self::PwcDvfsTargetcmdavs5),
            76 => Ok(Self::PwcDvfsTargetcmdavs6),
            77 => Ok(Self::PwcDvfsTargetcmdavs7),
            78 => Ok(Self::PwcDvfsTargetcmdavs8),
            79 => Ok(Self::PwcDvfsTargetcmdavs9),
            80 => Ok(Self::PwcDvfsTargetcmdavs10),
            81 => Ok(Self::PwcDvfsTargetcmdavs11),
            82 => Ok(Self::PwcDvfsTargetcmdavs12),
            83 => Ok(Self::PwcDvfsTargetcmdavs13),
            84 => Ok(Self::PwcAvsAvsError0),
            85 => Ok(Self::PwcAvsAvsError1),
            86 => Ok(Self::PwcAvsAvsError2),
            87 => Ok(Self::PwcAvsAvsError3),
            88 => Ok(Self::PwcAvsAvsError4),
            89 => Ok(Self::PwcAvsAvsError5),
            90 => Ok(Self::PwcAvsAvsError6),
            91 => Ok(Self::PwcAvsAvsError7),
            92 => Ok(Self::PwcAvsAvsError8),
            93 => Ok(Self::PwcAvsAvsError9),
            94 => Ok(Self::PwcAvsAvsError10),
            95 => Ok(Self::PwcAvsAvsError11),
            96 => Ok(Self::PwcAvsAvsError12),
            97 => Ok(Self::PwcAvsAvsError13),
            98 => Ok(Self::PwcAvsAvsError14),
            99 => Ok(Self::PwcAvsAvsError15),
            100 => Ok(Self::PwcAvsAvsError16),
            101 => Ok(Self::PwcAvsAvsError17),
            102 => Ok(Self::PwcAvsAvsError18),
            103 => Ok(Self::PwcAvsAvsError19),
            104 => Ok(Self::PwcAvsAvsError20),
            105 => Ok(Self::PwcAvsAvsResponseToFw0),
            106 => Ok(Self::PwcAvsAvsResponseToFw1),
            107 => Ok(Self::PwcAvsAvsResponseToFw2),
            108 => Ok(Self::PwcAvsAvsResponseToFw3),
            109 => Ok(Self::PwcAvsAvsResponseToFw4),
            110 => Ok(Self::PwcAvsAvsResponseToFw5),
            111 => Ok(Self::PwcAvsAvsResponseToFw6),
            112 => Ok(Self::PwcAvsAvsResponseToFw7),
            113 => Ok(Self::PwcAvsAvsResponseToFw8),
            114 => Ok(Self::PwcAvsAvsResponseToFw9),
            115 => Ok(Self::PwcAvsAvsResponseToFw10),
            116 => Ok(Self::PwcAvsAvsResponseToFw11),
            117 => Ok(Self::PwcAvsAvsResponseToFw12),
            118 => Ok(Self::PwcAvsAvsResponseToFw13),
            119 => Ok(Self::PwcAvsAvsResponseToFw14),
            120 => Ok(Self::PwcAvsAvsResponseToFw15),
            121 => Ok(Self::PwcAvsAvsResponseToFw16),
            122 => Ok(Self::PwcAvsAvsResponseToFw17),
            123 => Ok(Self::PwcAvsAvsResponseToFw18),
            124 => Ok(Self::PwcAvsAvsResponseToFw19),
            125 => Ok(Self::PwcAvsAvsResponseToFw20),
            126 => Ok(Self::PwcAvsAvsResponseToFw21),
            127 => Ok(Self::PwcAvsAvsResponseToFw22),
            128 => Ok(Self::PwcAvsAvsResponseToFw23),
            129 => Ok(Self::PwcAvsAvsResponseToFw24),
            130 => Ok(Self::PwcAvsAvsResponseToFw25),
            131 => Ok(Self::PwcAvsAvsResponseToFw26),
            132 => Ok(Self::PwcAvsAvsResponseToFw27),
            133 => Ok(Self::PwcAvsAvsResponseToFw28),
            134 => Ok(Self::PwcBcastCStateEntry),
            135 => Ok(Self::PwcBcastCStateExit),
            136 => Ok(Self::PwcBcastDpaIdleEntry),
            137 => Ok(Self::PwcBcastDpaIdleExit),
            138 => Ok(Self::PwcCcs0PwrVirusLvlReq),
            139 => Ok(Self::PwcCcs1PwrVirusLvlReq),
            140 => Ok(Self::PwcCcs2PwrVirusLvlReq),
            141 => Ok(Self::PwcCcs3PwrVirusLvlReq),
            142 => Ok(Self::PwcCcs4PwrVirusLvlReq),
            143 => Ok(Self::PwcCcs5PwrVirusLvlReq),
            144 => Ok(Self::PwcCcs0DvfsFsm),
            145 => Ok(Self::PwcCcs1DvfsFsm),
            146 => Ok(Self::PwcDvfsSocdpafsmstatus0),
            147 => Ok(Self::PwcDvfsSocdpafsmstatus1),
            148 => Ok(Self::PwcDvfsSocdpafsmstatus2),
            149 => Ok(Self::PwcDvfsSocdpafsmstatus3),
            150 => Ok(Self::PwcDvfsSocdpafsmstatus4),
            151 => Ok(Self::PwcDvfsSocdpafsmstatus5),
            152 => Ok(Self::PwcHms0Status),
            153 => Ok(Self::PwcHms1Status),
            154 => Ok(Self::PwcHms2Status),
            155 => Ok(Self::PwcHms3Status),
            156 => Ok(Self::PwcPcs0AllPortsStatus),
            157 => Ok(Self::PwcPcs0LinkBringup0),
            158 => Ok(Self::PwcPcs0LinkBringup1),
            159 => Ok(Self::PwcPcs0LinkBringup2),
            160 => Ok(Self::PwcPcs0LinkBringup3),
            161 => Ok(Self::PwcPcs0MsgCtrl),
            162 => Ok(Self::PwcPcs0PhyStatus),
            163 => Ok(Self::PwcPcs1AllPortsStatus),
            164 => Ok(Self::PwcPcs1LinkBringup0),
            165 => Ok(Self::PwcPcs1LinkBringup1),
            166 => Ok(Self::PwcPcs1LinkBringup2),
            167 => Ok(Self::PwcPcs1LinkBringup3),
            168 => Ok(Self::PwcPcs1MsgCtrl),
            169 => Ok(Self::PwcPcs1PhyStatus),
            170 => Ok(Self::PwcPcs2AllPortsStatus),
            171 => Ok(Self::PwcPcs2LinkBringup0),
            172 => Ok(Self::PwcPcs2LinkBringup1),
            173 => Ok(Self::PwcPcs2LinkBringup2),
            174 => Ok(Self::PwcPcs2LinkBringup3),
            175 => Ok(Self::PwcPcs2MsgCtrl),
            176 => Ok(Self::PwcPcs2PhyStatus),
            177 => Ok(Self::PwcPcs3AllPortsStatus),
            178 => Ok(Self::PwcPcs3LinkBringup0),
            179 => Ok(Self::PwcPcs3LinkBringup1),
            180 => Ok(Self::PwcPcs3LinkBringup2),
            181 => Ok(Self::PwcPcs3LinkBringup3),
            182 => Ok(Self::PwcPcs3MsgCtrl),
            183 => Ok(Self::PwcPcs3PhyStatus),
            184 => Ok(Self::PwcPcs4AllPortsStatus),
            185 => Ok(Self::PwcPcs4LinkBringup0),
            186 => Ok(Self::PwcPcs4LinkBringup1),
            187 => Ok(Self::PwcPcs4LinkBringup2),
            188 => Ok(Self::PwcPcs4LinkBringup3),
            189 => Ok(Self::PwcPcs4MsgCtrl),
            190 => Ok(Self::PwcPcs4PhyStatus),
            191 => Ok(Self::PwcPcs5AllPortsStatus),
            192 => Ok(Self::PwcPcs5LinkBringup0),
            193 => Ok(Self::PwcPcs5LinkBringup1),
            194 => Ok(Self::PwcPcs5LinkBringup2),
            195 => Ok(Self::PwcPcs5LinkBringup3),
            196 => Ok(Self::PwcPcs5MsgCtrl),
            197 => Ok(Self::PwcPcs5PhyStatus),
            198 => Ok(Self::PwcPcs6AllPortsStatus),
            199 => Ok(Self::PwcPcs6LinkBringup0),
            200 => Ok(Self::PwcPcs6LinkBringup1),
            201 => Ok(Self::PwcPcs6LinkBringup2),
            202 => Ok(Self::PwcPcs6LinkBringup3),
            203 => Ok(Self::PwcPcs6MsgCtrl),
            204 => Ok(Self::PwcPcs6PhyStatus),
            205 => Ok(Self::PwcPcs7AllPortsStatus),
            206 => Ok(Self::PwcPcs7LinkBringup0),
            207 => Ok(Self::PwcPcs7LinkBringup1),
            208 => Ok(Self::PwcPcs7LinkBringup2),
            209 => Ok(Self::PwcPcs7LinkBringup3),
            210 => Ok(Self::PwcPcs7MsgCtrl),
            211 => Ok(Self::PwcPcs7PhyStatus),
            212 => Ok(Self::PwcHdrIpiFromPwc0),
            213 => Ok(Self::PwcHdrIpiFromPwc1),
            214 => Ok(Self::PwcHdrIpiFromPwc2),
            215 => Ok(Self::PwcHdrIpiFromRot),
            216 => Ok(Self::PwcHdrIpiFromMio),
            217 => Ok(Self::PwcHdrIpiFromDuc),
            218 => Ok(Self::LioGrpAIpiFromLiogrpaI3c0PeriphRstReq),
            219 => Ok(Self::LioGrpAIpiFromLiogrpaI3c0ChipRstReq),
            220 => Ok(Self::LioGrpAIpiFromLiogrpaI3c1PeriphRstReq),
            221 => Ok(Self::LioGrpAIpiFromLiogrpaI3c1ChipRstReq),
            222 => Ok(Self::LioGrpAIpiFromLiogrpaI3c2PeriphRstReq),
            223 => Ok(Self::LioGrpAIpiFromLiogrpaI3c2ChipRstReq),
            224 => Ok(Self::LioGrpBIpiFromLiogrpbI3c0PeriphRstReq),
            225 => Ok(Self::LioGrpBIpiFromLiogrpbI3c0ChipRstReq),
            226 => Ok(Self::LioGrpBIpiFromLiogrpbI3c1PeriphRstReq),
            227 => Ok(Self::LioGrpBIpiFromLiogrpbI3c1ChipRstReq),
            228 => Ok(Self::LioGrpBIpiFromLiogrpbI3c2PeriphRstReq),
            229 => Ok(Self::LioGrpBIpiFromLiogrpbI3c2ChipRstReq),
            230 => Ok(Self::LioGrpCIpiFromLiogrpcI3c0PeriphRstReq),
            231 => Ok(Self::LioGrpCIpiFromLiogrpcI3c0ChipRstReq),
            232 => Ok(Self::LioGrpCIpiFromLiogrpcI3c1PeriphRstReq),
            233 => Ok(Self::LioGrpCIpiFromLiogrpcI3c1ChipRstReq),
            234 => Ok(Self::LioGrpCIpiFromLiogrpcI3c2PeriphRstReq),
            235 => Ok(Self::LioGrpCIpiFromLiogrpcI3c2ChipRstReq),
            236 => Ok(Self::LioGrpDIpiFromLiogrpdI3c0PeriphRstReq),
            237 => Ok(Self::LioGrpDIpiFromLiogrpdI3c0ChipRstReq),
            238 => Ok(Self::LioGrpDIpiFromLiogrpdI3c1PeriphRstReq),
            239 => Ok(Self::LioGrpDIpiFromLiogrpdI3c1ChipRstReq),
            240 => Ok(Self::LioGrpDIpiFromLiogrpdI3c2PeriphRstReq),
            241 => Ok(Self::LioGrpDIpiFromLiogrpdI3c2ChipRstReq),
            242 => Ok(Self::PwcErs0Req0ErsReqInterrupt),
            243 => Ok(Self::PwcErs0Req1ErsReqInterrupt),
            244 => Ok(Self::PwcErs1Req0ErsReqInterrupt),
            245 => Ok(Self::PwcErs1Req1ErsReqInterrupt),
            246 => Ok(Self::PwcCcs0CstateEntry),
            247 => Ok(Self::PwcCcs0CstateExit),
            248 => Ok(Self::PwcCcs1CstateEntry),
            249 => Ok(Self::PwcCcs1CstateExit),
            _ => Err(val),
        }
    }
}

/// PLIC Interrupt Target.
///
/// Enumeration used to determine which set of IE, CC, threshold registers to
/// access for a given interrupt target.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicPwcTarget {
    /// Ibex rv_core_ibex_pwc
    IbexPwc = 0,
}

/// PLIC Interrupt Source to Peripheral Map
///
/// This array is a mapping from `PlicPwcIrqId` to
/// `PlicPwcPeripheral`.
pub const PLIC_PWC_INTERRUPT_FOR_PERIPHERAL: [PlicPwcPeripheral; 250] = [
    // None -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // GpioGpio0 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio1 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio2 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio3 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio4 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio5 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio6 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio7 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio8 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio9 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio10 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio11 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio12 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio13 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio14 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio15 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio16 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio17 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio18 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio19 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio20 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio21 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio22 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio23 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio24 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio25 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio26 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio27 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio28 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio29 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio30 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // GpioGpio31 -> PlicPwcPeripheral::Gpio
    PlicPwcPeripheral::Gpio,
    // RvTimerTimerExpiredHart0Timer0 -> PlicPwcPeripheral::RvTimer
    PlicPwcPeripheral::RvTimer,
    // AonTimerAonWkupTimerExpired -> PlicPwcPeripheral::AonTimerAon
    PlicPwcPeripheral::AonTimerAon,
    // AonTimerAonWdogTimerBark -> PlicPwcPeripheral::AonTimerAon
    PlicPwcPeripheral::AonTimerAon,
    // DmaDmaDone -> PlicPwcPeripheral::Dma
    PlicPwcPeripheral::Dma,
    // DmaDmaChunkDone -> PlicPwcPeripheral::Dma
    PlicPwcPeripheral::Dma,
    // DmaDmaError -> PlicPwcPeripheral::Dma
    PlicPwcPeripheral::Dma,
    // Mbx0MbxReady -> PlicPwcPeripheral::Mbx0
    PlicPwcPeripheral::Mbx0,
    // Mbx0MbxAbort -> PlicPwcPeripheral::Mbx0
    PlicPwcPeripheral::Mbx0,
    // Mbx0MbxError -> PlicPwcPeripheral::Mbx0
    PlicPwcPeripheral::Mbx0,
    // Mbx1MbxReady -> PlicPwcPeripheral::Mbx1
    PlicPwcPeripheral::Mbx1,
    // Mbx1MbxAbort -> PlicPwcPeripheral::Mbx1
    PlicPwcPeripheral::Mbx1,
    // Mbx1MbxError -> PlicPwcPeripheral::Mbx1
    PlicPwcPeripheral::Mbx1,
    // Mbx2MbxReady -> PlicPwcPeripheral::Mbx2
    PlicPwcPeripheral::Mbx2,
    // Mbx2MbxAbort -> PlicPwcPeripheral::Mbx2
    PlicPwcPeripheral::Mbx2,
    // Mbx2MbxError -> PlicPwcPeripheral::Mbx2
    PlicPwcPeripheral::Mbx2,
    // Mbx3MbxReady -> PlicPwcPeripheral::Mbx3
    PlicPwcPeripheral::Mbx3,
    // Mbx3MbxAbort -> PlicPwcPeripheral::Mbx3
    PlicPwcPeripheral::Mbx3,
    // Mbx3MbxError -> PlicPwcPeripheral::Mbx3
    PlicPwcPeripheral::Mbx3,
    // Mbx4MbxReady -> PlicPwcPeripheral::Mbx4
    PlicPwcPeripheral::Mbx4,
    // Mbx4MbxAbort -> PlicPwcPeripheral::Mbx4
    PlicPwcPeripheral::Mbx4,
    // Mbx4MbxError -> PlicPwcPeripheral::Mbx4
    PlicPwcPeripheral::Mbx4,
    // Mbx5MbxReady -> PlicPwcPeripheral::Mbx5
    PlicPwcPeripheral::Mbx5,
    // Mbx5MbxAbort -> PlicPwcPeripheral::Mbx5
    PlicPwcPeripheral::Mbx5,
    // Mbx5MbxError -> PlicPwcPeripheral::Mbx5
    PlicPwcPeripheral::Mbx5,
    // MbxPcie0MbxReady -> PlicPwcPeripheral::MbxPcie0
    PlicPwcPeripheral::MbxPcie0,
    // MbxPcie0MbxAbort -> PlicPwcPeripheral::MbxPcie0
    PlicPwcPeripheral::MbxPcie0,
    // MbxPcie0MbxError -> PlicPwcPeripheral::MbxPcie0
    PlicPwcPeripheral::MbxPcie0,
    // PwcLteuSocHot -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcLteuFwTrip -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcLteuCatTrip -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpAIbexIrq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpBIbexIrq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpCIbexIrq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // Duc0Ducpvlreq0 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // Duc1Ducpvlreq1 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // Duc0Ducivdrreq0 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // Duc1Ducivdrreq1 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsTargetcmdavs0 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsTargetcmdavs1 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsTargetcmdavs2 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsTargetcmdavs3 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsTargetcmdavs4 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsTargetcmdavs5 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsTargetcmdavs6 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsTargetcmdavs7 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsTargetcmdavs8 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsTargetcmdavs9 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsTargetcmdavs10 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsTargetcmdavs11 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsTargetcmdavs12 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsTargetcmdavs13 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError0 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError1 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError2 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError3 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError4 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError5 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError6 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError7 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError8 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError9 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError10 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError11 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError12 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError13 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError14 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError15 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError16 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError17 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError18 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError19 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsError20 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw0 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw1 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw2 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw3 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw4 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw5 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw6 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw7 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw8 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw9 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw10 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw11 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw12 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw13 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw14 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw15 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw16 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw17 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw18 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw19 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw20 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw21 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw22 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw23 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw24 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw25 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw26 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw27 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcAvsAvsResponseToFw28 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcBcastCStateEntry -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcBcastCStateExit -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcBcastDpaIdleEntry -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcBcastDpaIdleExit -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcCcs0PwrVirusLvlReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcCcs1PwrVirusLvlReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcCcs2PwrVirusLvlReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcCcs3PwrVirusLvlReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcCcs4PwrVirusLvlReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcCcs5PwrVirusLvlReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcCcs0DvfsFsm -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcCcs1DvfsFsm -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsSocdpafsmstatus0 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsSocdpafsmstatus1 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsSocdpafsmstatus2 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsSocdpafsmstatus3 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsSocdpafsmstatus4 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcDvfsSocdpafsmstatus5 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcHms0Status -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcHms1Status -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcHms2Status -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcHms3Status -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs0AllPortsStatus -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs0LinkBringup0 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs0LinkBringup1 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs0LinkBringup2 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs0LinkBringup3 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs0MsgCtrl -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs0PhyStatus -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs1AllPortsStatus -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs1LinkBringup0 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs1LinkBringup1 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs1LinkBringup2 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs1LinkBringup3 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs1MsgCtrl -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs1PhyStatus -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs2AllPortsStatus -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs2LinkBringup0 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs2LinkBringup1 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs2LinkBringup2 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs2LinkBringup3 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs2MsgCtrl -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs2PhyStatus -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs3AllPortsStatus -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs3LinkBringup0 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs3LinkBringup1 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs3LinkBringup2 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs3LinkBringup3 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs3MsgCtrl -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs3PhyStatus -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs4AllPortsStatus -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs4LinkBringup0 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs4LinkBringup1 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs4LinkBringup2 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs4LinkBringup3 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs4MsgCtrl -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs4PhyStatus -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs5AllPortsStatus -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs5LinkBringup0 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs5LinkBringup1 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs5LinkBringup2 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs5LinkBringup3 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs5MsgCtrl -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs5PhyStatus -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs6AllPortsStatus -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs6LinkBringup0 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs6LinkBringup1 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs6LinkBringup2 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs6LinkBringup3 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs6MsgCtrl -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs6PhyStatus -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs7AllPortsStatus -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs7LinkBringup0 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs7LinkBringup1 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs7LinkBringup2 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs7LinkBringup3 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs7MsgCtrl -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcPcs7PhyStatus -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcHdrIpiFromPwc0 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcHdrIpiFromPwc1 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcHdrIpiFromPwc2 -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcHdrIpiFromRot -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcHdrIpiFromMio -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcHdrIpiFromDuc -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpAIpiFromLiogrpaI3c0PeriphRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpAIpiFromLiogrpaI3c0ChipRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpAIpiFromLiogrpaI3c1PeriphRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpAIpiFromLiogrpaI3c1ChipRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpAIpiFromLiogrpaI3c2PeriphRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpAIpiFromLiogrpaI3c2ChipRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpBIpiFromLiogrpbI3c0PeriphRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpBIpiFromLiogrpbI3c0ChipRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpBIpiFromLiogrpbI3c1PeriphRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpBIpiFromLiogrpbI3c1ChipRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpBIpiFromLiogrpbI3c2PeriphRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpBIpiFromLiogrpbI3c2ChipRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpCIpiFromLiogrpcI3c0PeriphRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpCIpiFromLiogrpcI3c0ChipRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpCIpiFromLiogrpcI3c1PeriphRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpCIpiFromLiogrpcI3c1ChipRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpCIpiFromLiogrpcI3c2PeriphRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpCIpiFromLiogrpcI3c2ChipRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpDIpiFromLiogrpdI3c0PeriphRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpDIpiFromLiogrpdI3c0ChipRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpDIpiFromLiogrpdI3c1PeriphRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpDIpiFromLiogrpdI3c1ChipRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpDIpiFromLiogrpdI3c2PeriphRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // LioGrpDIpiFromLiogrpdI3c2ChipRstReq -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcErs0Req0ErsReqInterrupt -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcErs0Req1ErsReqInterrupt -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcErs1Req0ErsReqInterrupt -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcErs1Req1ErsReqInterrupt -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcCcs0CstateEntry -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcCcs0CstateExit -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcCcs1CstateEntry -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
    // PwcCcs1CstateExit -> PlicPwcPeripheral::Unknown
    PlicPwcPeripheral::Unknown,
];

/// MPWC Region
///
/// MMIO region excludes any memory that is separate from the module
/// configuration space, i.e. ROM, main SRAM, and mbx SRAM are excluded but
/// retention SRAM or spi_device are included.
pub const TOP_PWC_MPWC_BASE_ADDR: usize = 0x211C0000;
pub const TOP_PWC_MPWC_SIZE_BYTES: usize = 0xF441000;
